package main

import (
	"flag"
	"log"

	"github.com/gin-gonic/gin"
	_ "github.com/mremperor-atwork/rpg1/api1/docs" // This is generated by swag
	"github.com/mremperor-atwork/rpg1/api1/internal/config"
	"github.com/mremperor-atwork/rpg1/api1/internal/database"
	"github.com/mremperor-atwork/rpg1/api1/internal/handlers"
	"github.com/mremperor-atwork/rpg1/api1/internal/routes"
	"github.com/mremperor-atwork/rpg1/api1/internal/supabase"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title           RPG API
// @version         1.0
// @description     A comprehensive RPG game API with authentication, characters, and SRD content.
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.

func main() {
	// Parse command line flags
	migrate := flag.Bool("migrate", false, "Run database migrations")
	flag.Parse()

	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("failed to load config: %v", err)
	}

	if err := supabase.Connect(cfg.SupabaseURL, cfg.SupabaseKey); err != nil {
		log.Fatalf("failed to connect to Supabase: %v", err)
	}
	defer supabase.Close()

	if err := database.Connect(cfg.DatabaseURL); err != nil {
		log.Fatalf("failed to connect to database: %v", err)
	}
	defer database.Close()

	// Run migrations if requested
	if *migrate {
		log.Println("Running database migrations...")
		if err := database.RunMigrationsIfNeeded(); err != nil {
			log.Fatalf("failed to run migrations: %v", err)
		}
		log.Println("Migrations completed successfully!")
		return
	}

	r := gin.Default()

	r.GET("/health", handlers.HealthCheck)

	// Swagger documentation endpoint
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	routes.SetupAuthRoutes(r)
	routes.SetupSRDRoutes(r)
	routes.SetupCharacterRoutes(r)
	routes.SetupUserRoutes(r)

	log.Printf("Starting server on %s", cfg.ServerAddress)
	log.Printf("Swagger documentation available at: http://%s/swagger/index.html", cfg.ServerAddress)
	if err := r.Run(cfg.ServerAddress); err != nil {
		log.Fatalf("failed to run server: %v", err)
	}
}
