package seeds

import (
	"github.com/mremperor-atwork/rpg1/api1/internal/features/srd"
)

// GetConditions returns comprehensive conditions from the RPG documentation
func GetConditions() []srd.Condition {
	return []srd.Condition{
		// Major Physical Negative Conditions
		{
			Name:        "Bleeding Out",
			Category:    "Physical",
			Severity:    "Major",
			Type:        "Negative",
			Description: "Character is losing blood rapidly and will die without immediate medical attention.",
			Effects:     "Take damage each round, cannot heal naturally",
		},
		{
			Name:        "Destroyed Weapon/Shield",
			Category:    "Physical",
			Severity:    "Major",
			Type:        "Negative",
			Description: "Your weapon or shield has been completely destroyed and is unusable.",
			Effects:     "Cannot use the destroyed item, must find replacement",
		},
		{
			Name:        "Destroyed Armor",
			Category:    "Physical",
			Severity:    "Major",
			Type:        "Negative",
			Description: "Your armor has been completely destroyed and provides no protection.",
			Effects:     "No armor bonus, must repair or replace",
		},
		{
			Name:        "Disabled Arm",
			Category:    "Physical",
			Severity:    "Major",
			Type:        "Negative",
			Description: "One of your arms is disabled and cannot be used effectively.",
			Effects:     "Cannot use two-handed weapons, penalties to actions requiring that arm",
		},
		{
			Name:        "Disabled Leg",
			Category:    "Physical",
			Severity:    "Major",
			Type:        "Negative",
			Description: "One of your legs is disabled and you cannot move normally.",
			Effects:     "Reduced movement, cannot run, penalties to athletics",
		},
		{
			Name:        "Plagued",
			Category:    "Physical",
			Severity:    "Major",
			Type:        "Negative",
			Description: "You are suffering from a serious disease or curse.",
			Effects:     "Ongoing damage, reduced effectiveness, may spread to others",
		},
		{
			Name:        "Stunned",
			Category:    "Physical",
			Severity:    "Major",
			Type:        "Negative",
			Description: "You are temporarily stunned and cannot take actions.",
			Effects:     "Cannot take actions, vulnerable to attacks",
		},

		// Major Physical Positive Conditions
		{
			Name:        "Blessed",
			Category:    "Physical",
			Severity:    "Major",
			Type:        "Positive",
			Description: "You are under divine protection and receive supernatural aid.",
			Effects:     "Bonus to all rolls, protection from harm",
		},
		{
			Name:        "Protected",
			Category:    "Physical",
			Severity:    "Major",
			Type:        "Positive",
			Description: "You are under magical or divine protection.",
			Effects:     "Damage reduction, resistance to certain effects",
		},
		{
			Name:        "Regenerating",
			Category:    "Physical",
			Severity:    "Major",
			Type:        "Positive",
			Description: "Your wounds are healing rapidly through magical or natural means.",
			Effects:     "Automatic healing each round, faster recovery",
		},
		{
			Name:        "Valorous",
			Category:    "Physical",
			Severity:    "Major",
			Type:        "Positive",
			Description: "You are filled with courage and determination.",
			Effects:     "Bonus to combat rolls, resistance to fear",
		},

		// Major Mental Negative Conditions
		{
			Name:        "Dominated",
			Category:    "Mental",
			Severity:    "Major",
			Type:        "Negative",
			Description: "Your mind is under the control of another being.",
			Effects:     "Cannot act independently, controlled by dominator",
		},
		{
			Name:        "Insane",
			Category:    "Mental",
			Severity:    "Major",
			Type:        "Negative",
			Description: "You have lost touch with reality and cannot function normally.",
			Effects:     "Random actions, cannot make rational decisions",
		},
		{
			Name:        "Insensate",
			Category:    "Mental",
			Severity:    "Major",
			Type:        "Negative",
			Description: "You are unconscious or in a deep trance.",
			Effects:     "Cannot take actions, unaware of surroundings",
		},
		{
			Name:        "Raging",
			Category:    "Mental",
			Severity:    "Major",
			Type:        "Negative",
			Description: "You are in a berserk rage and cannot control your actions.",
			Effects:     "Must attack nearest target, cannot use complex tactics",
		},
		{
			Name:        "Panicked",
			Category:    "Mental",
			Severity:    "Major",
			Type:        "Negative",
			Description: "You are overwhelmed by fear and cannot think clearly.",
			Effects:     "Must flee from source of fear, penalties to all rolls",
		},

		// Major Mental Positive Conditions
		{
			Name:        "Genius",
			Category:    "Mental",
			Severity:    "Major",
			Type:        "Positive",
			Description: "Your mental faculties are enhanced beyond normal limits.",
			Effects:     "Bonus to mental rolls, enhanced problem-solving",
		},
		{
			Name:        "Divinely Inspired",
			Category:    "Mental",
			Severity:    "Major",
			Type:        "Positive",
			Description: "You are receiving guidance from a divine source.",
			Effects:     "Bonus to relevant rolls, enhanced intuition",
		},
		{
			Name:        "Planned for This",
			Category:    "Mental",
			Severity:    "Major",
			Type:        "Positive",
			Description: "You have prepared extensively for this situation.",
			Effects:     "Bonus to relevant rolls, advantage in current circumstances",
		},

		// Major Social Negative Conditions
		{
			Name:        "Hated",
			Category:    "Social",
			Severity:    "Major",
			Type:        "Negative",
			Description: "You are universally despised by a group or community.",
			Effects:     "Hostile reactions, cannot gain social benefits",
		},
		{
			Name:        "Laughing Stock",
			Category:    "Social",
			Severity:    "Major",
			Type:        "Negative",
			Description: "You are the subject of ridicule and mockery.",
			Effects:     "Penalties to social rolls, cannot command respect",
		},
		{
			Name:        "Made a Fool",
			Category:    "Social",
			Severity:    "Major",
			Type:        "Negative",
			Description: "You have been publicly humiliated and your reputation is damaged.",
			Effects:     "Reduced social standing, penalties to influence",
		},
		{
			Name:        "Worst Dressed",
			Category:    "Social",
			Severity:    "Major",
			Type:        "Negative",
			Description: "Your appearance is so poor it affects all social interactions.",
			Effects:     "Penalties to social rolls, negative first impressions",
		},

		// Major Social Positive Conditions
		{
			Name:        "Beloved",
			Category:    "Social",
			Severity:    "Major",
			Type:        "Positive",
			Description: "You are universally loved and respected by a community.",
			Effects:     "Bonus to social rolls, automatic positive reactions",
		},
		{
			Name:        "Best Dressed",
			Category:    "Social",
			Severity:    "Major",
			Type:        "Positive",
			Description: "Your appearance is impeccable and commands attention.",
			Effects:     "Bonus to social rolls, positive first impressions",
		},
		{
			Name:        "Center of Attention",
			Category:    "Social",
			Severity:    "Major",
			Type:        "Positive",
			Description: "All eyes are on you and you command the room.",
			Effects:     "Bonus to performance and influence rolls",
		},
		{
			Name:        "Feared",
			Category:    "Social",
			Severity:    "Major",
			Type:        "Positive",
			Description: "Your reputation inspires fear and respect.",
			Effects:     "Intimidation bonuses, others hesitate to oppose you",
		},
		{
			Name:        "Gossip Confidant",
			Category:    "Social",
			Severity:    "Major",
			Type:        "Positive",
			Description: "You are trusted with secrets and information flows to you.",
			Effects:     "Bonus to gathering information, access to secrets",
		},
		{
			Name:        "Supreme Authority",
			Category:    "Social",
			Severity:    "Major",
			Type:        "Positive",
			Description: "You have absolute authority in your domain.",
			Effects:     "Commands are obeyed, automatic respect",
		},

		// Minor Physical Negative Conditions
		{
			Name:        "Arm Wrack",
			Category:    "Physical",
			Severity:    "Minor",
			Type:        "Negative",
			Description: "Your arm is injured and painful to use.",
			Effects:     "Penalty to actions requiring that arm",
		},
		{
			Name:        "Closed In",
			Category:    "Physical",
			Severity:    "Minor",
			Type:        "Negative",
			Description: "You are in a confined space that limits your movement.",
			Effects:     "Reduced movement, penalties to certain actions",
		},
		{
			Name:        "Damaged Weapon/Shield",
			Category:    "Physical",
			Severity:    "Minor",
			Type:        "Negative",
			Description: "Your weapon or shield is damaged and less effective.",
			Effects:     "Reduced effectiveness, may break with use",
		},
		{
			Name:        "Damaged Armor",
			Category:    "Physical",
			Severity:    "Minor",
			Type:        "Negative",
			Description: "Your armor is damaged and provides less protection.",
			Effects:     "Reduced armor value, may need repair",
		},
		{
			Name:        "Gaping Wounds",
			Category:    "Physical",
			Severity:    "Minor",
			Type:        "Negative",
			Description: "You have serious open wounds that are bleeding.",
			Effects:     "Ongoing damage, penalties to physical actions",
		},
		{
			Name:        "Impaled",
			Category:    "Physical",
			Severity:    "Minor",
			Type:        "Negative",
			Description: "You have been impaled by a weapon or object.",
			Effects:     "Ongoing damage, movement penalties",
		},
		{
			Name:        "Leg Wrack",
			Category:    "Physical",
			Severity:    "Minor",
			Type:        "Negative",
			Description: "Your leg is injured and painful to use.",
			Effects:     "Movement penalties, reduced athletics",
		},
		{
			Name:        "Off Balance",
			Category:    "Physical",
			Severity:    "Minor",
			Type:        "Negative",
			Description: "You are unsteady and off-balance.",
			Effects:     "Penalties to combat and movement rolls",
		},
		{
			Name:        "Prone",
			Category:    "Physical",
			Severity:    "Minor",
			Type:        "Negative",
			Description: "You are lying on the ground.",
			Effects:     "Penalties to combat, must spend action to stand",
		},
		{
			Name:        "Shocked",
			Category:    "Physical",
			Severity:    "Minor",
			Type:        "Negative",
			Description: "You are in shock from injury or trauma.",
			Effects:     "Penalties to all rolls, reduced effectiveness",
		},
		{
			Name:        "Sick",
			Category:    "Physical",
			Severity:    "Minor",
			Type:        "Negative",
			Description: "You are suffering from illness or disease.",
			Effects:     "Penalties to physical rolls, reduced stamina",
		},

		// Minor Physical Positive Conditions
		{
			Name:        "Adrenaline Boost",
			Category:    "Physical",
			Severity:    "Minor",
			Type:        "Positive",
			Description: "Your body is flooded with adrenaline.",
			Effects:     "Bonus to physical rolls, temporary energy",
		},
		{
			Name:        "Fast",
			Category:    "Physical",
			Severity:    "Minor",
			Type:        "Positive",
			Description: "You are moving with enhanced speed.",
			Effects:     "Bonus to movement and athletics",
		},
		{
			Name:        "Resolute Defense",
			Category:    "Physical",
			Severity:    "Minor",
			Type:        "Positive",
			Description: "You are in a defensive stance and ready for anything.",
			Effects:     "Bonus to defense rolls, improved armor",
		},
		{
			Name:        "Supported",
			Category:    "Physical",
			Severity:    "Minor",
			Type:        "Positive",
			Description: "You have allies supporting and aiding you.",
			Effects:     "Bonus to rolls, assistance in actions",
		},
		{
			Name:        "Medicated",
			Category:    "Physical",
			Severity:    "Minor",
			Type:        "Positive",
			Description: "You are under the effects of beneficial medication.",
			Effects:     "Healing bonuses, pain reduction",
		},

		// Minor Mental Negative Conditions
		{
			Name:        "Addicted",
			Category:    "Mental",
			Severity:    "Minor",
			Type:        "Negative",
			Description: "You are addicted to a substance or behavior.",
			Effects:     "Withdrawal penalties, compulsive behavior",
		},
		{
			Name:        "Angry",
			Category:    "Mental",
			Severity:    "Minor",
			Type:        "Negative",
			Description: "You are filled with anger and rage.",
			Effects:     "Penalties to social rolls, combat bonuses",
		},
		{
			Name:        "Confused",
			Category:    "Mental",
			Severity:    "Minor",
			Type:        "Negative",
			Description: "You are confused and cannot think clearly.",
			Effects:     "Penalties to mental rolls, poor decision making",
		},
		{
			Name:        "Distracted",
			Category:    "Mental",
			Severity:    "Minor",
			Type:        "Negative",
			Description: "Your attention is divided and you cannot focus.",
			Effects:     "Penalties to perception and concentration",
		},
		{
			Name:        "Frightened",
			Category:    "Mental",
			Severity:    "Minor",
			Type:        "Negative",
			Description: "Something frightens you, your heart beats faster and your hands are shaking. You want nothing more than to get away from the source of your fear.",
			Effects:     "Penalties to all rolls, desire to flee",
		},
		{
			Name:        "Hopeless",
			Category:    "Mental",
			Severity:    "Minor",
			Type:        "Negative",
			Description: "You have lost hope and see no way forward.",
			Effects:     "Penalties to all rolls, reduced motivation",
		},
		{
			Name:        "Megalomaniacal",
			Category:    "Mental",
			Severity:    "Minor",
			Type:        "Negative",
			Description: "You have delusions of grandeur and power.",
			Effects:     "Poor judgment, overconfidence",
		},
		{
			Name:        "Psychotic",
			Category:    "Mental",
			Severity:    "Minor",
			Type:        "Negative",
			Description: "You are experiencing psychotic symptoms.",
			Effects:     "Unpredictable behavior, poor reality testing",
		},

		// Minor Mental Positive Conditions
		{
			Name:        "Attentive",
			Category:    "Mental",
			Severity:    "Minor",
			Type:        "Positive",
			Description: "You are highly focused and attentive to your surroundings.",
			Effects:     "Bonus to perception and awareness",
		},
		{
			Name:        "Brave",
			Category:    "Mental",
			Severity:    "Minor",
			Type:        "Positive",
			Description: "You are filled with courage and determination.",
			Effects:     "Resistance to fear, bonus to combat",
		},
		{
			Name:        "Focused",
			Category:    "Mental",
			Severity:    "Minor",
			Type:        "Positive",
			Description: "Your mind is clear and focused on the task at hand.",
			Effects:     "Bonus to concentration and mental rolls",
		},
		{
			Name:        "Inspired",
			Category:    "Mental",
			Severity:    "Minor",
			Type:        "Positive",
			Description: "You are inspired and creative.",
			Effects:     "Bonus to creative and problem-solving rolls",
		},

		// Minor Social Negative Conditions
		{
			Name:        "Charmed",
			Category:    "Social",
			Severity:    "Minor",
			Type:        "Negative",
			Description: "You are under the influence of a charm or enchantment.",
			Effects:     "Cannot act against the charmer's interests",
		},
		{
			Name:        "Embarrassed",
			Category:    "Social",
			Severity:    "Minor",
			Type:        "Negative",
			Description: "You are embarrassed and self-conscious.",
			Effects:     "Penalties to social rolls, reduced confidence",
		},
		{
			Name:        "Guilty",
			Category:    "Social",
			Severity:    "Minor",
			Type:        "Negative",
			Description: "You are feeling guilty about something you've done.",
			Effects:     "Penalties to social rolls, reduced self-esteem",
		},
		{
			Name:        "Insecure",
			Category:    "Social",
			Severity:    "Minor",
			Type:        "Negative",
			Description: "You are feeling insecure and uncertain.",
			Effects:     "Penalties to social rolls, reduced confidence",
		},

		// Minor Social Positive Conditions
		{
			Name:        "In Your Element",
			Category:    "Social",
			Severity:    "Minor",
			Type:        "Positive",
			Description: "You are in a situation where you feel comfortable and confident.",
			Effects:     "Bonus to relevant social rolls",
		},
		{
			Name:        "Proven",
			Category:    "Social",
			Severity:    "Minor",
			Type:        "Positive",
			Description: "You have proven yourself and gained respect.",
			Effects:     "Bonus to social rolls, increased standing",
		},
		{
			Name:        "Wall Fly",
			Category:    "Social",
			Severity:    "Minor",
			Type:        "Positive",
			Description: "You are skilled at blending into social situations.",
			Effects:     "Bonus to stealth and social observation",
		},
	}
}
