package seeds

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// Helper functions to create pointers
func intPtr(i int) *int {
	return &i
}

func stringPtr(s string) *string {
	return &s
}

type EquipmentItem struct {
	ID              uuid.UUID `gorm:"type:uuid;primary_key;default:gen_random_uuid()"`
	Name            string    `gorm:"not null"`
	Category        string    `gorm:"not null"` // Weapon, Armor, Tool, Personal, Vehicle, Ammunition
	Subcategory     string    `gorm:"not null"` // Melee, Ranged, Body, Head, etc.
	Era             string    `gorm:"not null"` // Medieval, Industrial, Cyber
	Cost            int       `gorm:"not null"`
	Rarity          int       `gorm:"not null"` // 0=Civilian, 1-3=Restricted, 4-5=Military
	Size            int       `gorm:"not null"`
	Weight          float64   `gorm:"not null"`
	Damage          *int      `gorm:"default:null"` // Damage value (can be negative for penalties, null for armor)
	DamageType      *string   `gorm:"default:null"` // S=Stun, L=Lethal, A=Aggravated, null for armor
	ArmorRating     int       `gorm:"default:0"`
	BallisticRating int       `gorm:"default:0"`
	ArmorPiercing   int       `gorm:"default:0"`  // For ammunition
	Type            string    `gorm:"default:''"` // Blade, Club, Soft, Hard, etc.
	Special         string    `gorm:"default:''"` // Special properties
	Parry           bool      `gorm:"default:false"`
	StandardMods    string    `gorm:"default:''"`
	Description     string    `gorm:"default:''"`
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (EquipmentItem) TableName() string {
	return "equipment_items"
}

func SeedEquipmentItems(db *gorm.DB) error {
	items := GetEquipmentItems()

	// Check if equipment items already exist
	var count int64
	db.Model(&EquipmentItem{}).Count(&count)
	if count > 0 {
		return nil // Already seeded
	}

	// Create equipment items
	for _, item := range items {
		if err := db.Create(&item).Error; err != nil {
			return err
		}
	}

	return nil
}

// GetEquipmentItems returns all equipment items for seeding
func GetEquipmentItems() []EquipmentItem {
	return []EquipmentItem{
		// Medieval Melee Weapons
		{
			ID:          uuid.New(),
			Name:        "Punching Dagger",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        200,
			Rarity:      0,
			Size:        0,
			Weight:      0.5,
			Damage:      intPtr(0),
			DamageType:  stringPtr("L"),
			Type:        "Unarmed",
			Special:     "Brawling",
			Parry:       false,
			Description: "A small dagger designed for punching attacks, easily concealed.",
		},
		{
			ID:          uuid.New(),
			Name:        "Sap",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        250,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Damage:      intPtr(0),
			DamageType:  stringPtr("S"),
			Type:        "Club",
			Special:     "Headcracker",
			Parry:       false,
			Description: "A weighted leather pouch used for non-lethal takedowns.",
		},
		{
			ID:          uuid.New(),
			Name:        "Bolas",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        50,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Damage:      intPtr(0),
			DamageType:  stringPtr("S"),
			Type:        "Throwing",
			Special:     "Throwing, Tripping, Trapping, Risky",
			Parry:       false,
			Description: "Rope with weighted ends used to entangle and trip targets.",
		},
		{
			ID:          uuid.New(),
			Name:        "Dagger/Tanto",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        200,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Damage:      intPtr(1),
			DamageType:  stringPtr("L"),
			Type:        "Blade",
			Special:     "Armor piercing: 1",
			Parry:       false,
			Description: "A short, sharp blade perfect for close combat and throwing.",
		},
		{
			ID:          uuid.New(),
			Name:        "Parrying Dagger/Sai",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        500,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Damage:      intPtr(1),
			DamageType:  stringPtr("L"),
			Type:        "Blade",
			Special:     "Shield bonus 1, Parrying 1",
			Parry:       true,
			Description: "A specialized dagger with side guards designed for parrying attacks.",
		},
		{
			ID:          uuid.New(),
			Name:        "War Fan",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        700,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Damage:      intPtr(0),
			DamageType:  stringPtr("L"),
			Type:        "Blade",
			Special:     "Concealed",
			Parry:       true,
			Description: "An elegant but deadly fan with sharpened edges.",
		},
		{
			ID:          uuid.New(),
			Name:        "Tiger Claws",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        700,
			Rarity:      2,
			Size:        1,
			Weight:      1.0,
			Damage:      intPtr(1),
			DamageType:  stringPtr("L"),
			Type:        "Unarmed",
			Special:     "Brawling",
			Parry:       true,
			Description: "Metal claws worn on the hands for devastating unarmed attacks.",
		},
		{
			ID:          uuid.New(),
			Name:        "Club/Baton",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        0,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      intPtr(1),
			DamageType:  stringPtr("S"),
			Type:        "Club",
			Special:     "Blunt",
			Parry:       true,
			Description: "A simple wooden club or metal baton, easily improvised.",
		},
		{
			ID:          uuid.New(),
			Name:        "Lasso",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        50,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      intPtr(-1),
			DamageType:  stringPtr("S"),
			Type:        "Exotic",
			Special:     "Restraining, trapping, increased reach 2",
			Parry:       false,
			Description: "A rope loop used to catch and restrain targets from a distance.",
		},
		{
			ID:          uuid.New(),
			Name:        "Whip",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        100,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      intPtr(-1),
			DamageType:  stringPtr("S"),
			Type:        "Exotic/Wire",
			Special:     "Restraining, Disarming, Increased reach 1",
			Parry:       false,
			Description: "A flexible weapon that can disarm and restrain opponents.",
		},
		{
			ID:          uuid.New(),
			Name:        "Chain",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        200,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      intPtr(1),
			DamageType:  stringPtr("L"),
			Type:        "Exotic/Wire",
			Special:     "Restraining, Increased reach 1",
			Parry:       false,
			Description: "A heavy chain that can be used as a weapon or restraint.",
		},
		{
			ID:          uuid.New(),
			Name:        "Nunchaku",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        300,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      intPtr(1),
			DamageType:  stringPtr("S"),
			Type:        "Club",
			Special:     "Disarming, Risky",
			Parry:       true,
			Description: "Two wooden sticks connected by a chain, requiring skill to use effectively.",
		},
		{
			ID:          uuid.New(),
			Name:        "Hatchet/Machete",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        300,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      intPtr(2),
			DamageType:  stringPtr("L"),
			Type:        "Blade/Axe",
			Special:     "Gaping wounds",
			Parry:       true,
			Description: "A versatile cutting tool that doubles as an effective weapon.",
		},
		{
			ID:          uuid.New(),
			Name:        "Throwing Axe",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        400,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      intPtr(2),
			DamageType:  stringPtr("L"),
			Type:        "Throwing/Axe",
			Special:     "Throwing, Gaping wounds",
			Parry:       true,
			Description: "A balanced axe designed for throwing at targets.",
		},
		{
			ID:          uuid.New(),
			Name:        "Sickle/Kama",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        400,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      intPtr(2),
			DamageType:  stringPtr("L"),
			Type:        "Axe",
			Special:     "Disarming",
			Parry:       true,
			Description: "A curved blade originally used for harvesting, effective in combat.",
		},
		{
			ID:          uuid.New(),
			Name:        "Kusari-Gama",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        500,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      intPtr(2),
			DamageType:  stringPtr("L"),
			Type:        "Exotic",
			Special:     "Risky, Restraining, Increased reach 1",
			Parry:       true,
			Description: "A sickle attached to a chain, combining cutting and restraining capabilities.",
		},
		{
			ID:          uuid.New(),
			Name:        "Short Sword/Gladius/Wakizashi",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        800,
			Rarity:      2,
			Size:        2,
			Weight:      2.0,
			Damage:      intPtr(2),
			DamageType:  stringPtr("L"),
			Type:        "Blade",
			Special:     "Quick 1",
			Parry:       true,
			Description: "A versatile short sword used by warriors across many cultures.",
		},
		{
			ID:          uuid.New(),
			Name:        "Rapier",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        1000,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      intPtr(2),
			DamageType:  stringPtr("L"),
			Type:        "Blade",
			Special:     "Increased reach 1",
			Parry:       true,
			Description: "An elegant thrusting sword with a long, narrow blade.",
		},
		{
			ID:          uuid.New(),
			Name:        "Flanged Mace/Warhammer",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        1200,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      intPtr(2),
			DamageType:  stringPtr("L"),
			Type:        "Club",
			Special:     "Armor piercing 2",
			Parry:       true,
			Description: "A heavy weapon designed to crush armor and bone.",
		},
		{
			ID:          uuid.New(),
			Name:        "Javelin",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        1500,
			Rarity:      0,
			Size:        3,
			Weight:      3.0,
			Damage:      intPtr(2),
			DamageType:  stringPtr("L"),
			Type:        "Throwing/Polearm",
			Special:     "Throwing, armor piercing 1",
			Parry:       true,
			Description: "A spear designed for throwing, effective against armored targets.",
		},
		{
			ID:          uuid.New(),
			Name:        "Flail",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        300,
			Rarity:      0,
			Size:        3,
			Weight:      3.0,
			Damage:      nil,
			DamageType:  nil,
			Type:        "Club",
			Special:     "Armor Piercing 1, Inaccurate -1",
			Parry:       true,
			Description: "A chain weapon that can strike around shields and armor.",
		},
		{
			ID:          uuid.New(),
			Name:        "Battle Axe",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        500,
			Rarity:      0,
			Size:        3,
			Weight:      3.0,
			Damage:      nil,
			DamageType:  nil,
			Type:        "Axe",
			Special:     "Disarming, Gaping wounds",
			Parry:       true,
			Description: "A heavy axe designed for combat, capable of devastating wounds.",
		},
		{
			ID:          uuid.New(),
			Name:        "Arming Sword",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        800,
			Rarity:      0,
			Size:        3,
			Weight:      3.0,
			Damage:      nil,
			DamageType:  nil,
			Type:        "Blade",
			Special:     "Parrying 1",
			Parry:       true,
			Description: "A versatile one-handed sword with a straight, double-edged blade.",
		},
		{
			ID:          uuid.New(),
			Name:        "Katana",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        2000,
			Rarity:      0,
			Size:        3,
			Weight:      3.0,
			Damage:      nil,
			DamageType:  nil,
			Type:        "Blade",
			Special:     "Quick 1",
			Parry:       true,
			Description: "A curved Japanese sword known for its sharpness and cutting power.",
		},
		{
			ID:          uuid.New(),
			Name:        "Heavy Club",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        2500,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      nil,
			DamageType:  nil,
			Type:        "Club",
			Special:     "Blunt",
			Parry:       true,
			Description: "A massive club that can deliver both stunning and lethal damage.",
		},
		{
			ID:          uuid.New(),
			Name:        "Catchpole",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        150,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      nil,
			DamageType:  nil,
			Type:        "Polearm",
			Special:     "Trapping, Light",
			Parry:       true,
			Description: "A pole with a collar designed to capture and restrain targets.",
		},
		{
			ID:          uuid.New(),
			Name:        "Staff",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        300,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      nil,
			DamageType:  nil,
			Type:        "Club",
			Special:     "Parrying 1",
			Parry:       true,
			Description: "A simple wooden staff, effective for both attack and defense.",
		},
		{
			ID:          uuid.New(),
			Name:        "Net",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        300,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      nil,
			DamageType:  nil,
			Type:        "Exotic/Wire",
			Special:     "Throwing, Trapping, Light",
			Parry:       false,
			Description: "A weighted net used to entangle and capture targets.",
		},
		{
			ID:          uuid.New(),
			Name:        "Pitchfork",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        400,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      nil,
			DamageType:  nil,
			Type:        "Polearm",
			Special:     "Parrying 1, Inaccurate -1",
			Parry:       true,
			Description: "A farming tool that can be used as an effective weapon.",
		},
		{
			ID:          uuid.New(),
			Name:        "Trident",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        550,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      nil,
			DamageType:  nil,
			Type:        "Polearm",
			Special:     "Throwing",
			Parry:       true,
			Description: "A three-pronged spear effective for both thrusting and throwing.",
		},
		{
			ID:          uuid.New(),
			Name:        "Greataxe",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        700,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      nil,
			DamageType:  nil,
			Type:        "Axe",
			Special:     "Gaping wounds",
			Parry:       true,
			Description: "A massive two-handed axe capable of devastating wounds.",
		},
		{
			ID:          uuid.New(),
			Name:        "Bastard Sword",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        2000,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      nil,
			DamageType:  nil,
			Type:        "Blade",
			Special:     "1 or 2 handed, Parrying 1, can be quickdrawn by size 5",
			Parry:       true,
			Description: "A versatile sword that can be used one or two-handed.",
		},
		{
			ID:          uuid.New(),
			Name:        "Heavy Mace",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        3000,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      nil,
			DamageType:  nil,
			Type:        "Club",
			Special:     "Armor piercing 2",
			Parry:       true,
			Description: "A heavy mace designed to crush through armor.",
		},
		{
			ID:          uuid.New(),
			Name:        "Greatsword",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        3000,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      nil,
			DamageType:  nil,
			Type:        "Blade",
			Special:     "Parrying 1",
			Parry:       true,
			Description: "A massive two-handed sword requiring great strength to wield.",
		},
		{
			ID:          uuid.New(),
			Name:        "Nodachi",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        4000,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      nil,
			DamageType:  nil,
			Type:        "Blade",
			Special:     "Area attack +1 target",
			Parry:       true,
			Description: "An extremely long Japanese sword capable of striking multiple targets.",
		},
		{
			ID:          uuid.New(),
			Name:        "Spear",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        4000,
			Rarity:      0,
			Size:        5,
			Weight:      5.0,
			Damage:      nil,
			DamageType:  nil,
			Type:        "Polearm",
			Special:     "1 or 2 Handed, Light",
			Parry:       true,
			Description: "A simple but effective polearm, the weapon of choice for many armies.",
		},
		{
			ID:          uuid.New(),
			Name:        "Cavalry Lance",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        800,
			Rarity:      0,
			Size:        5,
			Weight:      5.0,
			Damage:      nil,
			DamageType:  nil,
			Type:        "Polearm",
			Special:     "Couched",
			Parry:       false,
			Description: "A long lance designed for mounted combat.",
		},
		{
			ID:          uuid.New(),
			Name:        "Halberd/Naginata",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        1200,
			Rarity:      0,
			Size:        5,
			Weight:      5.0,
			Damage:      nil,
			DamageType:  nil,
			Type:        "Polearm",
			Special:     "Tripping, Armor piercing 1",
			Parry:       true,
			Description: "A polearm combining axe, spear, and hook capabilities.",
		},
		{
			ID:          uuid.New(),
			Name:        "Two-Handed Warhammer",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        3500,
			Rarity:      0,
			Size:        5,
			Weight:      5.0,
			Damage:      nil,
			DamageType:  nil,
			Type:        "Club",
			Special:     "Armor piercing 2",
			Parry:       true,
			Description: "A massive hammer requiring two hands to wield effectively.",
		},
		{
			ID:          uuid.New(),
			Name:        "Pike",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        4000,
			Rarity:      0,
			Size:        6,
			Weight:      6.0,
			Damage:      nil,
			DamageType:  nil,
			Type:        "Polearm",
			Special:     "Charge stopper, Light",
			Parry:       true,
			Description: "An extremely long spear designed to stop cavalry charges.",
		},
		{
			ID:          uuid.New(),
			Name:        "Improvised Weapon",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Universal",
			Cost:        0,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Damage:      nil,
			DamageType:  nil,
			Type:        "Improvised",
			Special:     "Inaccurate -2, Fragile",
			Parry:       true,
			Description: "Any object used as a weapon, from chairs to broken bottles.",
		},
		// Medieval Armor
		{
			ID:              uuid.New(),
			Name:            "Leather Armor",
			Category:        "Armor",
			Subcategory:     "Body",
			Era:             "Medieval",
			Cost:            200,
			Rarity:          0,
			Size:            3,
			Weight:          3.0,
			Damage:          nil,
			DamageType:      nil,
			ArmorRating:     1,
			BallisticRating: 0,
			Type:            "Soft",
			Special:         "Light",
			Parry:           false,
			Description:     "Light leather armor offering minimal protection but good mobility.",
		},
		{
			ID:              uuid.New(),
			Name:            "Studded Leather",
			Category:        "Armor",
			Subcategory:     "Body",
			Era:             "Medieval",
			Cost:            400,
			Rarity:          0,
			Size:            3,
			Weight:          3.0,
			Damage:          nil,
			DamageType:      nil,
			ArmorRating:     2,
			BallisticRating: 0,
			Type:            "Soft",
			Special:         "Light",
			Parry:           false,
			Description:     "Leather armor reinforced with metal studs for better protection.",
		},
		{
			ID:              uuid.New(),
			Name:            "Chain Shirt",
			Category:        "Armor",
			Subcategory:     "Body",
			Era:             "Medieval",
			Cost:            1000,
			Rarity:          0,
			Size:            3,
			Weight:          3.0,
			Damage:          nil,
			ArmorRating:     3,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "Light",
			Parry:           false,
			Description:     "A flexible chain mail shirt covering the torso.",
		},
		{
			ID:              uuid.New(),
			Name:            "Scale Mail",
			Category:        "Armor",
			Subcategory:     "Body",
			Era:             "Medieval",
			Cost:            1500,
			Rarity:          0,
			Size:            4,
			Weight:          4.0,
			Damage:          nil,
			ArmorRating:     4,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "",
			Parry:           false,
			Description:     "Armor made of overlapping metal scales sewn to a backing.",
		},
		{
			ID:              uuid.New(),
			Name:            "Chain Hauberk",
			Category:        "Armor",
			Subcategory:     "Body",
			Era:             "Medieval",
			Cost:            2000,
			Rarity:          0,
			Size:            4,
			Weight:          4.0,
			Damage:          nil,
			ArmorRating:     4,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "",
			Parry:           false,
			Description:     "A full chain mail suit covering the torso and arms.",
		},
		{
			ID:              uuid.New(),
			Name:            "Breastplate",
			Category:        "Armor",
			Subcategory:     "Body",
			Era:             "Medieval",
			Cost:            3000,
			Rarity:          0,
			Size:            4,
			Weight:          4.0,
			Damage:          nil,
			ArmorRating:     5,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "",
			Parry:           false,
			Description:     "A solid metal breastplate protecting the chest and abdomen.",
		},
		{
			ID:              uuid.New(),
			Name:            "Splint Mail",
			Category:        "Armor",
			Subcategory:     "Body",
			Era:             "Medieval",
			Cost:            4000,
			Rarity:          0,
			Size:            5,
			Weight:          5.0,
			Damage:          nil,
			ArmorRating:     6,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "",
			Parry:           false,
			Description:     "Heavy armor made of metal strips attached to a leather backing.",
		},
		{
			ID:              uuid.New(),
			Name:            "Banded Mail",
			Category:        "Armor",
			Subcategory:     "Body",
			Era:             "Medieval",
			Cost:            5000,
			Rarity:          0,
			Size:            5,
			Weight:          5.0,
			Damage:          nil,
			ArmorRating:     7,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "",
			Parry:           false,
			Description:     "Heavy armor made of overlapping metal bands.",
		},
		{
			ID:              uuid.New(),
			Name:            "Half Plate",
			Category:        "Armor",
			Subcategory:     "Body",
			Era:             "Medieval",
			Cost:            6000,
			Rarity:          0,
			Size:            5,
			Weight:          5.0,
			Damage:          nil,
			ArmorRating:     8,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "",
			Parry:           false,
			Description:     "Partial plate armor covering the upper body.",
		},
		{
			ID:              uuid.New(),
			Name:            "Full Plate",
			Category:        "Armor",
			Subcategory:     "Body",
			Era:             "Medieval",
			Cost:            10000,
			Rarity:          0,
			Size:            6,
			Weight:          6.0,
			Damage:          nil,
			ArmorRating:     10,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "",
			Parry:           false,
			Description:     "Complete plate armor offering maximum protection.",
		},
		// Medieval Head Armor
		{
			ID:              uuid.New(),
			Name:            "Leather Cap",
			Category:        "Armor",
			Subcategory:     "Head",
			Era:             "Medieval",
			Cost:            50,
			Rarity:          0,
			Size:            1,
			Weight:          1.0,
			Damage:          nil,
			ArmorRating:     1,
			BallisticRating: 0,
			Type:            "Soft",
			Special:         "Light",
			Parry:           false,
			Description:     "A simple leather cap offering minimal head protection.",
		},
		{
			ID:              uuid.New(),
			Name:            "Chain Coif",
			Category:        "Armor",
			Subcategory:     "Head",
			Era:             "Medieval",
			Cost:            200,
			Rarity:          0,
			Size:            1,
			Weight:          1.0,
			Damage:          nil,
			ArmorRating:     3,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "Light",
			Parry:           false,
			Description:     "A chain mail hood protecting the head and neck.",
		},
		{
			ID:              uuid.New(),
			Name:            "Steel Cap",
			Category:        "Armor",
			Subcategory:     "Head",
			Era:             "Medieval",
			Cost:            500,
			Rarity:          0,
			Size:            1,
			Weight:          1.0,
			Damage:          nil,
			ArmorRating:     4,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "",
			Parry:           false,
			Description:     "A simple steel helmet protecting the top of the head.",
		},
		{
			ID:              uuid.New(),
			Name:            "Open Helm",
			Category:        "Armor",
			Subcategory:     "Head",
			Era:             "Medieval",
			Cost:            1000,
			Rarity:          0,
			Size:            1,
			Weight:          1.0,
			Damage:          nil,
			ArmorRating:     5,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "",
			Parry:           false,
			Description:     "A helmet with an open face for better visibility.",
		},
		{
			ID:              uuid.New(),
			Name:            "Great Helm",
			Category:        "Armor",
			Subcategory:     "Head",
			Era:             "Medieval",
			Cost:            2000,
			Rarity:          0,
			Size:            1,
			Weight:          1.0,
			Damage:          nil,
			ArmorRating:     6,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "Reduced vision",
			Parry:           false,
			Description:     "A fully enclosed helmet offering maximum head protection.",
		},
		// Medieval Arm Armor
		{
			ID:              uuid.New(),
			Name:            "Leather Bracers",
			Category:        "Armor",
			Subcategory:     "Arms",
			Era:             "Medieval",
			Cost:            100,
			Rarity:          0,
			Size:            1,
			Weight:          1.0,
			Damage:          nil,
			ArmorRating:     1,
			BallisticRating: 0,
			Type:            "Soft",
			Special:         "Light",
			Parry:           false,
			Description:     "Simple leather protection for the forearms.",
		},
		{
			ID:              uuid.New(),
			Name:            "Chain Sleeves",
			Category:        "Armor",
			Subcategory:     "Arms",
			Era:             "Medieval",
			Cost:            300,
			Rarity:          0,
			Size:            1,
			Weight:          1.0,
			Damage:          nil,
			ArmorRating:     3,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "Light",
			Parry:           false,
			Description:     "Chain mail sleeves protecting the arms.",
		},
		{
			ID:              uuid.New(),
			Name:            "Plate Gauntlets",
			Category:        "Armor",
			Subcategory:     "Arms",
			Era:             "Medieval",
			Cost:            500,
			Rarity:          0,
			Size:            1,
			Weight:          1.0,
			Damage:          nil,
			ArmorRating:     4,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "",
			Parry:           false,
			Description:     "Metal gauntlets protecting the hands and wrists.",
		},
		// Medieval Leg Armor
		{
			ID:              uuid.New(),
			Name:            "Leather Greaves",
			Category:        "Armor",
			Subcategory:     "Legs",
			Era:             "Medieval",
			Cost:            150,
			Rarity:          0,
			Size:            1,
			Weight:          1.0,
			Damage:          nil,
			ArmorRating:     1,
			BallisticRating: 0,
			Type:            "Soft",
			Special:         "Light",
			Parry:           false,
			Description:     "Leather protection for the lower legs.",
		},
		{
			ID:              uuid.New(),
			Name:            "Chain Chausses",
			Category:        "Armor",
			Subcategory:     "Legs",
			Era:             "Medieval",
			Cost:            400,
			Rarity:          0,
			Size:            1,
			Weight:          1.0,
			Damage:          nil,
			ArmorRating:     3,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "Light",
			Parry:           false,
			Description:     "Chain mail leggings protecting the legs.",
		},
		{
			ID:              uuid.New(),
			Name:            "Plate Greaves",
			Category:        "Armor",
			Subcategory:     "Legs",
			Era:             "Medieval",
			Cost:            600,
			Rarity:          0,
			Size:            1,
			Weight:          1.0,
			Damage:          nil,
			ArmorRating:     4,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "",
			Parry:           false,
			Description:     "Metal greaves protecting the lower legs.",
		},
		// Industrial Era Armor
		{
			ID:              uuid.New(),
			Name:            "Kevlar Vest",
			Category:        "Armor",
			Subcategory:     "Body",
			Era:             "Industrial",
			Cost:            5000,
			Rarity:          1,
			Size:            2,
			Weight:          2.0,
			Damage:          nil,
			ArmorRating:     2,
			BallisticRating: 4,
			Type:            "Soft",
			Special:         "Light",
			Parry:           false,
			Description:     "Modern body armor made of Kevlar fibers.",
		},
		{
			ID:              uuid.New(),
			Name:            "Tactical Vest",
			Category:        "Armor",
			Subcategory:     "Body",
			Era:             "Industrial",
			Cost:            8000,
			Rarity:          2,
			Size:            3,
			Weight:          3.0,
			Damage:          nil,
			ArmorRating:     3,
			BallisticRating: 6,
			Type:            "Hard",
			Special:         "",
			Parry:           false,
			Description:     "Military-grade body armor with ballistic plates.",
		},
		{
			ID:              uuid.New(),
			Name:            "Combat Helmet",
			Category:        "Armor",
			Subcategory:     "Head",
			Era:             "Industrial",
			Cost:            2000,
			Rarity:          1,
			Size:            1,
			Weight:          1.0,
			Damage:          nil,
			DamageType:      nil,
			ArmorRating:     2,
			BallisticRating: 3,
			Type:            "Hard",
			Special:         "",
			Parry:           false,
			Description:     "Modern military helmet with ballistic protection.",
		},
		// Cyber Era Armor
		{
			ID:              uuid.New(),
			Name:            "Smart Armor",
			Category:        "Armor",
			Subcategory:     "Body",
			Era:             "Cyber",
			Cost:            15000,
			Rarity:          3,
			Size:            2,
			Weight:          2.0,
			Damage:          nil,
			DamageType:      nil,
			ArmorRating:     4,
			BallisticRating: 8,
			Type:            "Hard",
			Special:         "Light, Smart",
			Parry:           false,
			Description:     "Advanced armor with integrated smart systems.",
		},
		{
			ID:              uuid.New(),
			Name:            "Combat Suit",
			Category:        "Armor",
			Subcategory:     "Body",
			Era:             "Cyber",
			Cost:            25000,
			Rarity:          4,
			Size:            3,
			Weight:          3.0,
			Damage:          nil,
			DamageType:      nil,
			ArmorRating:     6,
			BallisticRating: 10,
			Type:            "Hard",
			Special:         "Smart, Stealth",
			Parry:           false,
			Description:     "Full-body combat armor with advanced protection systems.",
		},
		{
			ID:              uuid.New(),
			Name:            "Neural Helmet",
			Category:        "Armor",
			Subcategory:     "Head",
			Era:             "Cyber",
			Cost:            8000,
			Rarity:          3,
			Size:            1,
			Weight:          1.0,
			Damage:          nil,
			DamageType:      nil,
			ArmorRating:     3,
			BallisticRating: 5,
			Type:            "Hard",
			Special:         "Smart, Neural Interface",
			Parry:           false,
			Description:     "Advanced helmet with neural interface capabilities.",
		},
		// Cyber Era Armor - Legs
		{
			ID:              uuid.New(),
			Name:            "Armored Leggings",
			Category:        "Armor",
			Subcategory:     "Legs",
			Era:             "Cyber",
			Cost:            800,
			Rarity:          0,
			Size:            3,
			Weight:          3.0,
			ArmorRating:     4,
			BallisticRating: 4,
			Type:            "Soft",
			Special:         "Light",
			Description:     "Flexible armored leggings providing ballistic protection.",
		},
		{
			ID:              uuid.New(),
			Name:            "Leg Pads",
			Category:        "Armor",
			Subcategory:     "Legs",
			Era:             "Cyber",
			Cost:            400,
			Rarity:          0,
			Size:            2,
			Weight:          2.0,
			ArmorRating:     2,
			BallisticRating: 2,
			Type:            "Soft",
			Special:         "Light",
			Description:     "Lightweight leg protection for urban environments.",
		},

		// Ammunition - Medieval Era
		{
			ID:            uuid.New(),
			Name:          "Arrows (Standard)",
			Category:      "Ammunition",
			Subcategory:   "Arrows",
			Era:           "Medieval",
			Cost:          50,
			Rarity:        0,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(0),
			DamageType:    stringPtr("L"),
			ArmorPiercing: 0,
			Type:          "Standard",
			Special:       "For Bows, Short, Long, Yumi",
			Description:   "Standard arrows for medieval bows.",
		},
		{
			ID:            uuid.New(),
			Name:          "Arrows (Armor Piercing)",
			Category:      "Ammunition",
			Subcategory:   "Arrows",
			Era:           "Medieval",
			Cost:          80,
			Rarity:        3,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(-1),
			DamageType:    stringPtr("L"),
			ArmorPiercing: 2,
			Type:          "Armor Piercing",
			Special:       "For Bows, Short, Long, Yumi",
			Description:   "Armor piercing arrows with hardened tips.",
		},
		{
			ID:            uuid.New(),
			Name:          "Arrows (Broadhead)",
			Category:      "Ammunition",
			Subcategory:   "Arrows",
			Era:           "Medieval",
			Cost:          60,
			Rarity:        0,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(1),
			DamageType:    stringPtr("L"),
			ArmorPiercing: -2,
			Type:          "Broadhead",
			Special:       "Gaping Wounds, For Bows, Short, Long, Yumi",
			Description:   "Broadhead arrows designed to cause bleeding wounds.",
		},
		{
			ID:            uuid.New(),
			Name:          "Arrows (Blunt)",
			Category:      "Ammunition",
			Subcategory:   "Arrows",
			Era:           "Medieval",
			Cost:          30,
			Rarity:        0,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(-2),
			DamageType:    stringPtr("S"),
			ArmorPiercing: -2,
			Type:          "Blunt",
			Special:       "Stun damage, For Bows, Short, Long, Yumi",
			Description:   "Blunt arrows designed for non-lethal takedowns.",
		},
		{
			ID:            uuid.New(),
			Name:          "Crossbow Bolts (Standard)",
			Category:      "Ammunition",
			Subcategory:   "Bolts",
			Era:           "Medieval",
			Cost:          80,
			Rarity:        0,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(0),
			DamageType:    stringPtr("L"),
			ArmorPiercing: 0,
			Type:          "Standard",
			Special:       "For Crossbow: Hand, Light, Heavy",
			Description:   "Standard crossbow bolts.",
		},
		{
			ID:            uuid.New(),
			Name:          "Crossbow Bolts (Broadhead)",
			Category:      "Ammunition",
			Subcategory:   "Bolts",
			Era:           "Medieval",
			Cost:          100,
			Rarity:        0,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(1),
			DamageType:    stringPtr("L"),
			ArmorPiercing: -2,
			Type:          "Broadhead",
			Special:       "Gaping Wounds, For Crossbow: Hand, Light, Heavy",
			Description:   "Broadhead crossbow bolts for maximum damage.",
		},
		{
			ID:            uuid.New(),
			Name:          "Sling (Rock)",
			Category:      "Ammunition",
			Subcategory:   "Sling",
			Era:           "Medieval",
			Cost:          1,
			Rarity:        0,
			Size:          0,
			Weight:        0.05,
			Damage:        intPtr(0),
			DamageType:    stringPtr("L"),
			ArmorPiercing: 0,
			Type:          "Rock",
			Special:       "Easily scavenged, For Sling",
			Description:   "Common rocks for sling ammunition.",
		},
		{
			ID:            uuid.New(),
			Name:          "Sling (Metal ball)",
			Category:      "Ammunition",
			Subcategory:   "Sling",
			Era:           "Medieval",
			Cost:          70,
			Rarity:        0,
			Size:          0,
			Weight:        0.1,
			Damage:        intPtr(1),
			DamageType:    stringPtr("L"),
			ArmorPiercing: 0,
			Type:          "Metal",
			Special:       "For Sling",
			Description:   "Metal balls for increased sling damage.",
		},
		{
			ID:            uuid.New(),
			Name:          "Sling (Wood ball)",
			Category:      "Ammunition",
			Subcategory:   "Sling",
			Era:           "Medieval",
			Cost:          20,
			Rarity:        0,
			Size:          0,
			Weight:        0.05,
			Damage:        intPtr(-1),
			DamageType:    stringPtr("S"),
			ArmorPiercing: -1,
			Type:          "Wood",
			Special:       "Stun Damage, For Sling",
			Description:   "Wooden balls for non-lethal sling attacks.",
		},

		// Ammunition - Industrial Era
		{
			ID:            uuid.New(),
			Name:          "Ball & Powder (Standard)",
			Category:      "Ammunition",
			Subcategory:   "Firearm",
			Era:           "Industrial",
			Cost:          100,
			Rarity:        0,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(0),
			DamageType:    stringPtr("L"),
			ArmorPiercing: 0,
			Type:          "Standard",
			Special:       "For Pistol, Musket",
			Description:   "Standard ball and powder for early firearms.",
		},
		{
			ID:            uuid.New(),
			Name:          "Ball & Powder (Minié)",
			Category:      "Ammunition",
			Subcategory:   "Firearm",
			Era:           "Industrial",
			Cost:          120,
			Rarity:        0,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(1),
			DamageType:    stringPtr("L"),
			ArmorPiercing: -2,
			Type:          "Minié",
			Special:       "1 less inaccurate penalty, For Pistol, Musket",
			Description:   "Improved Minié ball ammunition for better accuracy.",
		},
		{
			ID:            uuid.New(),
			Name:          "Shot",
			Category:      "Ammunition",
			Subcategory:   "Firearm",
			Era:           "Industrial",
			Cost:          150,
			Rarity:        0,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(0),
			DamageType:    stringPtr("L"),
			ArmorPiercing: 0,
			Type:          "Shot",
			Special:       "Area: engaged, For Dragon, Blunderbuss",
			Description:   "Shot ammunition for scatter weapons.",
		},

		// Ammunition - Cyber Era
		{
			ID:            uuid.New(),
			Name:          "Full Metal Jacket (Standard)",
			Category:      "Ammunition",
			Subcategory:   "Firearm",
			Era:           "Cyber",
			Cost:          50,
			Rarity:        2,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(0),
			DamageType:    stringPtr("L"),
			ArmorPiercing: 0,
			Type:          "FMJ",
			Special:       "For Pistol, SMG, Assault rifle, Rifle, MG",
			Description:   "Standard full metal jacket ammunition.",
		},
		{
			ID:            uuid.New(),
			Name:          "Armor Piercing",
			Category:      "Ammunition",
			Subcategory:   "Firearm",
			Era:           "Cyber",
			Cost:          100,
			Rarity:        3,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(-1),
			DamageType:    stringPtr("L"),
			ArmorPiercing: 2,
			Type:          "AP",
			Special:       "For Pistol, SMG, Assault rifle, Rifle, MG",
			Description:   "Armor piercing ammunition for penetrating defenses.",
		},
		{
			ID:            uuid.New(),
			Name:          "Rubber Coated",
			Category:      "Ammunition",
			Subcategory:   "Firearm",
			Era:           "Cyber",
			Cost:          60,
			Rarity:        0,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(-2),
			DamageType:    stringPtr("S"),
			ArmorPiercing: -2,
			Type:          "Rubber",
			Special:       "For Pistol, SMG, Assault rifle, Rifle, MG",
			Description:   "Non-lethal rubber coated ammunition.",
		},
		{
			ID:            uuid.New(),
			Name:          "Frangible",
			Category:      "Ammunition",
			Subcategory:   "Firearm",
			Era:           "Cyber",
			Cost:          60,
			Rarity:        2,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(1),
			DamageType:    stringPtr("L"),
			ArmorPiercing: -2,
			Type:          "Frangible",
			Special:       "For Pistol, SMG, Assault rifle, Rifle, MG",
			Description:   "Frangible ammunition that breaks apart on impact.",
		},
		{
			ID:            uuid.New(),
			Name:          "Explosive",
			Category:      "Ammunition",
			Subcategory:   "Firearm",
			Era:           "Cyber",
			Cost:          300,
			Rarity:        4,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(2),
			DamageType:    stringPtr("L"),
			ArmorPiercing: 0,
			Type:          "Explosive",
			Special:       "Gives weapon Risky tag, For Pistol, SMG, Assault rifle, Rifle, MG",
			Description:   "Explosive ammunition with devastating impact.",
		},
		{
			ID:            uuid.New(),
			Name:          "Subsonic",
			Category:      "Ammunition",
			Subcategory:   "Firearm",
			Era:           "Cyber",
			Cost:          60,
			Rarity:        3,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(-2),
			DamageType:    stringPtr("L"),
			ArmorPiercing: 0,
			Type:          "Subsonic",
			Special:       "Increases hearing threshold by 2, For Pistol, SMG, Assault rifle, Rifle, MG",
			Description:   "Subsonic ammunition for stealth operations.",
		},
		{
			ID:            uuid.New(),
			Name:          "Flechette",
			Category:      "Ammunition",
			Subcategory:   "Firearm",
			Era:           "Cyber",
			Cost:          70,
			Rarity:        3,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(0),
			DamageType:    stringPtr("L"),
			ArmorPiercing: 0,
			Type:          "Flechette",
			Special:       "Area: Engaged, When Combined with full auto = Close area and -6 Defense, For Shotgun, Flechette pistol",
			Description:   "Flechette ammunition with wide area effect.",
		},
		{
			ID:            uuid.New(),
			Name:          "Injector Dart",
			Category:      "Ammunition",
			Subcategory:   "Firearm",
			Era:           "Cyber",
			Cost:          100,
			Rarity:        3,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(0),
			DamageType:    stringPtr("S"),
			ArmorPiercing: 0,
			Type:          "Injector",
			Special:       "For Dart gun",
			Description:   "Darts for injector weapons.",
		},
		{
			ID:            uuid.New(),
			Name:          "Grenade (Frag)",
			Category:      "Ammunition",
			Subcategory:   "Grenade",
			Era:           "Cyber",
			Cost:          2500,
			Rarity:        4,
			Size:          1,
			Weight:        0.5,
			Damage:        intPtr(12),
			DamageType:    stringPtr("L"),
			ArmorPiercing: 0,
			Type:          "Fragmentation",
			Special:       "Area: Close, For Grenade Launcher",
			Description:   "Fragmentation grenades for area damage.",
		},
		{
			ID:            uuid.New(),
			Name:          "Grenade (Gas)",
			Category:      "Ammunition",
			Subcategory:   "Grenade",
			Era:           "Cyber",
			Cost:          1500,
			Rarity:        5,
			Size:          1,
			Weight:        0.5,
			Damage:        intPtr(0),
			DamageType:    stringPtr("S"),
			ArmorPiercing: 0,
			Type:          "Gas",
			Special:       "Area: Close, As Chemical, For Grenade Launcher",
			Description:   "Gas grenades for chemical warfare.",
		},
		{
			ID:            uuid.New(),
			Name:          "Grenade (High explosive)",
			Category:      "Ammunition",
			Subcategory:   "Grenade",
			Era:           "Cyber",
			Cost:          4500,
			Rarity:        4,
			Size:          1,
			Weight:        0.5,
			Damage:        intPtr(10),
			DamageType:    stringPtr("L"),
			ArmorPiercing: 3,
			Type:          "High Explosive",
			Special:       "Area: Close, For Grenade Launcher",
			Description:   "High explosive grenades for maximum destruction.",
		},
		{
			ID:            uuid.New(),
			Name:          "Grenade (Stun)",
			Category:      "Ammunition",
			Subcategory:   "Grenade",
			Era:           "Cyber",
			Cost:          2000,
			Rarity:        4,
			Size:          1,
			Weight:        0.5,
			Damage:        intPtr(10),
			DamageType:    stringPtr("S"),
			ArmorPiercing: 0,
			Type:          "Stun",
			Special:       "Area: Close, Stun damage, For Grenade Launcher",
			Description:   "Stun grenades for non-lethal crowd control.",
		},
		{
			ID:            uuid.New(),
			Name:          "Grenade (Smoke)",
			Category:      "Ammunition",
			Subcategory:   "Grenade",
			Era:           "Cyber",
			Cost:          1000,
			Rarity:        2,
			Size:          1,
			Weight:        0.5,
			Damage:        intPtr(0),
			DamageType:    stringPtr("S"),
			ArmorPiercing: 0,
			Type:          "Smoke",
			Special:       "Area: Close, For Grenade Launcher",
			Description:   "Smoke grenades for concealment.",
		},
		{
			ID:            uuid.New(),
			Name:          "Grenade (Incendiary)",
			Category:      "Ammunition",
			Subcategory:   "Grenade",
			Era:           "Cyber",
			Cost:          2000,
			Rarity:        4,
			Size:          1,
			Weight:        0.5,
			Damage:        intPtr(8),
			DamageType:    stringPtr("L"),
			ArmorPiercing: 0,
			Type:          "Incendiary",
			Special:       "Area: Engaged, Flaming, For Grenade Launcher",
			Description:   "Incendiary grenades for fire damage.",
		},
		{
			ID:            uuid.New(),
			Name:          "Slug",
			Category:      "Ammunition",
			Subcategory:   "Firearm",
			Era:           "Cyber",
			Cost:          50,
			Rarity:        2,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(1),
			DamageType:    stringPtr("L"),
			ArmorPiercing: 0,
			Type:          "Slug",
			Special:       "No area, For Shotgun",
			Description:   "Solid slug ammunition for shotguns.",
		},
		{
			ID:            uuid.New(),
			Name:          "Breach",
			Category:      "Ammunition",
			Subcategory:   "Firearm",
			Era:           "Cyber",
			Cost:          50,
			Rarity:        3,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(1),
			DamageType:    stringPtr("L"),
			ArmorPiercing: 2,
			Type:          "Breach",
			Special:       "Range: Engaged, For Shotgun",
			Description:   "Breaching ammunition for door and barrier destruction.",
		},
		{
			ID:            uuid.New(),
			Name:          "Rocket/Missile (Frag)",
			Category:      "Ammunition",
			Subcategory:   "Rocket",
			Era:           "Cyber",
			Cost:          500,
			Rarity:        7,
			Size:          2,
			Weight:        2.0,
			Damage:        intPtr(16),
			DamageType:    stringPtr("L"),
			ArmorPiercing: 0,
			Type:          "Fragmentation",
			Special:       "Area: Close, For Rocket launcher",
			Description:   "Fragmentation rockets for area damage.",
		},
		{
			ID:            uuid.New(),
			Name:          "Rocket/Missile (High Explosive)",
			Category:      "Ammunition",
			Subcategory:   "Rocket",
			Era:           "Cyber",
			Cost:          800,
			Rarity:        7,
			Size:          2,
			Weight:        2.0,
			Damage:        intPtr(15),
			DamageType:    stringPtr("L"),
			ArmorPiercing: 3,
			Type:          "High Explosive",
			Special:       "Area: Close, For Rocket launcher",
			Description:   "High explosive rockets for maximum destruction.",
		},
		{
			ID:            uuid.New(),
			Name:          "Rocket/Missile (Anti Vehicle)",
			Category:      "Ammunition",
			Subcategory:   "Rocket",
			Era:           "Cyber",
			Cost:          800,
			Rarity:        7,
			Size:          2,
			Weight:        2.0,
			Damage:        intPtr(18),
			DamageType:    stringPtr("L"),
			ArmorPiercing: 3,
			Type:          "Anti Vehicle",
			Special:       "Area: Engaged, Direct hit: +3 dmg, +2 AP, For Rocket launcher",
			Description:   "Anti-vehicle rockets for heavy targets.",
		},
		{
			ID:            uuid.New(),
			Name:          "Gas round",
			Category:      "Ammunition",
			Subcategory:   "Firearm",
			Era:           "Cyber",
			Cost:          50,
			Rarity:        4,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(0),
			DamageType:    stringPtr("S"),
			ArmorPiercing: 0,
			Type:          "Gas",
			Special:       "Area: Engaged, max range: Close, As Drug, For Shotgun",
			Description:   "Gas rounds for chemical dispersal.",
		},
		{
			ID:            uuid.New(),
			Name:          "Taser round",
			Category:      "Ammunition",
			Subcategory:   "Firearm",
			Era:           "Cyber",
			Cost:          200,
			Rarity:        2,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(-4),
			DamageType:    stringPtr("S"),
			ArmorPiercing: 0,
			Type:          "Taser",
			Special:       "Shocking, No area, Stun damage, For Shotgun",
			Description:   "Taser rounds for non-lethal takedowns.",
		},
		{
			ID:            uuid.New(),
			Name:          "Dragons Breath",
			Category:      "Ammunition",
			Subcategory:   "Firearm",
			Era:           "Cyber",
			Cost:          200,
			Rarity:        4,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(-3),
			DamageType:    stringPtr("L"),
			ArmorPiercing: 0,
			Type:          "Incendiary",
			Special:       "Flaming, Area: Engage, max range close, For Shotgun",
			Description:   "Incendiary shotgun rounds for fire damage.",
		},
		{
			ID:            uuid.New(),
			Name:          "Flame Fuel",
			Category:      "Ammunition",
			Subcategory:   "Firearm",
			Era:           "Cyber",
			Cost:          200,
			Rarity:        2,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(0),
			DamageType:    stringPtr("L"),
			ArmorPiercing: 0,
			Type:          "Fuel",
			Special:       "Flaming, For Flamethrower",
			Description:   "Fuel for flamethrower weapons.",
		},
		{
			ID:            uuid.New(),
			Name:          "Assault Cannon Rounds",
			Category:      "Ammunition",
			Subcategory:   "Firearm",
			Era:           "Cyber",
			Cost:          300,
			Rarity:        6,
			Size:          1,
			Weight:        0.2,
			Damage:        intPtr(0),
			DamageType:    stringPtr("L"),
			ArmorPiercing: 0,
			Type:          "Cannon",
			Special:       "For Assault Cannon",
			Description:   "Heavy ammunition for assault cannons.",
		},
		{
			ID:            uuid.New(),
			Name:          "Rail Gun Ammo & Battery",
			Category:      "Ammunition",
			Subcategory:   "Firearm",
			Era:           "Cyber",
			Cost:          1000,
			Rarity:        10,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(0),
			DamageType:    stringPtr("L"),
			ArmorPiercing: 0,
			Type:          "Rail",
			Special:       "For Rail Gun",
			Description:   "Specialized ammunition and power for rail guns.",
		},
		{
			ID:            uuid.New(),
			Name:          "Tracer",
			Category:      "Ammunition",
			Subcategory:   "Firearm",
			Era:           "Cyber",
			Cost:          60,
			Rarity:        2,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(0),
			DamageType:    stringPtr("L"),
			ArmorPiercing: 0,
			Type:          "Tracer",
			Special:       "Automatic fire only, 1 less range penalty, For Pistol, SMG, Assault rifle, Rifle, MG",
			Description:   "Tracer rounds for improved accuracy in automatic fire.",
		},
		{
			ID:            uuid.New(),
			Name:          "Arrow/Bolt (Gas)",
			Category:      "Ammunition",
			Subcategory:   "Arrows",
			Era:           "Cyber",
			Cost:          100,
			Rarity:        3,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(0),
			DamageType:    stringPtr("S"),
			ArmorPiercing: 0,
			Type:          "Gas",
			Special:       "Area: Engaged, As Drug, For Bow, Crossbow",
			Description:   "Gas-tipped arrows and bolts for chemical delivery.",
		},
		{
			ID:            uuid.New(),
			Name:          "Arrow/Bolt (Explosive)",
			Category:      "Ammunition",
			Subcategory:   "Arrows",
			Era:           "Cyber",
			Cost:          300,
			Rarity:        4,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(1),
			DamageType:    stringPtr("L"),
			ArmorPiercing: 2,
			Type:          "Explosive",
			Special:       "Area: Engaged, Risky, For Bow, Crossbow",
			Description:   "Explosive arrows and bolts for area damage.",
		},
		{
			ID:            uuid.New(),
			Name:          "Arrow/Bolt (Taser)",
			Category:      "Ammunition",
			Subcategory:   "Arrows",
			Era:           "Cyber",
			Cost:          100,
			Rarity:        2,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(-3),
			DamageType:    stringPtr("S"),
			ArmorPiercing: 0,
			Type:          "Taser",
			Special:       "Shocking, For Bow, Crossbow",
			Description:   "Taser-tipped arrows and bolts for non-lethal attacks.",
		},
		{
			ID:            uuid.New(),
			Name:          "Arrow/Bolt (Injection)",
			Category:      "Ammunition",
			Subcategory:   "Arrows",
			Era:           "Cyber",
			Cost:          250,
			Rarity:        3,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(-5),
			DamageType:    stringPtr("L"),
			ArmorPiercing: -2,
			Type:          "Injection",
			Special:       "Injector, For Bow, Crossbow",
			Description:   "Injection arrows and bolts for drug delivery.",
		},
		{
			ID:            uuid.New(),
			Name:          "Battery",
			Category:      "Ammunition",
			Subcategory:   "Energy",
			Era:           "Cyber",
			Cost:          300,
			Rarity:        4,
			Size:          1,
			Weight:        0.1,
			Damage:        intPtr(0),
			DamageType:    stringPtr("L"),
			ArmorPiercing: 0,
			Type:          "Battery",
			Special:       "Armor Wrecker 1, For Laser",
			Description:   "Power batteries for laser weapons.",
		},
		{
			ID:            uuid.New(),
			Name:          "Smart function",
			Category:      "Ammunition",
			Subcategory:   "Modification",
			Era:           "Cyber",
			Cost:          200,
			Rarity:        1,
			Size:          0,
			Weight:        0.0,
			Damage:        intPtr(0),
			DamageType:    stringPtr("L"),
			ArmorPiercing: 0,
			Type:          "Smart",
			Special:       "Requires Smartlink, Exploding 6s when aiming, Only works on bullets and slugs",
			Description:   "Smart targeting modification for ammunition.",
		},
	}
}
