package seeds

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type EquipmentItem struct {
	ID              uuid.UUID `gorm:"type:uuid;primary_key;default:gen_random_uuid()"`
	Name            string    `gorm:"not null"`
	Category        string    `gorm:"not null"` // Weapon, Armor, Tool, Personal, Vehicle
	Subcategory     string    `gorm:"not null"` // Melee, Ranged, Body, Head, etc.
	Era             string    `gorm:"not null"` // Medieval, Industrial, Cyber
	Cost            int       `gorm:"not null"`
	Rarity          int       `gorm:"not null"` // 0=Civilian, 1-3=Restricted, 4-5=Military
	Size            int       `gorm:"not null"`
	Weight          float64   `gorm:"not null"`
	Damage          string    `gorm:"default:''"`
	ArmorRating     int       `gorm:"default:0"`
	BallisticRating int       `gorm:"default:0"`
	Type            string    `gorm:"default:''"` // Blade, Club, Soft, Hard, etc.
	Special         string    `gorm:"default:''"` // Special properties
	Parry           bool      `gorm:"default:false"`
	StandardMods    string    `gorm:"default:''"`
	Description     string    `gorm:"default:''"`
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (EquipmentItem) TableName() string {
	return "equipment_items"
}

func SeedEquipmentItems(db *gorm.DB) error {
	items := []EquipmentItem{
		// Medieval Melee Weapons
		{
			ID:          uuid.New(),
			Name:        "Punching Dagger",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        200,
			Rarity:      0,
			Size:        0,
			Weight:      0.5,
			Damage:      "+0L",
			Type:        "Unarmed",
			Special:     "Brawling",
			Parry:       false,
			Description: "A small dagger designed for punching attacks, easily concealed.",
		},
		{
			ID:          uuid.New(),
			Name:        "Sap",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        250,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Damage:      "+0S",
			Type:        "Club",
			Special:     "Headcracker",
			Parry:       false,
			Description: "A weighted leather pouch used for non-lethal takedowns.",
		},
		{
			ID:          uuid.New(),
			Name:        "Bolas",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        50,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Damage:      "+0S",
			Type:        "Throwing",
			Special:     "Throwing, Tripping, Trapping, Risky",
			Parry:       false,
			Description: "Rope with weighted ends used to entangle and trip targets.",
		},
		{
			ID:          uuid.New(),
			Name:        "Dagger/Tanto",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        200,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Damage:      "+1L",
			Type:        "Blade",
			Special:     "Armor piercing: 1",
			Parry:       false,
			Description: "A short, sharp blade perfect for close combat and throwing.",
		},
		{
			ID:          uuid.New(),
			Name:        "Parrying Dagger/Sai",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        500,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Damage:      "+1L",
			Type:        "Blade",
			Special:     "Shield bonus 1, Parrying 1",
			Parry:       true,
			Description: "A specialized dagger with side guards designed for parrying attacks.",
		},
		{
			ID:          uuid.New(),
			Name:        "War Fan",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        700,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Damage:      "+0L",
			Type:        "Blade",
			Special:     "Concealed",
			Parry:       true,
			Description: "An elegant but deadly fan with sharpened edges.",
		},
		{
			ID:          uuid.New(),
			Name:        "Tiger Claws",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        700,
			Rarity:      2,
			Size:        1,
			Weight:      1.0,
			Damage:      "+1L",
			Type:        "Unarmed",
			Special:     "Brawling",
			Parry:       true,
			Description: "Metal claws worn on the hands for devastating unarmed attacks.",
		},
		{
			ID:          uuid.New(),
			Name:        "Club/Baton",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        0,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "+1S/1L",
			Type:        "Club",
			Special:     "Blunt",
			Parry:       true,
			Description: "A simple wooden club or metal baton, easily improvised.",
		},
		{
			ID:          uuid.New(),
			Name:        "Lasso",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        50,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "-1S",
			Type:        "Exotic",
			Special:     "Restraining, trapping, increased reach 2",
			Parry:       false,
			Description: "A rope loop used to catch and restrain targets from a distance.",
		},
		{
			ID:          uuid.New(),
			Name:        "Whip",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        100,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "-1S",
			Type:        "Exotic/Wire",
			Special:     "Restraining, Disarming, Increased reach 1",
			Parry:       false,
			Description: "A flexible weapon that can disarm and restrain opponents.",
		},
		{
			ID:          uuid.New(),
			Name:        "Chain",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        200,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "+1L",
			Type:        "Exotic/Wire",
			Special:     "Restraining, Increased reach 1",
			Parry:       false,
			Description: "A heavy chain that can be used as a weapon or restraint.",
		},
		{
			ID:          uuid.New(),
			Name:        "Nunchaku",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        300,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "+1S",
			Type:        "Club",
			Special:     "Disarming, Risky",
			Parry:       true,
			Description: "Two wooden sticks connected by a chain, requiring skill to use effectively.",
		},
		{
			ID:          uuid.New(),
			Name:        "Hatchet/Machete",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        300,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "+2L",
			Type:        "Blade/Axe",
			Special:     "Gaping wounds",
			Parry:       true,
			Description: "A versatile cutting tool that doubles as an effective weapon.",
		},
		{
			ID:          uuid.New(),
			Name:        "Throwing Axe",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        400,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "+2L",
			Type:        "Throwing/Axe",
			Special:     "Throwing, Gaping wounds",
			Parry:       true,
			Description: "A balanced axe designed for throwing at targets.",
		},
		{
			ID:          uuid.New(),
			Name:        "Sickle/Kama",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        400,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "+2L",
			Type:        "Axe",
			Special:     "Disarming",
			Parry:       true,
			Description: "A curved blade originally used for harvesting, effective in combat.",
		},
		{
			ID:          uuid.New(),
			Name:        "Kusari-Gama",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        500,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "+2L",
			Type:        "Exotic",
			Special:     "Risky, Restraining, Increased reach 1",
			Parry:       true,
			Description: "A sickle attached to a chain, combining cutting and restraining capabilities.",
		},
		{
			ID:          uuid.New(),
			Name:        "Short Sword/Gladius/Wakizashi",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        800,
			Rarity:      2,
			Size:        2,
			Weight:      2.0,
			Damage:      "+2L",
			Type:        "Blade",
			Special:     "Quick 1",
			Parry:       true,
			Description: "A versatile short sword used by warriors across many cultures.",
		},
		{
			ID:          uuid.New(),
			Name:        "Rapier",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        1000,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "+2L",
			Type:        "Blade",
			Special:     "Increased reach 1",
			Parry:       true,
			Description: "An elegant thrusting sword with a long, narrow blade.",
		},
		{
			ID:          uuid.New(),
			Name:        "Flanged Mace/Warhammer",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        1200,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "+2L",
			Type:        "Club",
			Special:     "Armor piercing 2",
			Parry:       true,
			Description: "A heavy weapon designed to crush armor and bone.",
		},
		{
			ID:          uuid.New(),
			Name:        "Javelin",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        1500,
			Rarity:      0,
			Size:        3,
			Weight:      3.0,
			Damage:      "+2L",
			Type:        "Throwing/Polearm",
			Special:     "Throwing, armor piercing 1",
			Parry:       true,
			Description: "A spear designed for throwing, effective against armored targets.",
		},
		{
			ID:          uuid.New(),
			Name:        "Flail",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        300,
			Rarity:      0,
			Size:        3,
			Weight:      3.0,
			Damage:      "+2L",
			Type:        "Club",
			Special:     "Armor Piercing 1, Inaccurate -1",
			Parry:       true,
			Description: "A chain weapon that can strike around shields and armor.",
		},
		{
			ID:          uuid.New(),
			Name:        "Battle Axe",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        500,
			Rarity:      0,
			Size:        3,
			Weight:      3.0,
			Damage:      "+3L",
			Type:        "Axe",
			Special:     "Disarming, Gaping wounds",
			Parry:       true,
			Description: "A heavy axe designed for combat, capable of devastating wounds.",
		},
		{
			ID:          uuid.New(),
			Name:        "Arming Sword",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        800,
			Rarity:      0,
			Size:        3,
			Weight:      3.0,
			Damage:      "+3L",
			Type:        "Blade",
			Special:     "Parrying 1",
			Parry:       true,
			Description: "A versatile one-handed sword with a straight, double-edged blade.",
		},
		{
			ID:          uuid.New(),
			Name:        "Katana",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        2000,
			Rarity:      0,
			Size:        3,
			Weight:      3.0,
			Damage:      "+3L",
			Type:        "Blade",
			Special:     "Quick 1",
			Parry:       true,
			Description: "A curved Japanese sword known for its sharpness and cutting power.",
		},
		{
			ID:          uuid.New(),
			Name:        "Heavy Club",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        2500,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+2S/L",
			Type:        "Club",
			Special:     "Blunt",
			Parry:       true,
			Description: "A massive club that can deliver both stunning and lethal damage.",
		},
		{
			ID:          uuid.New(),
			Name:        "Catchpole",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        150,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+0S",
			Type:        "Polearm",
			Special:     "Trapping, Light",
			Parry:       true,
			Description: "A pole with a collar designed to capture and restrain targets.",
		},
		{
			ID:          uuid.New(),
			Name:        "Staff",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        300,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+1S",
			Type:        "Club",
			Special:     "Parrying 1",
			Parry:       true,
			Description: "A simple wooden staff, effective for both attack and defense.",
		},
		{
			ID:          uuid.New(),
			Name:        "Net",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        300,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "0",
			Type:        "Exotic/Wire",
			Special:     "Throwing, Trapping, Light",
			Parry:       false,
			Description: "A weighted net used to entangle and capture targets.",
		},
		{
			ID:          uuid.New(),
			Name:        "Pitchfork",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        400,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+1L",
			Type:        "Polearm",
			Special:     "Parrying 1, Inaccurate -1",
			Parry:       true,
			Description: "A farming tool that can be used as an effective weapon.",
		},
		{
			ID:          uuid.New(),
			Name:        "Trident",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        550,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+3L",
			Type:        "Polearm",
			Special:     "Throwing",
			Parry:       true,
			Description: "A three-pronged spear effective for both thrusting and throwing.",
		},
		{
			ID:          uuid.New(),
			Name:        "Greataxe",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        700,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+4L",
			Type:        "Axe",
			Special:     "Gaping wounds",
			Parry:       true,
			Description: "A massive two-handed axe capable of devastating wounds.",
		},
		{
			ID:          uuid.New(),
			Name:        "Bastard Sword",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        2000,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+3L",
			Type:        "Blade",
			Special:     "1 or 2 handed, Parrying 1, can be quickdrawn by size 5",
			Parry:       true,
			Description: "A versatile sword that can be used one or two-handed.",
		},
		{
			ID:          uuid.New(),
			Name:        "Heavy Mace",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        3000,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+3L",
			Type:        "Club",
			Special:     "Armor piercing 2",
			Parry:       true,
			Description: "A heavy mace designed to crush through armor.",
		},
		{
			ID:          uuid.New(),
			Name:        "Greatsword",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        3000,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+4L",
			Type:        "Blade",
			Special:     "Parrying 1",
			Parry:       true,
			Description: "A massive two-handed sword requiring great strength to wield.",
		},
		{
			ID:          uuid.New(),
			Name:        "Nodachi",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        4000,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+4L",
			Type:        "Blade",
			Special:     "Area attack +1 target",
			Parry:       true,
			Description: "An extremely long Japanese sword capable of striking multiple targets.",
		},
		{
			ID:          uuid.New(),
			Name:        "Spear",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        4000,
			Rarity:      0,
			Size:        5,
			Weight:      5.0,
			Damage:      "+2L",
			Type:        "Polearm",
			Special:     "1 or 2 Handed, Light",
			Parry:       true,
			Description: "A simple but effective polearm, the weapon of choice for many armies.",
		},
		{
			ID:          uuid.New(),
			Name:        "Cavalry Lance",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        800,
			Rarity:      0,
			Size:        5,
			Weight:      5.0,
			Damage:      "+2L",
			Type:        "Polearm",
			Special:     "Couched",
			Parry:       false,
			Description: "A long lance designed for mounted combat.",
		},
		{
			ID:          uuid.New(),
			Name:        "Halberd/Naginata",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        1200,
			Rarity:      0,
			Size:        5,
			Weight:      5.0,
			Damage:      "+3L",
			Type:        "Polearm",
			Special:     "Tripping, Armor piercing 1",
			Parry:       true,
			Description: "A polearm combining axe, spear, and hook capabilities.",
		},
		{
			ID:          uuid.New(),
			Name:        "Two-Handed Warhammer",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        3500,
			Rarity:      0,
			Size:        5,
			Weight:      5.0,
			Damage:      "+4L",
			Type:        "Club",
			Special:     "Armor piercing 2",
			Parry:       true,
			Description: "A massive hammer requiring two hands to wield effectively.",
		},
		{
			ID:          uuid.New(),
			Name:        "Pike",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        4000,
			Rarity:      0,
			Size:        6,
			Weight:      6.0,
			Damage:      "+3L",
			Type:        "Polearm",
			Special:     "Charge stopper, Light",
			Parry:       true,
			Description: "An extremely long spear designed to stop cavalry charges.",
		},
		{
			ID:          uuid.New(),
			Name:        "Improvised Weapon",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Universal",
			Cost:        0,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Damage:      "+ (Size -2)",
			Type:        "Improvised",
			Special:     "Inaccurate -2, Fragile",
			Parry:       true,
			Description: "Any object used as a weapon, from chairs to broken bottles.",
		},
	}

	// Check if equipment items already exist
	var count int64
	db.Model(&EquipmentItem{}).Count(&count)
	if count > 0 {
		return nil // Already seeded
	}

	// Create equipment items
	for _, item := range items {
		if err := db.Create(&item).Error; err != nil {
			return err
		}
	}

	return nil
}

// GetEquipmentItems returns all equipment items for seeding
func GetEquipmentItems() []EquipmentItem {
	return []EquipmentItem{
		// Medieval Melee Weapons
		{
			ID:          uuid.New(),
			Name:        "Punching Dagger",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        200,
			Rarity:      0,
			Size:        0,
			Weight:      0.5,
			Damage:      "+0L",
			Type:        "Unarmed",
			Special:     "Brawling",
			Parry:       false,
			Description: "A small dagger designed for punching attacks, easily concealed.",
		},
		{
			ID:          uuid.New(),
			Name:        "Sap",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        250,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Damage:      "+0S",
			Type:        "Club",
			Special:     "Headcracker",
			Parry:       false,
			Description: "A weighted leather pouch used for non-lethal takedowns.",
		},
		{
			ID:          uuid.New(),
			Name:        "Bolas",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        50,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Damage:      "+0S",
			Type:        "Throwing",
			Special:     "Throwing, Tripping, Trapping, Risky",
			Parry:       false,
			Description: "Rope with weighted ends used to entangle and trip targets.",
		},
		{
			ID:          uuid.New(),
			Name:        "Dagger/Tanto",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        200,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Damage:      "+1L",
			Type:        "Blade",
			Special:     "Armor piercing: 1",
			Parry:       false,
			Description: "A short, sharp blade perfect for close combat and throwing.",
		},
		{
			ID:          uuid.New(),
			Name:        "Parrying Dagger/Sai",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        500,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Damage:      "+1L",
			Type:        "Blade",
			Special:     "Shield bonus 1, Parrying 1",
			Parry:       true,
			Description: "A specialized dagger with side guards designed for parrying attacks.",
		},
		{
			ID:          uuid.New(),
			Name:        "War Fan",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        700,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Damage:      "+0L",
			Type:        "Blade",
			Special:     "Concealed",
			Parry:       true,
			Description: "An elegant but deadly fan with sharpened edges.",
		},
		{
			ID:          uuid.New(),
			Name:        "Tiger Claws",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        700,
			Rarity:      2,
			Size:        1,
			Weight:      1.0,
			Damage:      "+1L",
			Type:        "Unarmed",
			Special:     "Brawling",
			Parry:       true,
			Description: "Metal claws worn on the hands for devastating unarmed attacks.",
		},
		{
			ID:          uuid.New(),
			Name:        "Club/Baton",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        0,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "+1S/1L",
			Type:        "Club",
			Special:     "Blunt",
			Parry:       true,
			Description: "A simple wooden club or metal baton, easily improvised.",
		},
		{
			ID:          uuid.New(),
			Name:        "Lasso",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        50,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "-1S",
			Type:        "Exotic",
			Special:     "Restraining, trapping, increased reach 2",
			Parry:       false,
			Description: "A rope loop used to catch and restrain targets from a distance.",
		},
		{
			ID:          uuid.New(),
			Name:        "Whip",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        100,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "-1S",
			Type:        "Exotic/Wire",
			Special:     "Restraining, Disarming, Increased reach 1",
			Parry:       false,
			Description: "A flexible weapon that can disarm and restrain opponents.",
		},
		{
			ID:          uuid.New(),
			Name:        "Chain",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        200,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "+1L",
			Type:        "Exotic/Wire",
			Special:     "Restraining, Increased reach 1",
			Parry:       false,
			Description: "A heavy chain that can be used as a weapon or restraint.",
		},
		{
			ID:          uuid.New(),
			Name:        "Nunchaku",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        300,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "+1S",
			Type:        "Club",
			Special:     "Disarming, Risky",
			Parry:       true,
			Description: "Two wooden sticks connected by a chain, requiring skill to use effectively.",
		},
		{
			ID:          uuid.New(),
			Name:        "Hatchet/Machete",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        300,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "+2L",
			Type:        "Blade/Axe",
			Special:     "Gaping wounds",
			Parry:       true,
			Description: "A versatile cutting tool that doubles as an effective weapon.",
		},
		{
			ID:          uuid.New(),
			Name:        "Throwing Axe",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        400,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "+2L",
			Type:        "Throwing/Axe",
			Special:     "Throwing, Gaping wounds",
			Parry:       true,
			Description: "A balanced axe designed for throwing at targets.",
		},
		{
			ID:          uuid.New(),
			Name:        "Sickle/Kama",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        400,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "+2L",
			Type:        "Axe",
			Special:     "Disarming",
			Parry:       true,
			Description: "A curved blade originally used for harvesting, effective in combat.",
		},
		{
			ID:          uuid.New(),
			Name:        "Kusari-Gama",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        500,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "+2L",
			Type:        "Exotic",
			Special:     "Risky, Restraining, Increased reach 1",
			Parry:       true,
			Description: "A sickle attached to a chain, combining cutting and restraining capabilities.",
		},
		{
			ID:          uuid.New(),
			Name:        "Short Sword/Gladius/Wakizashi",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        800,
			Rarity:      2,
			Size:        2,
			Weight:      2.0,
			Damage:      "+2L",
			Type:        "Blade",
			Special:     "Quick 1",
			Parry:       true,
			Description: "A versatile short sword used by warriors across many cultures.",
		},
		{
			ID:          uuid.New(),
			Name:        "Rapier",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        1000,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "+2L",
			Type:        "Blade",
			Special:     "Increased reach 1",
			Parry:       true,
			Description: "An elegant thrusting sword with a long, narrow blade.",
		},
		{
			ID:          uuid.New(),
			Name:        "Flanged Mace/Warhammer",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        1200,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "+2L",
			Type:        "Club",
			Special:     "Armor piercing 2",
			Parry:       true,
			Description: "A heavy weapon designed to crush armor and bone.",
		},
		{
			ID:          uuid.New(),
			Name:        "Javelin",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        1500,
			Rarity:      0,
			Size:        3,
			Weight:      3.0,
			Damage:      "+2L",
			Type:        "Throwing/Polearm",
			Special:     "Throwing, armor piercing 1",
			Parry:       true,
			Description: "A spear designed for throwing, effective against armored targets.",
		},
		{
			ID:          uuid.New(),
			Name:        "Flail",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        300,
			Rarity:      0,
			Size:        3,
			Weight:      3.0,
			Damage:      "+2L",
			Type:        "Club",
			Special:     "Armor Piercing 1, Inaccurate -1",
			Parry:       true,
			Description: "A chain weapon that can strike around shields and armor.",
		},
		{
			ID:          uuid.New(),
			Name:        "Battle Axe",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        500,
			Rarity:      0,
			Size:        3,
			Weight:      3.0,
			Damage:      "+3L",
			Type:        "Axe",
			Special:     "Disarming, Gaping wounds",
			Parry:       true,
			Description: "A heavy axe designed for combat, capable of devastating wounds.",
		},
		{
			ID:          uuid.New(),
			Name:        "Arming Sword",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        800,
			Rarity:      0,
			Size:        3,
			Weight:      3.0,
			Damage:      "+3L",
			Type:        "Blade",
			Special:     "Parrying 1",
			Parry:       true,
			Description: "A versatile one-handed sword with a straight, double-edged blade.",
		},
		{
			ID:          uuid.New(),
			Name:        "Katana",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        2000,
			Rarity:      0,
			Size:        3,
			Weight:      3.0,
			Damage:      "+3L",
			Type:        "Blade",
			Special:     "Quick 1",
			Parry:       true,
			Description: "A curved Japanese sword known for its sharpness and cutting power.",
		},
		{
			ID:          uuid.New(),
			Name:        "Heavy Club",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        2500,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+2S/L",
			Type:        "Club",
			Special:     "Blunt",
			Parry:       true,
			Description: "A massive club that can deliver both stunning and lethal damage.",
		},
		{
			ID:          uuid.New(),
			Name:        "Catchpole",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        150,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+0S",
			Type:        "Polearm",
			Special:     "Trapping, Light",
			Parry:       true,
			Description: "A pole with a collar designed to capture and restrain targets.",
		},
		{
			ID:          uuid.New(),
			Name:        "Staff",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        300,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+1S",
			Type:        "Club",
			Special:     "Parrying 1",
			Parry:       true,
			Description: "A simple wooden staff, effective for both attack and defense.",
		},
		{
			ID:          uuid.New(),
			Name:        "Net",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        300,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "0",
			Type:        "Exotic/Wire",
			Special:     "Throwing, Trapping, Light",
			Parry:       false,
			Description: "A weighted net used to entangle and capture targets.",
		},
		{
			ID:          uuid.New(),
			Name:        "Pitchfork",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        400,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+1L",
			Type:        "Polearm",
			Special:     "Parrying 1, Inaccurate -1",
			Parry:       true,
			Description: "A farming tool that can be used as an effective weapon.",
		},
		{
			ID:          uuid.New(),
			Name:        "Trident",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        550,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+3L",
			Type:        "Polearm",
			Special:     "Throwing",
			Parry:       true,
			Description: "A three-pronged spear effective for both thrusting and throwing.",
		},
		{
			ID:          uuid.New(),
			Name:        "Greataxe",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        700,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+4L",
			Type:        "Axe",
			Special:     "Gaping wounds",
			Parry:       true,
			Description: "A massive two-handed axe capable of devastating wounds.",
		},
		{
			ID:          uuid.New(),
			Name:        "Bastard Sword",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        2000,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+3L",
			Type:        "Blade",
			Special:     "1 or 2 handed, Parrying 1, can be quickdrawn by size 5",
			Parry:       true,
			Description: "A versatile sword that can be used one or two-handed.",
		},
		{
			ID:          uuid.New(),
			Name:        "Heavy Mace",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        3000,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+3L",
			Type:        "Club",
			Special:     "Armor piercing 2",
			Parry:       true,
			Description: "A heavy mace designed to crush through armor.",
		},
		{
			ID:          uuid.New(),
			Name:        "Greatsword",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        3000,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+4L",
			Type:        "Blade",
			Special:     "Parrying 1",
			Parry:       true,
			Description: "A massive two-handed sword requiring great strength to wield.",
		},
		{
			ID:          uuid.New(),
			Name:        "Nodachi",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        4000,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+4L",
			Type:        "Blade",
			Special:     "Area attack +1 target",
			Parry:       true,
			Description: "An extremely long Japanese sword capable of striking multiple targets.",
		},
		{
			ID:          uuid.New(),
			Name:        "Spear",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        4000,
			Rarity:      0,
			Size:        5,
			Weight:      5.0,
			Damage:      "+2L",
			Type:        "Polearm",
			Special:     "1 or 2 Handed, Light",
			Parry:       true,
			Description: "A simple but effective polearm, the weapon of choice for many armies.",
		},
		{
			ID:          uuid.New(),
			Name:        "Cavalry Lance",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        800,
			Rarity:      0,
			Size:        5,
			Weight:      5.0,
			Damage:      "+2L",
			Type:        "Polearm",
			Special:     "Couched",
			Parry:       false,
			Description: "A long lance designed for mounted combat.",
		},
		{
			ID:          uuid.New(),
			Name:        "Halberd/Naginata",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        1200,
			Rarity:      0,
			Size:        5,
			Weight:      5.0,
			Damage:      "+3L",
			Type:        "Polearm",
			Special:     "Tripping, Armor piercing 1",
			Parry:       true,
			Description: "A polearm combining axe, spear, and hook capabilities.",
		},
		{
			ID:          uuid.New(),
			Name:        "Two-Handed Warhammer",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        3500,
			Rarity:      0,
			Size:        5,
			Weight:      5.0,
			Damage:      "+4L",
			Type:        "Club",
			Special:     "Armor piercing 2",
			Parry:       true,
			Description: "A massive hammer requiring two hands to wield effectively.",
		},
		{
			ID:          uuid.New(),
			Name:        "Pike",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        4000,
			Rarity:      0,
			Size:        6,
			Weight:      6.0,
			Damage:      "+3L",
			Type:        "Polearm",
			Special:     "Charge stopper, Light",
			Parry:       true,
			Description: "An extremely long spear designed to stop cavalry charges.",
		},
		{
			ID:          uuid.New(),
			Name:        "Improvised Weapon",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Universal",
			Cost:        0,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Damage:      "+ (Size -2)",
			Type:        "Improvised",
			Special:     "Inaccurate -2, Fragile",
			Parry:       true,
			Description: "Any object used as a weapon, from chairs to broken bottles.",
		},
	}
}
