package seeds

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type EquipmentItem struct {
	ID              uuid.UUID `gorm:"type:uuid;primary_key;default:gen_random_uuid()"`
	Name            string    `gorm:"not null"`
	Category        string    `gorm:"not null"` // Weapon, Armor, Tool, Personal, Vehicle
	Subcategory     string    `gorm:"not null"` // Melee, Ranged, Body, Head, etc.
	Era             string    `gorm:"not null"` // Medieval, Industrial, Cyber
	Cost            int       `gorm:"not null"`
	Rarity          int       `gorm:"not null"` // 0=Civilian, 1-3=Restricted, 4-5=Military
	Size            int       `gorm:"not null"`
	Weight          float64   `gorm:"not null"`
	Damage          string    `gorm:"default:''"`
	ArmorRating     int       `gorm:"default:0"`
	BallisticRating int       `gorm:"default:0"`
	Type            string    `gorm:"default:''"` // Blade, Club, Soft, Hard, etc.
	Special         string    `gorm:"default:''"` // Special properties
	Parry           bool      `gorm:"default:false"`
	StandardMods    string    `gorm:"default:''"`
	Description     string    `gorm:"default:''"`
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (EquipmentItem) TableName() string {
	return "equipment_items"
}

func SeedEquipmentItems(db *gorm.DB) error {
	items := GetEquipmentItems()

	// Check if equipment items already exist
	var count int64
	db.Model(&EquipmentItem{}).Count(&count)
	if count > 0 {
		return nil // Already seeded
	}

	// Create equipment items
	for _, item := range items {
		if err := db.Create(&item).Error; err != nil {
			return err
		}
	}

	return nil
}

// GetEquipmentItems returns all equipment items for seeding
func GetEquipmentItems() []EquipmentItem {
	return []EquipmentItem{
		// Medieval Melee Weapons
		{
			ID:          uuid.New(),
			Name:        "Punching Dagger",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        200,
			Rarity:      0,
			Size:        0,
			Weight:      0.5,
			Damage:      "+0L",
			Type:        "Unarmed",
			Special:     "Brawling",
			Parry:       false,
			Description: "A small dagger designed for punching attacks, easily concealed.",
		},
		{
			ID:          uuid.New(),
			Name:        "Sap",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        250,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Damage:      "+0S",
			Type:        "Club",
			Special:     "Headcracker",
			Parry:       false,
			Description: "A weighted leather pouch used for non-lethal takedowns.",
		},
		{
			ID:          uuid.New(),
			Name:        "Bolas",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        50,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Damage:      "+0S",
			Type:        "Throwing",
			Special:     "Throwing, Tripping, Trapping, Risky",
			Parry:       false,
			Description: "Rope with weighted ends used to entangle and trip targets.",
		},
		{
			ID:          uuid.New(),
			Name:        "Dagger/Tanto",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        200,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Damage:      "+1L",
			Type:        "Blade",
			Special:     "Armor piercing: 1",
			Parry:       false,
			Description: "A short, sharp blade perfect for close combat and throwing.",
		},
		{
			ID:          uuid.New(),
			Name:        "Parrying Dagger/Sai",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        500,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Damage:      "+1L",
			Type:        "Blade",
			Special:     "Shield bonus 1, Parrying 1",
			Parry:       true,
			Description: "A specialized dagger with side guards designed for parrying attacks.",
		},
		{
			ID:          uuid.New(),
			Name:        "War Fan",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        700,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Damage:      "+0L",
			Type:        "Blade",
			Special:     "Concealed",
			Parry:       true,
			Description: "An elegant but deadly fan with sharpened edges.",
		},
		{
			ID:          uuid.New(),
			Name:        "Tiger Claws",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        700,
			Rarity:      2,
			Size:        1,
			Weight:      1.0,
			Damage:      "+1L",
			Type:        "Unarmed",
			Special:     "Brawling",
			Parry:       true,
			Description: "Metal claws worn on the hands for devastating unarmed attacks.",
		},
		{
			ID:          uuid.New(),
			Name:        "Club/Baton",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        0,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "+1S/1L",
			Type:        "Club",
			Special:     "Blunt",
			Parry:       true,
			Description: "A simple wooden club or metal baton, easily improvised.",
		},
		{
			ID:          uuid.New(),
			Name:        "Lasso",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        50,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "-1S",
			Type:        "Exotic",
			Special:     "Restraining, trapping, increased reach 2",
			Parry:       false,
			Description: "A rope loop used to catch and restrain targets from a distance.",
		},
		{
			ID:          uuid.New(),
			Name:        "Whip",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        100,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "-1S",
			Type:        "Exotic/Wire",
			Special:     "Restraining, Disarming, Increased reach 1",
			Parry:       false,
			Description: "A flexible weapon that can disarm and restrain opponents.",
		},
		{
			ID:          uuid.New(),
			Name:        "Chain",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        200,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "+1L",
			Type:        "Exotic/Wire",
			Special:     "Restraining, Increased reach 1",
			Parry:       false,
			Description: "A heavy chain that can be used as a weapon or restraint.",
		},
		{
			ID:          uuid.New(),
			Name:        "Nunchaku",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        300,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "+1S",
			Type:        "Club",
			Special:     "Disarming, Risky",
			Parry:       true,
			Description: "Two wooden sticks connected by a chain, requiring skill to use effectively.",
		},
		{
			ID:          uuid.New(),
			Name:        "Hatchet/Machete",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        300,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "+2L",
			Type:        "Blade/Axe",
			Special:     "Gaping wounds",
			Parry:       true,
			Description: "A versatile cutting tool that doubles as an effective weapon.",
		},
		{
			ID:          uuid.New(),
			Name:        "Throwing Axe",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        400,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "+2L",
			Type:        "Throwing/Axe",
			Special:     "Throwing, Gaping wounds",
			Parry:       true,
			Description: "A balanced axe designed for throwing at targets.",
		},
		{
			ID:          uuid.New(),
			Name:        "Sickle/Kama",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        400,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "+2L",
			Type:        "Axe",
			Special:     "Disarming",
			Parry:       true,
			Description: "A curved blade originally used for harvesting, effective in combat.",
		},
		{
			ID:          uuid.New(),
			Name:        "Kusari-Gama",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        500,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "+2L",
			Type:        "Exotic",
			Special:     "Risky, Restraining, Increased reach 1",
			Parry:       true,
			Description: "A sickle attached to a chain, combining cutting and restraining capabilities.",
		},
		{
			ID:          uuid.New(),
			Name:        "Short Sword/Gladius/Wakizashi",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        800,
			Rarity:      2,
			Size:        2,
			Weight:      2.0,
			Damage:      "+2L",
			Type:        "Blade",
			Special:     "Quick 1",
			Parry:       true,
			Description: "A versatile short sword used by warriors across many cultures.",
		},
		{
			ID:          uuid.New(),
			Name:        "Rapier",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        1000,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "+2L",
			Type:        "Blade",
			Special:     "Increased reach 1",
			Parry:       true,
			Description: "An elegant thrusting sword with a long, narrow blade.",
		},
		{
			ID:          uuid.New(),
			Name:        "Flanged Mace/Warhammer",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        1200,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "+2L",
			Type:        "Club",
			Special:     "Armor piercing 2",
			Parry:       true,
			Description: "A heavy weapon designed to crush armor and bone.",
		},
		{
			ID:          uuid.New(),
			Name:        "Javelin",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        1500,
			Rarity:      0,
			Size:        3,
			Weight:      3.0,
			Damage:      "+2L",
			Type:        "Throwing/Polearm",
			Special:     "Throwing, armor piercing 1",
			Parry:       true,
			Description: "A spear designed for throwing, effective against armored targets.",
		},
		{
			ID:          uuid.New(),
			Name:        "Flail",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        300,
			Rarity:      0,
			Size:        3,
			Weight:      3.0,
			Damage:      "+2L",
			Type:        "Club",
			Special:     "Armor Piercing 1, Inaccurate -1",
			Parry:       true,
			Description: "A chain weapon that can strike around shields and armor.",
		},
		{
			ID:          uuid.New(),
			Name:        "Battle Axe",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        500,
			Rarity:      0,
			Size:        3,
			Weight:      3.0,
			Damage:      "+3L",
			Type:        "Axe",
			Special:     "Disarming, Gaping wounds",
			Parry:       true,
			Description: "A heavy axe designed for combat, capable of devastating wounds.",
		},
		{
			ID:          uuid.New(),
			Name:        "Arming Sword",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        800,
			Rarity:      0,
			Size:        3,
			Weight:      3.0,
			Damage:      "+3L",
			Type:        "Blade",
			Special:     "Parrying 1",
			Parry:       true,
			Description: "A versatile one-handed sword with a straight, double-edged blade.",
		},
		{
			ID:          uuid.New(),
			Name:        "Katana",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        2000,
			Rarity:      0,
			Size:        3,
			Weight:      3.0,
			Damage:      "+3L",
			Type:        "Blade",
			Special:     "Quick 1",
			Parry:       true,
			Description: "A curved Japanese sword known for its sharpness and cutting power.",
		},
		{
			ID:          uuid.New(),
			Name:        "Heavy Club",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        2500,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+2S/L",
			Type:        "Club",
			Special:     "Blunt",
			Parry:       true,
			Description: "A massive club that can deliver both stunning and lethal damage.",
		},
		{
			ID:          uuid.New(),
			Name:        "Catchpole",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        150,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+0S",
			Type:        "Polearm",
			Special:     "Trapping, Light",
			Parry:       true,
			Description: "A pole with a collar designed to capture and restrain targets.",
		},
		{
			ID:          uuid.New(),
			Name:        "Staff",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        300,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+1S",
			Type:        "Club",
			Special:     "Parrying 1",
			Parry:       true,
			Description: "A simple wooden staff, effective for both attack and defense.",
		},
		{
			ID:          uuid.New(),
			Name:        "Net",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        300,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "0",
			Type:        "Exotic/Wire",
			Special:     "Throwing, Trapping, Light",
			Parry:       false,
			Description: "A weighted net used to entangle and capture targets.",
		},
		{
			ID:          uuid.New(),
			Name:        "Pitchfork",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        400,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+1L",
			Type:        "Polearm",
			Special:     "Parrying 1, Inaccurate -1",
			Parry:       true,
			Description: "A farming tool that can be used as an effective weapon.",
		},
		{
			ID:          uuid.New(),
			Name:        "Trident",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        550,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+3L",
			Type:        "Polearm",
			Special:     "Throwing",
			Parry:       true,
			Description: "A three-pronged spear effective for both thrusting and throwing.",
		},
		{
			ID:          uuid.New(),
			Name:        "Greataxe",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        700,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+4L",
			Type:        "Axe",
			Special:     "Gaping wounds",
			Parry:       true,
			Description: "A massive two-handed axe capable of devastating wounds.",
		},
		{
			ID:          uuid.New(),
			Name:        "Bastard Sword",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        2000,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+3L",
			Type:        "Blade",
			Special:     "1 or 2 handed, Parrying 1, can be quickdrawn by size 5",
			Parry:       true,
			Description: "A versatile sword that can be used one or two-handed.",
		},
		{
			ID:          uuid.New(),
			Name:        "Heavy Mace",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        3000,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+3L",
			Type:        "Club",
			Special:     "Armor piercing 2",
			Parry:       true,
			Description: "A heavy mace designed to crush through armor.",
		},
		{
			ID:          uuid.New(),
			Name:        "Greatsword",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        3000,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+4L",
			Type:        "Blade",
			Special:     "Parrying 1",
			Parry:       true,
			Description: "A massive two-handed sword requiring great strength to wield.",
		},
		{
			ID:          uuid.New(),
			Name:        "Nodachi",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        4000,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "+4L",
			Type:        "Blade",
			Special:     "Area attack +1 target",
			Parry:       true,
			Description: "An extremely long Japanese sword capable of striking multiple targets.",
		},
		{
			ID:          uuid.New(),
			Name:        "Spear",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        4000,
			Rarity:      0,
			Size:        5,
			Weight:      5.0,
			Damage:      "+2L",
			Type:        "Polearm",
			Special:     "1 or 2 Handed, Light",
			Parry:       true,
			Description: "A simple but effective polearm, the weapon of choice for many armies.",
		},
		{
			ID:          uuid.New(),
			Name:        "Cavalry Lance",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        800,
			Rarity:      0,
			Size:        5,
			Weight:      5.0,
			Damage:      "+2L",
			Type:        "Polearm",
			Special:     "Couched",
			Parry:       false,
			Description: "A long lance designed for mounted combat.",
		},
		{
			ID:          uuid.New(),
			Name:        "Halberd/Naginata",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        1200,
			Rarity:      0,
			Size:        5,
			Weight:      5.0,
			Damage:      "+3L",
			Type:        "Polearm",
			Special:     "Tripping, Armor piercing 1",
			Parry:       true,
			Description: "A polearm combining axe, spear, and hook capabilities.",
		},
		{
			ID:          uuid.New(),
			Name:        "Two-Handed Warhammer",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        3500,
			Rarity:      0,
			Size:        5,
			Weight:      5.0,
			Damage:      "+4L",
			Type:        "Club",
			Special:     "Armor piercing 2",
			Parry:       true,
			Description: "A massive hammer requiring two hands to wield effectively.",
		},
		{
			ID:          uuid.New(),
			Name:        "Pike",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Medieval",
			Cost:        4000,
			Rarity:      0,
			Size:        6,
			Weight:      6.0,
			Damage:      "+3L",
			Type:        "Polearm",
			Special:     "Charge stopper, Light",
			Parry:       true,
			Description: "An extremely long spear designed to stop cavalry charges.",
		},
		{
			ID:          uuid.New(),
			Name:        "Improvised Weapon",
			Category:    "Weapon",
			Subcategory: "Melee",
			Era:         "Universal",
			Cost:        0,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Damage:      "+ (Size -2)",
			Type:        "Improvised",
			Special:     "Inaccurate -2, Fragile",
			Parry:       true,
			Description: "Any object used as a weapon, from chairs to broken bottles.",
		},
		// Medieval Armor
		{
			ID:              uuid.New(),
			Name:            "Leather Armor",
			Category:        "Armor",
			Subcategory:     "Body",
			Era:             "Medieval",
			Cost:            200,
			Rarity:          0,
			Size:            3,
			Weight:          3.0,
			Damage:          "",
			ArmorRating:     1,
			BallisticRating: 0,
			Type:            "Soft",
			Special:         "Light",
			Parry:           false,
			Description:     "Light leather armor offering minimal protection but good mobility.",
		},
		{
			ID:              uuid.New(),
			Name:            "Studded Leather",
			Category:        "Armor",
			Subcategory:     "Body",
			Era:             "Medieval",
			Cost:            400,
			Rarity:          0,
			Size:            3,
			Weight:          3.0,
			Damage:          "",
			ArmorRating:     2,
			BallisticRating: 0,
			Type:            "Soft",
			Special:         "Light",
			Parry:           false,
			Description:     "Leather armor reinforced with metal studs for better protection.",
		},
		{
			ID:              uuid.New(),
			Name:            "Chain Shirt",
			Category:        "Armor",
			Subcategory:     "Body",
			Era:             "Medieval",
			Cost:            1000,
			Rarity:          0,
			Size:            3,
			Weight:          3.0,
			Damage:          "",
			ArmorRating:     3,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "Light",
			Parry:           false,
			Description:     "A flexible chain mail shirt covering the torso.",
		},
		{
			ID:              uuid.New(),
			Name:            "Scale Mail",
			Category:        "Armor",
			Subcategory:     "Body",
			Era:             "Medieval",
			Cost:            1500,
			Rarity:          0,
			Size:            4,
			Weight:          4.0,
			Damage:          "",
			ArmorRating:     4,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "",
			Parry:           false,
			Description:     "Armor made of overlapping metal scales sewn to a backing.",
		},
		{
			ID:              uuid.New(),
			Name:            "Chain Hauberk",
			Category:        "Armor",
			Subcategory:     "Body",
			Era:             "Medieval",
			Cost:            2000,
			Rarity:          0,
			Size:            4,
			Weight:          4.0,
			Damage:          "",
			ArmorRating:     4,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "",
			Parry:           false,
			Description:     "A full chain mail suit covering the torso and arms.",
		},
		{
			ID:              uuid.New(),
			Name:            "Breastplate",
			Category:        "Armor",
			Subcategory:     "Body",
			Era:             "Medieval",
			Cost:            3000,
			Rarity:          0,
			Size:            4,
			Weight:          4.0,
			Damage:          "",
			ArmorRating:     5,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "",
			Parry:           false,
			Description:     "A solid metal breastplate protecting the chest and abdomen.",
		},
		{
			ID:              uuid.New(),
			Name:            "Splint Mail",
			Category:        "Armor",
			Subcategory:     "Body",
			Era:             "Medieval",
			Cost:            4000,
			Rarity:          0,
			Size:            5,
			Weight:          5.0,
			Damage:          "",
			ArmorRating:     6,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "",
			Parry:           false,
			Description:     "Heavy armor made of metal strips attached to a leather backing.",
		},
		{
			ID:              uuid.New(),
			Name:            "Banded Mail",
			Category:        "Armor",
			Subcategory:     "Body",
			Era:             "Medieval",
			Cost:            5000,
			Rarity:          0,
			Size:            5,
			Weight:          5.0,
			Damage:          "",
			ArmorRating:     7,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "",
			Parry:           false,
			Description:     "Heavy armor made of overlapping metal bands.",
		},
		{
			ID:              uuid.New(),
			Name:            "Half Plate",
			Category:        "Armor",
			Subcategory:     "Body",
			Era:             "Medieval",
			Cost:            6000,
			Rarity:          0,
			Size:            5,
			Weight:          5.0,
			Damage:          "",
			ArmorRating:     8,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "",
			Parry:           false,
			Description:     "Partial plate armor covering the upper body.",
		},
		{
			ID:              uuid.New(),
			Name:            "Full Plate",
			Category:        "Armor",
			Subcategory:     "Body",
			Era:             "Medieval",
			Cost:            10000,
			Rarity:          0,
			Size:            6,
			Weight:          6.0,
			Damage:          "",
			ArmorRating:     10,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "",
			Parry:           false,
			Description:     "Complete plate armor offering maximum protection.",
		},
		// Medieval Head Armor
		{
			ID:              uuid.New(),
			Name:            "Leather Cap",
			Category:        "Armor",
			Subcategory:     "Head",
			Era:             "Medieval",
			Cost:            50,
			Rarity:          0,
			Size:            1,
			Weight:          1.0,
			Damage:          "",
			ArmorRating:     1,
			BallisticRating: 0,
			Type:            "Soft",
			Special:         "Light",
			Parry:           false,
			Description:     "A simple leather cap offering minimal head protection.",
		},
		{
			ID:              uuid.New(),
			Name:            "Chain Coif",
			Category:        "Armor",
			Subcategory:     "Head",
			Era:             "Medieval",
			Cost:            200,
			Rarity:          0,
			Size:            1,
			Weight:          1.0,
			Damage:          "",
			ArmorRating:     3,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "Light",
			Parry:           false,
			Description:     "A chain mail hood protecting the head and neck.",
		},
		{
			ID:              uuid.New(),
			Name:            "Steel Cap",
			Category:        "Armor",
			Subcategory:     "Head",
			Era:             "Medieval",
			Cost:            500,
			Rarity:          0,
			Size:            1,
			Weight:          1.0,
			Damage:          "",
			ArmorRating:     4,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "",
			Parry:           false,
			Description:     "A simple steel helmet protecting the top of the head.",
		},
		{
			ID:              uuid.New(),
			Name:            "Open Helm",
			Category:        "Armor",
			Subcategory:     "Head",
			Era:             "Medieval",
			Cost:            1000,
			Rarity:          0,
			Size:            1,
			Weight:          1.0,
			Damage:          "",
			ArmorRating:     5,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "",
			Parry:           false,
			Description:     "A helmet with an open face for better visibility.",
		},
		{
			ID:              uuid.New(),
			Name:            "Great Helm",
			Category:        "Armor",
			Subcategory:     "Head",
			Era:             "Medieval",
			Cost:            2000,
			Rarity:          0,
			Size:            1,
			Weight:          1.0,
			Damage:          "",
			ArmorRating:     6,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "Reduced vision",
			Parry:           false,
			Description:     "A fully enclosed helmet offering maximum head protection.",
		},
		// Medieval Arm Armor
		{
			ID:              uuid.New(),
			Name:            "Leather Bracers",
			Category:        "Armor",
			Subcategory:     "Arms",
			Era:             "Medieval",
			Cost:            100,
			Rarity:          0,
			Size:            1,
			Weight:          1.0,
			Damage:          "",
			ArmorRating:     1,
			BallisticRating: 0,
			Type:            "Soft",
			Special:         "Light",
			Parry:           false,
			Description:     "Simple leather protection for the forearms.",
		},
		{
			ID:              uuid.New(),
			Name:            "Chain Sleeves",
			Category:        "Armor",
			Subcategory:     "Arms",
			Era:             "Medieval",
			Cost:            300,
			Rarity:          0,
			Size:            1,
			Weight:          1.0,
			Damage:          "",
			ArmorRating:     3,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "Light",
			Parry:           false,
			Description:     "Chain mail sleeves protecting the arms.",
		},
		{
			ID:              uuid.New(),
			Name:            "Plate Gauntlets",
			Category:        "Armor",
			Subcategory:     "Arms",
			Era:             "Medieval",
			Cost:            500,
			Rarity:          0,
			Size:            1,
			Weight:          1.0,
			Damage:          "",
			ArmorRating:     4,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "",
			Parry:           false,
			Description:     "Metal gauntlets protecting the hands and wrists.",
		},
		// Medieval Leg Armor
		{
			ID:              uuid.New(),
			Name:            "Leather Greaves",
			Category:        "Armor",
			Subcategory:     "Legs",
			Era:             "Medieval",
			Cost:            150,
			Rarity:          0,
			Size:            1,
			Weight:          1.0,
			Damage:          "",
			ArmorRating:     1,
			BallisticRating: 0,
			Type:            "Soft",
			Special:         "Light",
			Parry:           false,
			Description:     "Leather protection for the lower legs.",
		},
		{
			ID:              uuid.New(),
			Name:            "Chain Chausses",
			Category:        "Armor",
			Subcategory:     "Legs",
			Era:             "Medieval",
			Cost:            400,
			Rarity:          0,
			Size:            1,
			Weight:          1.0,
			Damage:          "",
			ArmorRating:     3,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "Light",
			Parry:           false,
			Description:     "Chain mail leggings protecting the legs.",
		},
		{
			ID:              uuid.New(),
			Name:            "Plate Greaves",
			Category:        "Armor",
			Subcategory:     "Legs",
			Era:             "Medieval",
			Cost:            600,
			Rarity:          0,
			Size:            1,
			Weight:          1.0,
			Damage:          "",
			ArmorRating:     4,
			BallisticRating: 0,
			Type:            "Hard",
			Special:         "",
			Parry:           false,
			Description:     "Metal greaves protecting the lower legs.",
		},
		// Industrial Era Armor
		{
			ID:              uuid.New(),
			Name:            "Kevlar Vest",
			Category:        "Armor",
			Subcategory:     "Body",
			Era:             "Industrial",
			Cost:            5000,
			Rarity:          1,
			Size:            2,
			Weight:          2.0,
			Damage:          "",
			ArmorRating:     2,
			BallisticRating: 4,
			Type:            "Soft",
			Special:         "Light",
			Parry:           false,
			Description:     "Modern body armor made of Kevlar fibers.",
		},
		{
			ID:              uuid.New(),
			Name:            "Tactical Vest",
			Category:        "Armor",
			Subcategory:     "Body",
			Era:             "Industrial",
			Cost:            8000,
			Rarity:          2,
			Size:            3,
			Weight:          3.0,
			Damage:          "",
			ArmorRating:     3,
			BallisticRating: 6,
			Type:            "Hard",
			Special:         "",
			Parry:           false,
			Description:     "Military-grade body armor with ballistic plates.",
		},
		{
			ID:              uuid.New(),
			Name:            "Combat Helmet",
			Category:        "Armor",
			Subcategory:     "Head",
			Era:             "Industrial",
			Cost:            2000,
			Rarity:          1,
			Size:            1,
			Weight:          1.0,
			Damage:          "",
			ArmorRating:     2,
			BallisticRating: 3,
			Type:            "Hard",
			Special:         "",
			Parry:           false,
			Description:     "Modern military helmet with ballistic protection.",
		},
		// Cyber Era Armor
		{
			ID:              uuid.New(),
			Name:            "Smart Armor",
			Category:        "Armor",
			Subcategory:     "Body",
			Era:             "Cyber",
			Cost:            15000,
			Rarity:          3,
			Size:            2,
			Weight:          2.0,
			Damage:          "",
			ArmorRating:     4,
			BallisticRating: 8,
			Type:            "Hard",
			Special:         "Light, Smart",
			Parry:           false,
			Description:     "Advanced armor with integrated smart systems.",
		},
		{
			ID:              uuid.New(),
			Name:            "Combat Suit",
			Category:        "Armor",
			Subcategory:     "Body",
			Era:             "Cyber",
			Cost:            25000,
			Rarity:          4,
			Size:            3,
			Weight:          3.0,
			Damage:          "",
			ArmorRating:     6,
			BallisticRating: 10,
			Type:            "Hard",
			Special:         "Smart, Stealth",
			Parry:           false,
			Description:     "Full-body combat armor with advanced protection systems.",
		},
		{
			ID:              uuid.New(),
			Name:            "Neural Helmet",
			Category:        "Armor",
			Subcategory:     "Head",
			Era:             "Cyber",
			Cost:            8000,
			Rarity:          3,
			Size:            1,
			Weight:          1.0,
			Damage:          "",
			ArmorRating:     3,
			BallisticRating: 5,
			Type:            "Hard",
			Special:         "Smart, Neural Interface",
			Parry:           false,
			Description:     "Advanced helmet with neural interface capabilities.",
		},
		// Medieval Ranged Weapons
		{
			ID:          uuid.New(),
			Name:        "Sling",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Medieval",
			Cost:        100,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Damage:      "+1L/+1S",
			Type:        "Throwing",
			Special:     "Blunt",
			Parry:       false,
			Description: "A simple sling for throwing stones or metal balls.",
		},
		{
			ID:          uuid.New(),
			Name:        "Blow Gun",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Medieval",
			Cost:        300,
			Rarity:      3,
			Size:        2,
			Weight:      2.0,
			Damage:      "0",
			Type:        "Exotic",
			Special:     "Injector, Slow reload 1 complex",
			Parry:       false,
			Description: "A tube for blowing darts, often poisoned.",
		},
		{
			ID:          uuid.New(),
			Name:        "Short Bow",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Medieval",
			Cost:        500,
			Rarity:      0,
			Size:        3,
			Weight:      3.0,
			Damage:      "5+(brawn/2)L",
			Type:        "Bow",
			Special:     "Quick 1",
			Parry:       false,
			Description: "A compact bow suitable for hunting and combat.",
		},
		{
			ID:          uuid.New(),
			Name:        "Crossbow (Hand)",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Medieval",
			Cost:        700,
			Rarity:      2,
			Size:        2,
			Weight:      2.0,
			Damage:      "5L",
			Type:        "Crossbow",
			Special:     "Armor piercing 1",
			Parry:       false,
			Description: "A small crossbow that can be used one-handed.",
		},
		{
			ID:          uuid.New(),
			Name:        "Longbow",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Medieval",
			Cost:        800,
			Rarity:      0,
			Size:        5,
			Weight:      5.0,
			Damage:      "6+(brawn/2)L",
			Type:        "Bow",
			Special:     "Longshot",
			Parry:       false,
			Description: "A powerful bow with excellent range and accuracy.",
		},
		{
			ID:          uuid.New(),
			Name:        "Yumi",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Medieval",
			Cost:        1000,
			Rarity:      0,
			Size:        6,
			Weight:      6.0,
			Damage:      "7+(brawn/2)L",
			Type:        "Bow",
			Special:     "Longshot",
			Parry:       false,
			Description: "A Japanese longbow known for its power and accuracy.",
		},
		{
			ID:          uuid.New(),
			Name:        "Crossbow (Light)",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Medieval",
			Cost:        1000,
			Rarity:      0,
			Size:        3,
			Weight:      3.0,
			Damage:      "6L",
			Type:        "Crossbow",
			Special:     "Armor Piercing 2",
			Parry:       false,
			Description: "A standard crossbow with good armor penetration.",
		},
		{
			ID:          uuid.New(),
			Name:        "Crossbow (Heavy)",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Medieval",
			Cost:        1400,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Damage:      "8L",
			Type:        "Crossbow",
			Special:     "Armor piercing 3, Slow reload: 1 Complex",
			Parry:       false,
			Description: "A powerful crossbow requiring strength to reload.",
		},
		{
			ID:          uuid.New(),
			Name:        "Crossbow (Repeating)",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Medieval",
			Cost:        2000,
			Rarity:      6,
			Size:        4,
			Weight:      4.0,
			Damage:      "6L",
			Type:        "Crossbow",
			Special:     "Armor piercing 1, Slow reload: 1 Complex",
			Parry:       false,
			Description: "A crossbow with a magazine for multiple shots.",
		},
		{
			ID:          uuid.New(),
			Name:        "Scorpion/Light Ballista",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Medieval",
			Cost:        12000,
			Rarity:      8,
			Size:        7,
			Weight:      7.0,
			Damage:      "16L",
			Type:        "Heavy",
			Special:     "Armor Piercing 4, Slow reload 2 Complex, Inaccurate -4",
			Parry:       false,
			Description: "A massive siege weapon for anti-armor combat.",
		},
		// Industrial Era Ranged Weapons
		{
			ID:          uuid.New(),
			Name:        "Derringer",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Industrial",
			Cost:        1000,
			Rarity:      0,
			Size:        0,
			Weight:      0.5,
			Damage:      "5L",
			Type:        "Pistol",
			Special:     "Ballistic, Slow reload: 1 Complex, Concealed, Inaccurate: -2",
			Parry:       false,
			Description: "A small, easily concealed pistol.",
		},
		{
			ID:          uuid.New(),
			Name:        "Powder Pistol",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Industrial",
			Cost:        1500,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "8L",
			Type:        "Pistol",
			Special:     "Ballistic, Slow reload: 1 Complex, Inaccurate -2",
			Parry:       false,
			Description: "A black powder pistol requiring manual reloading.",
		},
		{
			ID:          uuid.New(),
			Name:        "Double Barrelled Pistol",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Industrial",
			Cost:        1800,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "8L",
			Type:        "Pistol",
			Special:     "Ballistic, Slow reload: 1 Complex, Inaccurate -2",
			Parry:       false,
			Description: "A pistol with two barrels for two shots.",
		},
		{
			ID:          uuid.New(),
			Name:        "Dragon (1 handed blunderbuss)",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Industrial",
			Cost:        2000,
			Rarity:      3,
			Size:        3,
			Weight:      3.0,
			Damage:      "9L",
			Type:        "Pistol",
			Special:     "Ballistic, Slow reload: 1 Complex, Inaccurate -2, Area:Engaged",
			Parry:       false,
			Description: "A hand-held blunderbuss for close-range devastation.",
		},
		{
			ID:          uuid.New(),
			Name:        "Duck Foot Pistol",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Industrial",
			Cost:        1500,
			Rarity:      0,
			Size:        3,
			Weight:      3.0,
			Damage:      "8L",
			Type:        "Pistol",
			Special:     "Ballistic, Slow reload: 2 Complex, Inaccurate -3, Area: Engaged",
			Parry:       false,
			Description: "A multi-barreled pistol firing in a spread pattern.",
		},
		{
			ID:          uuid.New(),
			Name:        "Musket",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Industrial",
			Cost:        3000,
			Rarity:      0,
			Size:        5,
			Weight:      5.0,
			Damage:      "10L",
			Type:        "Longarm",
			Special:     "Ballistic, Slow reload: 2 Complex, Inaccurate -2",
			Parry:       false,
			Description: "A long-barreled black powder rifle.",
		},
		{
			ID:          uuid.New(),
			Name:        "Blunderbuss",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Industrial",
			Cost:        3000,
			Rarity:      3,
			Size:        4,
			Weight:      4.0,
			Damage:      "10L",
			Type:        "Longarm",
			Special:     "Ballistic, Slow reload: 2 Complex, Inaccurate -2, Area:Engaged",
			Parry:       false,
			Description: "A shotgun-like weapon firing multiple projectiles.",
		},
		{
			ID:          uuid.New(),
			Name:        "Field Cannon (Light)",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Industrial",
			Cost:        20000,
			Rarity:      6,
			Size:        7,
			Weight:      7.0,
			Damage:      "20L",
			Type:        "Heavy",
			Special:     "Ballistic, Slow reload: 4 Complex, Inaccurate -4, Immobile",
			Parry:       false,
			Description: "A portable artillery piece for battlefield use.",
		},
		// Cyber Era Ranged Weapons
		{
			ID:          uuid.New(),
			Name:        "Spray (Small)",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        150,
			Rarity:      0,
			Size:        0,
			Weight:      0.5,
			Damage:      "0",
			Type:        "Tool",
			Special:     "Spray",
			Parry:       false,
			Description: "A small spray device for chemicals or paint.",
		},
		{
			ID:          uuid.New(),
			Name:        "Spray (Large)",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        200,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Damage:      "0",
			Type:        "Tool",
			Special:     "Spray, Area Engaged",
			Parry:       false,
			Description: "A large spray device for area coverage.",
		},
		{
			ID:          uuid.New(),
			Name:        "Taser Gun",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        300,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Damage:      "6S",
			Type:        "Pistol",
			Special:     "Shocking",
			Parry:       false,
			Description: "A non-lethal weapon that delivers electric shocks.",
		},
		{
			ID:          uuid.New(),
			Name:        "Revolver (Light)",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        450,
			Rarity:      2,
			Size:        1,
			Weight:      1.0,
			Damage:      "6L",
			Type:        "Pistol",
			Special:     "Ballistic",
			Parry:       false,
			Description: "A lightweight revolver with good reliability.",
		},
		{
			ID:          uuid.New(),
			Name:        "Pistol (Holdout)",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        500,
			Rarity:      2,
			Size:        0,
			Weight:      0.5,
			Damage:      "5L",
			Type:        "Pistol",
			Special:     "Ballistic, Concealed",
			Parry:       false,
			Description: "A tiny pistol designed to be easily hidden.",
		},
		{
			ID:          uuid.New(),
			Name:        "Pistol (Dart)",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        500,
			Rarity:      3,
			Size:        1,
			Weight:      1.0,
			Damage:      "0",
			Type:        "Pistol",
			Special:     "Injector",
			Parry:       false,
			Description: "A pistol that fires tranquilizer darts.",
		},
		{
			ID:          uuid.New(),
			Name:        "Pistol (Light)",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        550,
			Rarity:      2,
			Size:        1,
			Weight:      1.0,
			Damage:      "6L",
			Type:        "Pistol",
			Special:     "Ballistic, Quick 1",
			Parry:       false,
			Description: "A standard semi-automatic pistol.",
		},
		{
			ID:          uuid.New(),
			Name:        "Revolver (Heavy)",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        750,
			Rarity:      2,
			Size:        2,
			Weight:      2.0,
			Damage:      "8L",
			Type:        "Pistol",
			Special:     "Ballistic",
			Parry:       false,
			Description: "A powerful revolver with high stopping power.",
		},
		{
			ID:          uuid.New(),
			Name:        "Pistol (Heavy)",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        850,
			Rarity:      2,
			Size:        2,
			Weight:      2.0,
			Damage:      "7L",
			Type:        "Pistol",
			Special:     "Ballistic",
			Parry:       false,
			Description: "A heavy semi-automatic pistol with good damage.",
		},
		{
			ID:          uuid.New(),
			Name:        "Shotgun (Double Barrel)",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        1000,
			Rarity:      2,
			Size:        4,
			Weight:      4.0,
			Damage:      "10L",
			Type:        "Longarm",
			Special:     "Ballistic",
			Parry:       false,
			Description: "A classic double-barreled shotgun.",
		},
		{
			ID:          uuid.New(),
			Name:        "Pistol (Burst-capable)",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        1500,
			Rarity:      3,
			Size:        2,
			Weight:      2.0,
			Damage:      "5L",
			Type:        "Pistol",
			Special:     "Ballistic",
			Parry:       false,
			Description: "A pistol capable of burst fire mode.",
		},
		{
			ID:          uuid.New(),
			Name:        "Shotgun (Pump-action)",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        2000,
			Rarity:      2,
			Size:        4,
			Weight:      4.0,
			Damage:      "10L",
			Type:        "Longarm",
			Special:     "Ballistic",
			Parry:       false,
			Description: "A pump-action shotgun with good reliability.",
		},
		{
			ID:          uuid.New(),
			Name:        "Rifle (Hunting)",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        2000,
			Rarity:      2,
			Size:        5,
			Weight:      5.0,
			Damage:      "11L",
			Type:        "Longarm",
			Special:     "Ballistic",
			Parry:       false,
			Description: "A hunting rifle with good accuracy and range.",
		},
		{
			ID:          uuid.New(),
			Name:        "Shotgun (Combat)",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        3000,
			Rarity:      4,
			Size:        4,
			Weight:      4.0,
			Damage:      "10L",
			Type:        "Longarm",
			Special:     "Ballistic",
			Parry:       false,
			Description: "A combat shotgun designed for tactical use.",
		},
		{
			ID:          uuid.New(),
			Name:        "Machine Pistol",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        3000,
			Rarity:      4,
			Size:        2,
			Weight:      2.0,
			Damage:      "5L",
			Type:        "Automatic",
			Special:     "Ballistic",
			Parry:       false,
			Description: "A compact automatic weapon with high rate of fire.",
		},
		{
			ID:          uuid.New(),
			Name:        "Shotgun (Automatic)",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        4000,
			Rarity:      4,
			Size:        4,
			Weight:      4.0,
			Damage:      "9L",
			Type:        "Longarm",
			Special:     "Ballistic",
			Parry:       false,
			Description: "An automatic shotgun for rapid fire.",
		},
		{
			ID:          uuid.New(),
			Name:        "Rifle (Sniper)",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        6000,
			Rarity:      4,
			Size:        5,
			Weight:      5.0,
			Damage:      "13L",
			Type:        "Longarm",
			Special:     "Ballistic",
			Parry:       false,
			Description: "A precision rifle designed for long-range accuracy.",
		},
		{
			ID:          uuid.New(),
			Name:        "Grenade Launcher (Single)",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        6000,
			Rarity:      6,
			Size:        3,
			Weight:      3.0,
			Damage:      "Grenade",
			Type:        "Heavy",
			Special:     "Ballistic",
			Parry:       false,
			Description: "A single-shot grenade launcher for explosive rounds.",
		},
		{
			ID:          uuid.New(),
			Name:        "Flamethrower (Light)",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        8000,
			Rarity:      6,
			Size:        4,
			Weight:      4.0,
			Damage:      "8L",
			Type:        "Heavy",
			Special:     "Flaming",
			Parry:       false,
			Description: "A portable flamethrower for area denial.",
		},
		{
			ID:          uuid.New(),
			Name:        "Submachine Gun",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        8000,
			Rarity:      4,
			Size:        3,
			Weight:      3.0,
			Damage:      "8L",
			Type:        "Automatic",
			Special:     "Ballistic",
			Parry:       false,
			Description: "A compact automatic weapon for close combat.",
		},
		{
			ID:          uuid.New(),
			Name:        "Laser Rifle",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        10000,
			Rarity:      8,
			Size:        5,
			Weight:      5.0,
			Damage:      "10L",
			Type:        "Longarm",
			Special:     "Ballistic, Armor wrecker 1",
			Parry:       false,
			Description: "An advanced energy weapon with armor-piercing capabilities.",
		},
		{
			ID:          uuid.New(),
			Name:        "Assault Rifle",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        12000,
			Rarity:      4,
			Size:        4,
			Weight:      4.0,
			Damage:      "10L",
			Type:        "Automatic",
			Special:     "Ballistic",
			Parry:       false,
			Description: "A versatile automatic rifle for military use.",
		},
		{
			ID:          uuid.New(),
			Name:        "Rifle (Anti-Material)",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        20000,
			Rarity:      6,
			Size:        6,
			Weight:      6.0,
			Damage:      "14L",
			Type:        "Longarm",
			Special:     "Ballistic, Armor piercing 2",
			Parry:       false,
			Description: "A heavy rifle designed to penetrate armor and vehicles.",
		},
		{
			ID:          uuid.New(),
			Name:        "Machine Gun (Light)",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        16000,
			Rarity:      6,
			Size:        5,
			Weight:      5.0,
			Damage:      "10L",
			Type:        "Heavy",
			Special:     "Ballistic, Slow reload: 1 complex",
			Parry:       false,
			Description: "A portable machine gun for sustained fire support.",
		},
		{
			ID:          uuid.New(),
			Name:        "Assault Cannon",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        25000,
			Rarity:      8,
			Size:        6,
			Weight:      6.0,
			Damage:      "15L",
			Type:        "Heavy",
			Special:     "Ballistic, Armor Wrecker: 1",
			Parry:       false,
			Description: "A heavy automatic weapon for anti-vehicle combat.",
		},
		{
			ID:          uuid.New(),
			Name:        "Flamethrower (Heavy)",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        18000,
			Rarity:      8,
			Size:        6,
			Weight:      6.0,
			Damage:      "8L",
			Type:        "Heavy",
			Special:     "Flaming, Slow reload 2 Complex",
			Parry:       false,
			Description: "A heavy flamethrower for area denial and clearing.",
		},
		{
			ID:          uuid.New(),
			Name:        "Rocket/Missile Launcher",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        30000,
			Rarity:      8,
			Size:        6,
			Weight:      6.0,
			Damage:      "Rocket",
			Type:        "Heavy",
			Special:     "Ballistic, Slow reload: 1 Complex",
			Parry:       false,
			Description: "A heavy weapon for launching explosive projectiles.",
		},
		{
			ID:          uuid.New(),
			Name:        "Machine Gun (Heavy)",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        24000,
			Rarity:      6,
			Size:        6,
			Weight:      6.0,
			Damage:      "11L",
			Type:        "Heavy",
			Special:     "Ballistic, Slow reload: 1 Complex (box), 2 Complex (belt)",
			Parry:       false,
			Description: "A heavy machine gun for sustained fire support.",
		},
		{
			ID:          uuid.New(),
			Name:        "Grenade Launcher",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        18000,
			Rarity:      6,
			Size:        4,
			Weight:      4.0,
			Damage:      "Grenade",
			Type:        "Heavy",
			Special:     "Ballistic",
			Parry:       false,
			Description: "A multi-shot grenade launcher for explosive support.",
		},
		{
			ID:          uuid.New(),
			Name:        "Laser Heavy",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        40000,
			Rarity:      9,
			Size:        6,
			Weight:      6.0,
			Damage:      "11L",
			Type:        "Heavy",
			Special:     "Ballistic, Armor wrecker 2, Slow reload: complex",
			Parry:       false,
			Description: "A heavy energy weapon with devastating armor-piercing capabilities.",
		},
		{
			ID:          uuid.New(),
			Name:        "Railgun",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        50000,
			Rarity:      10,
			Size:        5,
			Weight:      5.0,
			Damage:      "18L",
			Type:        "Longarm",
			Special:     "Ballistic, Slow reload: 1 complex, 3 Armor piercing",
			Parry:       false,
			Description: "An advanced weapon using magnetic acceleration for extreme penetration.",
		},
		{
			ID:          uuid.New(),
			Name:        "Rocket/Missile Launcher (Single Use)",
			Category:    "Weapon",
			Subcategory: "Ranged",
			Era:         "Cyber",
			Cost:        1000,
			Rarity:      7,
			Size:        5,
			Weight:      5.0,
			Damage:      "Rocket",
			Type:        "Heavy",
			Special:     "Ballistic",
			Parry:       false,
			Description: "A disposable rocket launcher for one-time use.",
		},
	}
}
