package seeds

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type PersonalEquipment struct {
	ID          uuid.UUID `gorm:"type:uuid;primary_key;default:gen_random_uuid()"`
	Name        string    `gorm:"not null"`
	Category    string    `gorm:"not null"` // Carry, Light, Tools, Vision, Communication, Electronics, Clothing, Living, Restraint, Magical aid
	Subcategory string    `gorm:"not null"` // Medieval, Industrial, Cyber
	Era         string    `gorm:"not null"` // Medieval, Industrial, Cyber
	Cost        int       `gorm:"not null"`
	Rarity      int       `gorm:"not null"` // 0=Civilian, 1-3=Restricted, 4-5=Military
	Size        int       `gorm:"not null"`
	Weight      float64   `gorm:"not null"`
	Type        string    `gorm:"default:''"` // Specific type within category
	Special     string    `gorm:"default:''"` // Special properties and effects
	Capacity    int       `gorm:"default:0"`  // For items with capacity (programs, IC, etc.)
	Rating      int       `gorm:"default:0"`  // For items with ratings
	Description string    `gorm:"default:''"`
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (PersonalEquipment) TableName() string {
	return "personal_equipment"
}

func SeedPersonalEquipment(db *gorm.DB) error {
	var count int64
	db.Model(&PersonalEquipment{}).Count(&count)
	if count > 0 {
		return nil // Already seeded
	}

	equipment := GetPersonalEquipment()
	return db.Create(&equipment).Error
}

func GetPersonalEquipment() []PersonalEquipment {
	return []PersonalEquipment{
		// Medieval Era Personal Equipment
		{
			ID:          uuid.New(),
			Name:        "Backpack",
			Category:    "Carry",
			Subcategory: "Storage",
			Era:         "Medieval",
			Cost:        400,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Type:        "Storage",
			Special:     "No encumbrance cost, adds char-size to carry cap",
			Description: "A sturdy backpack for carrying equipment and supplies.",
		},
		{
			ID:          uuid.New(),
			Name:        "Quiver (Hip)",
			Category:    "Carry",
			Subcategory: "Ammunition",
			Era:         "Medieval",
			Cost:        150,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Type:        "Ammunition",
			Special:     "10 Arrows/Bolts",
			Description: "A hip quiver for carrying arrows or crossbow bolts.",
		},
		{
			ID:          uuid.New(),
			Name:        "Quiver (Back)",
			Category:    "Carry",
			Subcategory: "Ammunition",
			Era:         "Medieval",
			Cost:        200,
			Rarity:      0,
			Size:        3,
			Weight:      3.0,
			Type:        "Ammunition",
			Special:     "20 Arrows/Bolts",
			Description: "A back quiver for carrying more arrows or crossbow bolts.",
		},
		{
			ID:          uuid.New(),
			Name:        "Bandoleer",
			Category:    "Carry",
			Subcategory: "Storage",
			Era:         "Medieval",
			Cost:        200,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Type:        "Storage",
			Special:     "Quickdraw up to 4 total size",
			Description: "A bandoleer for quick access to small items and ammunition.",
		},
		{
			ID:          uuid.New(),
			Name:        "Torch",
			Category:    "Light",
			Subcategory: "Illumination",
			Era:         "Medieval",
			Cost:        20,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Type:        "Illumination",
			Special:     "30 min dim light",
			Description: "A simple torch providing dim light for 30 minutes.",
		},
		{
			ID:          uuid.New(),
			Name:        "Lantern",
			Category:    "Light",
			Subcategory: "Illumination",
			Era:         "Medieval",
			Cost:        300,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Type:        "Illumination",
			Special:     "3 hours light",
			Description: "A lantern providing bright light for 3 hours.",
		},
		{
			ID:          uuid.New(),
			Name:        "Tool Kit",
			Category:    "Tools",
			Subcategory: "Crafting",
			Era:         "Medieval",
			Cost:        2000,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Type:        "Crafting",
			Special:     "Different toolkits for different use",
			Description: "A comprehensive toolkit for various crafting and repair tasks.",
		},
		{
			ID:          uuid.New(),
			Name:        "Spy Glass",
			Category:    "Vision",
			Subcategory: "Optics",
			Era:         "Medieval",
			Cost:        1500,
			Rarity:      0,
			Size:        0,
			Weight:      0.5,
			Type:        "Optics",
			Special:     "Half vision penalty for range",
			Description: "A telescopic lens for viewing distant objects.",
		},
		{
			ID:          uuid.New(),
			Name:        "Coin Pouch",
			Category:    "Carry",
			Subcategory: "Storage",
			Era:         "Medieval",
			Cost:        5,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Type:        "Storage",
			Special:     "Hold up to 50 coins",
			Description: "A small pouch for carrying coins and small valuables.",
		},
		{
			ID:          uuid.New(),
			Name:        "Thieves Tools",
			Category:    "Tools",
			Subcategory: "Security",
			Era:         "Medieval",
			Cost:        1000,
			Rarity:      3,
			Size:        1,
			Weight:      1.0,
			Type:        "Security",
			Special:     "Lockpicking and trap disarming",
			Description: "Specialized tools for picking locks and disarming traps.",
		},
		{
			ID:          uuid.New(),
			Name:        "First Aid Kit",
			Category:    "Tools",
			Subcategory: "Medical",
			Era:         "Medieval",
			Cost:        500,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Type:        "Medical",
			Special:     "Basic medical supplies and bandages",
			Description: "A kit containing basic medical supplies for treating wounds.",
		},
		{
			ID:          uuid.New(),
			Name:        "Rope",
			Category:    "Restraint",
			Subcategory: "Binding",
			Era:         "Medieval",
			Cost:        100,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Type:        "Binding",
			Special:     "General purpose rope",
			Description: "Sturdy rope useful for climbing, binding, or securing items.",
		},
		{
			ID:          uuid.New(),
			Name:        "Chain",
			Category:    "Restraint",
			Subcategory: "Binding",
			Era:         "Medieval",
			Cost:        300,
			Rarity:      0,
			Size:        3,
			Weight:      3.0,
			Type:        "Binding",
			Special:     "Escape: Agility: 4, Brawn: 8",
			Description: "Heavy chain for binding prisoners or securing objects.",
		},
		{
			ID:          uuid.New(),
			Name:        "Manacles",
			Category:    "Restraint",
			Subcategory: "Binding",
			Era:         "Medieval",
			Cost:        500,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Type:        "Binding",
			Special:     "Escape: Agility: 6, Brawn: 8",
			Description: "Metal restraints for binding hands or feet.",
		},
		{
			ID:          uuid.New(),
			Name:        "Clothing (Fine)",
			Category:    "Clothing",
			Subcategory: "Apparel",
			Era:         "Medieval",
			Cost:        500,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Type:        "Apparel",
			Special:     "Light, Lifestyle: Decent+",
			Description: "Fine quality clothing suitable for formal occasions.",
		},
		{
			ID:          uuid.New(),
			Name:        "Clothing (Cold Weather)",
			Category:    "Clothing",
			Subcategory: "Apparel",
			Era:         "Medieval",
			Cost:        250,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Type:        "Apparel",
			Special:     "Light, Lifestyle: Decent+",
			Description: "Warm clothing designed for cold weather conditions.",
		},
		{
			ID:          uuid.New(),
			Name:        "Clothing (Hot Weather)",
			Category:    "Clothing",
			Subcategory: "Apparel",
			Era:         "Medieval",
			Cost:        200,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Type:        "Apparel",
			Special:     "Light, Lifestyle: Decent+",
			Description: "Light, breathable clothing for hot weather.",
		},
		{
			ID:          uuid.New(),
			Name:        "Clothing (Rain)",
			Category:    "Clothing",
			Subcategory: "Apparel",
			Era:         "Medieval",
			Cost:        200,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Type:        "Apparel",
			Special:     "Light, Lifestyle: Decent+",
			Description: "Waterproof clothing for protection against rain.",
		},
		{
			ID:          uuid.New(),
			Name:        "Mirror",
			Category:    "Vision",
			Subcategory: "Optics",
			Era:         "Medieval",
			Cost:        300,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Type:        "Optics",
			Special:     "Reflective surface",
			Description: "A polished mirror for reflection and signaling.",
		},
		{
			ID:          uuid.New(),
			Name:        "Tent (Small)",
			Category:    "Living",
			Subcategory: "Shelter",
			Era:         "Medieval",
			Cost:        500,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Type:        "Shelter",
			Special:     "Light",
			Description: "A small tent for one or two people.",
		},
		{
			ID:          uuid.New(),
			Name:        "Tent (Medium)",
			Category:    "Living",
			Subcategory: "Shelter",
			Era:         "Medieval",
			Cost:        800,
			Rarity:      0,
			Size:        6,
			Weight:      6.0,
			Type:        "Shelter",
			Special:     "Light",
			Description: "A medium tent for a small group.",
		},
		{
			ID:          uuid.New(),
			Name:        "Tent (Large)",
			Category:    "Living",
			Subcategory: "Shelter",
			Era:         "Medieval",
			Cost:        1200,
			Rarity:      0,
			Size:        8,
			Weight:      8.0,
			Type:        "Shelter",
			Special:     "Light",
			Description: "A large tent for a group or family.",
		},
		{
			ID:          uuid.New(),
			Name:        "Tent (Luxury)",
			Category:    "Living",
			Subcategory: "Shelter",
			Era:         "Medieval",
			Cost:        3000,
			Rarity:      0,
			Size:        10,
			Weight:      10.0,
			Type:        "Shelter",
			Special:     "Light",
			Description: "A luxurious tent with extra comforts and space.",
		},
		{
			ID:          uuid.New(),
			Name:        "Rations",
			Category:    "Living",
			Subcategory: "Food",
			Era:         "Medieval",
			Cost:        50,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Type:        "Food",
			Special:     "For 1 day, Lifestyle: poor+",
			Description: "Preserved food sufficient for one day of travel.",
		},
		{
			ID:          uuid.New(),
			Name:        "Rope Ladder",
			Category:    "Tools",
			Subcategory: "Climbing",
			Era:         "Medieval",
			Cost:        250,
			Rarity:      0,
			Size:        3,
			Weight:      3.0,
			Type:        "Climbing",
			Special:     "Climb +2 ignores penalties for wall condition",
			Description: "A portable ladder made of rope and wooden rungs.",
		},
		// Cyber Era Personal Equipment
		{
			ID:          uuid.New(),
			Name:        "Comlink (Average)",
			Category:    "Communication",
			Subcategory: "Electronics",
			Era:         "Cyber",
			Cost:        500,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Type:        "Communication",
			Special:     "IC: 5, Programs: 2",
			Capacity:    2,
			Rating:      5,
			Description: "A standard communication device with basic programs.",
		},
		{
			ID:          uuid.New(),
			Name:        "Comlink (Cheap)",
			Category:    "Communication",
			Subcategory: "Electronics",
			Era:         "Cyber",
			Cost:        100,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Type:        "Communication",
			Special:     "IC: 3, Programs: 1",
			Capacity:    1,
			Rating:      3,
			Description: "A basic communication device with minimal features.",
		},
		{
			ID:          uuid.New(),
			Name:        "Comlink (Top of the line)",
			Category:    "Communication",
			Subcategory: "Electronics",
			Era:         "Cyber",
			Cost:        1500,
			Rarity:      3,
			Size:        1,
			Weight:      1.0,
			Type:        "Communication",
			Special:     "IC: 7, Programs: 3",
			Capacity:    3,
			Rating:      7,
			Description: "A high-end communication device with advanced features.",
		},
		{
			ID:          uuid.New(),
			Name:        "Headset",
			Category:    "Communication",
			Subcategory: "Electronics",
			Era:         "Cyber",
			Cost:        150,
			Rarity:      0,
			Size:        0,
			Weight:      0.5,
			Type:        "Communication",
			Special:     "Audio communication",
			Description: "A headset for hands-free communication.",
		},
		{
			ID:          uuid.New(),
			Name:        "Microtransiever",
			Category:    "Communication",
			Subcategory: "Electronics",
			Era:         "Cyber",
			Cost:        300,
			Rarity:      0,
			Size:        0,
			Weight:      0.5,
			Type:        "Communication",
			Special:     "Radio",
			Description: "A small radio transceiver for communication.",
		},
		{
			ID:          uuid.New(),
			Name:        "Credit Chip",
			Category:    "Electronics",
			Subcategory: "Financial",
			Era:         "Cyber",
			Cost:        20,
			Rarity:      0,
			Size:        0,
			Weight:      0.1,
			Type:        "Financial",
			Special:     "Digital currency storage",
			Description: "A digital chip for storing and transferring credits.",
		},
		{
			ID:          uuid.New(),
			Name:        "Cyberdeck (Average)",
			Category:    "Electronics",
			Subcategory: "Computing",
			Era:         "Cyber",
			Cost:        9000,
			Rarity:      4,
			Size:        2,
			Weight:      2.0,
			Type:        "Computing",
			Special:     "IC: 6, Programs: 4",
			Capacity:    4,
			Rating:      6,
			Description: "A standard cyberdeck for hacking and computing tasks.",
		},
		{
			ID:          uuid.New(),
			Name:        "Cyberdeck (Cheap)",
			Category:    "Electronics",
			Subcategory: "Computing",
			Era:         "Cyber",
			Cost:        3000,
			Rarity:      2,
			Size:        2,
			Weight:      2.0,
			Type:        "Computing",
			Special:     "IC: 4, Programs: 2",
			Capacity:    2,
			Rating:      4,
			Description: "A basic cyberdeck with limited capabilities.",
		},
		{
			ID:          uuid.New(),
			Name:        "Cyberdeck (Top of the line)",
			Category:    "Electronics",
			Subcategory: "Computing",
			Era:         "Cyber",
			Cost:        15000,
			Rarity:      6,
			Size:        2,
			Weight:      2.0,
			Type:        "Computing",
			Special:     "IC: 8, Programs: 6",
			Capacity:    6,
			Rating:      8,
			Description: "A high-end cyberdeck with maximum capabilities.",
		},
		{
			ID:          uuid.New(),
			Name:        "Cyber Terminal (Cheap)",
			Category:    "Electronics",
			Subcategory: "Computing",
			Era:         "Cyber",
			Cost:        1500,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Type:        "Computing",
			Special:     "Immobile, IC: 4, Programs: 2",
			Capacity:    2,
			Rating:      4,
			Description: "A basic stationary computer terminal.",
		},
		{
			ID:          uuid.New(),
			Name:        "Cyber Terminal (Average)",
			Category:    "Electronics",
			Subcategory: "Computing",
			Era:         "Cyber",
			Cost:        4500,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Type:        "Computing",
			Special:     "Immobile, IC: 6, Programs: 4",
			Capacity:    4,
			Rating:      6,
			Description: "A standard stationary computer terminal.",
		},
		{
			ID:          uuid.New(),
			Name:        "Cyber Terminal (Top of the line)",
			Category:    "Electronics",
			Subcategory: "Computing",
			Era:         "Cyber",
			Cost:        7500,
			Rarity:      3,
			Size:        4,
			Weight:      4.0,
			Type:        "Computing",
			Special:     "Immobile, IC: 8, Programs: 6",
			Capacity:    6,
			Rating:      8,
			Description: "A high-end stationary computer terminal.",
		},
		{
			ID:          uuid.New(),
			Name:        "Data Card",
			Category:    "Electronics",
			Subcategory: "Storage",
			Era:         "Cyber",
			Cost:        20,
			Rarity:      0,
			Size:        0,
			Weight:      0.1,
			Type:        "Storage",
			Special:     "Digital data storage",
			Description: "A small card for storing digital data.",
		},
		{
			ID:          uuid.New(),
			Name:        "Fake ID",
			Category:    "Electronics",
			Subcategory: "Forgery",
			Era:         "Cyber",
			Cost:        1000,
			Rarity:      1,
			Size:        0,
			Weight:      0.1,
			Type:        "Forgery",
			Special:     "Rating 1 - 10",
			Rating:      1,
			Description: "A forged identification document.",
		},
		{
			ID:          uuid.New(),
			Name:        "Fake License",
			Category:    "Electronics",
			Subcategory: "Forgery",
			Era:         "Cyber",
			Cost:        200,
			Rarity:      1,
			Size:        0,
			Weight:      0.1,
			Type:        "Forgery",
			Special:     "Rating 1 - 10",
			Rating:      1,
			Description: "A forged license or permit.",
		},
		{
			ID:          uuid.New(),
			Name:        "Holo Projector",
			Category:    "Electronics",
			Subcategory: "Display",
			Era:         "Cyber",
			Cost:        100,
			Rarity:      0,
			Size:        0,
			Weight:      0.5,
			Type:        "Display",
			Special:     "Holographic display",
			Description: "A device for projecting holographic images.",
		},
		{
			ID:          uuid.New(),
			Name:        "Jammer",
			Category:    "Electronics",
			Subcategory: "Security",
			Era:         "Cyber",
			Cost:        500,
			Rarity:      4,
			Size:        0,
			Weight:      0.5,
			Type:        "Security",
			Special:     "Jams area depending on size",
			Description: "A device for jamming electronic communications.",
		},
		{
			ID:          uuid.New(),
			Name:        "Program (Illegal)",
			Category:    "Electronics",
			Subcategory: "Software",
			Era:         "Cyber",
			Cost:        400,
			Rarity:      4,
			Size:        0,
			Weight:      0.1,
			Type:        "Software",
			Special:     "Can be used on Cyberdeck",
			Description: "Illegal software for cyberdeck systems.",
		},
		{
			ID:          uuid.New(),
			Name:        "Program (Legal)",
			Category:    "Electronics",
			Subcategory: "Software",
			Era:         "Cyber",
			Cost:        100,
			Rarity:      0,
			Size:        0,
			Weight:      0.1,
			Type:        "Software",
			Special:     "Can be used on comlink or Cyberdeck",
			Description: "Legal software for communication and computing devices.",
		},
		{
			ID:          uuid.New(),
			Name:        "Remote Control (Average)",
			Category:    "Electronics",
			Subcategory: "Control",
			Era:         "Cyber",
			Cost:        9000,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Type:        "Control",
			Special:     "Control 6 Drones",
			Capacity:    6,
			Description: "A device for controlling multiple drones simultaneously.",
		},
		{
			ID:          uuid.New(),
			Name:        "Remote Control (Cheap)",
			Category:    "Electronics",
			Subcategory: "Control",
			Era:         "Cyber",
			Cost:        3000,
			Rarity:      0,
			Size:        2,
			Weight:      2.0,
			Type:        "Control",
			Special:     "Control 4 Drones",
			Capacity:    4,
			Description: "A basic device for controlling a few drones.",
		},
		{
			ID:          uuid.New(),
			Name:        "Remote Control (Top of the Line)",
			Category:    "Electronics",
			Subcategory: "Control",
			Era:         "Cyber",
			Cost:        15000,
			Rarity:      4,
			Size:        2,
			Weight:      2.0,
			Type:        "Control",
			Special:     "Control 8 Drones",
			Capacity:    8,
			Description: "An advanced device for controlling many drones.",
		},
		{
			ID:          uuid.New(),
			Name:        "Sound Blocker",
			Category:    "Electronics",
			Subcategory: "Security",
			Era:         "Cyber",
			Cost:        400,
			Rarity:      0,
			Size:        0,
			Weight:      0.5,
			Type:        "Security",
			Special:     "-6 to listen in outside engaged area",
			Description: "A device that blocks sound from escaping an area.",
		},
		{
			ID:          uuid.New(),
			Name:        "Flashlight",
			Category:    "Light",
			Subcategory: "Illumination",
			Era:         "Cyber",
			Cost:        30,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Type:        "Illumination",
			Special:     "Portable light source",
			Description: "A portable electric light source.",
		},
		{
			ID:          uuid.New(),
			Name:        "Cyberware Restraint",
			Category:    "Restraint",
			Subcategory: "Binding",
			Era:         "Cyber",
			Cost:        500,
			Rarity:      4,
			Size:        0,
			Weight:      0.5,
			Type:        "Binding",
			Special:     "Escape: Agility: N/A, Brawn: 10",
			Description: "Advanced restraints that disable cyberware.",
		},
		{
			ID:          uuid.New(),
			Name:        "Handcuffs",
			Category:    "Restraint",
			Subcategory: "Binding",
			Era:         "Cyber",
			Cost:        200,
			Rarity:      0,
			Size:        0,
			Weight:      0.5,
			Type:        "Binding",
			Special:     "Escape: Agility: 8, Brawn: 7",
			Description: "Modern handcuffs for restraining prisoners.",
		},
		{
			ID:          uuid.New(),
			Name:        "Zip Ties",
			Category:    "Restraint",
			Subcategory: "Binding",
			Era:         "Cyber",
			Cost:        10,
			Rarity:      0,
			Size:        0,
			Weight:      0.1,
			Type:        "Binding",
			Special:     "Escape: Agility: 6, Brawn: 5",
			Description: "Disposable plastic restraints for temporary binding.",
		},
		{
			ID:          uuid.New(),
			Name:        "Autodoc Medkit",
			Category:    "Tools",
			Subcategory: "Medical",
			Era:         "Cyber",
			Cost:        1500,
			Rarity:      2,
			Size:        1,
			Weight:      1.0,
			Type:        "Medical",
			Special:     "Bonus equal to size",
			Rating:      1,
			Description: "An automated medical kit with basic treatment capabilities.",
		},
		{
			ID:          uuid.New(),
			Name:        "Automatic Lockpick",
			Category:    "Tools",
			Subcategory: "Security",
			Era:         "Cyber",
			Cost:        1200,
			Rarity:      4,
			Size:        0,
			Weight:      0.5,
			Type:        "Security",
			Special:     "Automatically opens mechanic locks up to threshold 3",
			Description: "An automated device for picking mechanical locks.",
		},
		{
			ID:          uuid.New(),
			Name:        "Eye Mimic",
			Category:    "Tools",
			Subcategory: "Security",
			Era:         "Cyber",
			Cost:        800,
			Rarity:      6,
			Size:        0,
			Weight:      0.1,
			Type:        "Security",
			Special:     "Copies retina",
			Description: "A device that can copy and replicate retinal patterns.",
		},
		{
			ID:          uuid.New(),
			Name:        "Gas Mask",
			Category:    "Tools",
			Subcategory: "Protection",
			Era:         "Cyber",
			Cost:        500,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Type:        "Protection",
			Special:     "1 no face shield, 2 face shield",
			Description: "A mask for protection against toxic gases and chemicals.",
		},
		{
			ID:          uuid.New(),
			Name:        "Glue Sprayer",
			Category:    "Tools",
			Subcategory: "Restraint",
			Era:         "Cyber",
			Cost:        250,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Type:        "Restraint",
			Special:     "Restrain at threshold 6",
			Description: "A device that sprays adhesive for restraining targets.",
		},
		{
			ID:          uuid.New(),
			Name:        "Handprint Mold",
			Category:    "Tools",
			Subcategory: "Security",
			Era:         "Cyber",
			Cost:        400,
			Rarity:      6,
			Size:        1,
			Weight:      1.0,
			Type:        "Security",
			Special:     "Copies hand/fingerprint",
			Description: "A device for copying hand and fingerprint patterns.",
		},
		{
			ID:          uuid.New(),
			Name:        "Mini Plasma Cutter",
			Category:    "Tools",
			Subcategory: "Cutting",
			Era:         "Cyber",
			Cost:        750,
			Rarity:      3,
			Size:        2,
			Weight:      2.0,
			Type:        "Cutting",
			Special:     "High-temperature cutting tool",
			Description: "A portable plasma cutter for cutting through metal.",
		},
		{
			ID:          uuid.New(),
			Name:        "Scuba Gear",
			Category:    "Tools",
			Subcategory: "Aquatic",
			Era:         "Cyber",
			Cost:        1500,
			Rarity:      0,
			Size:        4,
			Weight:      4.0,
			Type:        "Aquatic",
			Special:     "1 hour air, Full speed in water, +2 swim check",
			Description: "Equipment for underwater exploration and diving.",
		},
		{
			ID:          uuid.New(),
			Name:        "Solvent Sprayer",
			Category:    "Tools",
			Subcategory: "Chemical",
			Era:         "Cyber",
			Cost:        150,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Type:        "Chemical",
			Special:     "Remove glue",
			Description: "A device that sprays solvent to dissolve adhesives.",
		},
		{
			ID:          uuid.New(),
			Name:        "Spray Paint",
			Category:    "Tools",
			Subcategory: "Artistic",
			Era:         "Cyber",
			Cost:        40,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Type:        "Artistic",
			Special:     "Marking and graffiti",
			Description: "Paint in aerosol form for marking surfaces.",
		},
		{
			ID:          uuid.New(),
			Name:        "Surveillance Bug",
			Category:    "Tools",
			Subcategory: "Surveillance",
			Era:         "Cyber",
			Cost:        400,
			Rarity:      2,
			Size:        0,
			Weight:      0.1,
			Type:        "Surveillance",
			Special:     "Covert listening device",
			Description: "A small device for covert audio surveillance.",
		},
		{
			ID:          uuid.New(),
			Name:        "Thermite (Single Use)",
			Category:    "Tools",
			Subcategory: "Explosive",
			Era:         "Cyber",
			Cost:        400,
			Rarity:      3,
			Size:        1,
			Weight:      1.0,
			Type:        "Explosive",
			Special:     "Makes size 1 hole, through armor ≤6",
			Description: "A high-temperature explosive for breaching barriers.",
		},
		{
			ID:          uuid.New(),
			Name:        "Binoculars",
			Category:    "Vision",
			Subcategory: "Optics",
			Era:         "Cyber",
			Cost:        200,
			Rarity:      0,
			Size:        1,
			Weight:      1.0,
			Type:        "Optics",
			Special:     "Half vision penalty for range",
			Description: "Optical device for viewing distant objects.",
		},
		{
			ID:          uuid.New(),
			Name:        "Contacts",
			Category:    "Vision",
			Subcategory: "Optics",
			Era:         "Cyber",
			Cost:        300,
			Rarity:      0,
			Size:        0,
			Weight:      0.1,
			Type:        "Optics",
			Special:     "Capacity 1",
			Capacity:    1,
			Description: "Contact lenses with embedded technology.",
		},
		{
			ID:          uuid.New(),
			Name:        "Glasses/Goggles",
			Category:    "Vision",
			Subcategory: "Optics",
			Era:         "Cyber",
			Cost:        500,
			Rarity:      0,
			Size:        0,
			Weight:      0.5,
			Type:        "Optics",
			Special:     "Capacity 2",
			Capacity:    2,
			Description: "Eyewear with embedded technology and displays.",
		},
		{
			ID:          uuid.New(),
			Name:        "Scanner (Handheld)",
			Category:    "Vision",
			Subcategory: "Scanning",
			Era:         "Cyber",
			Cost:        300,
			Rarity:      0,
			Size:        0,
			Weight:      0.5,
			Type:        "Scanning",
			Special:     "Capacity = size+1",
			Capacity:    1,
			Description: "A portable device for scanning and analyzing objects.",
		},
		// Magical Equipment
		{
			ID:          uuid.New(),
			Name:        "Wand",
			Category:    "Magical Aid",
			Subcategory: "Focus",
			Era:         "Medieval",
			Cost:        3000,
			Rarity:      4,
			Size:        2,
			Weight:      2.0,
			Type:        "Focus",
			Special:     "Sets spell optimal range to Short",
			Description: "A magical focus that extends spell range to short distance.",
		},
		{
			ID:          uuid.New(),
			Name:        "Staff",
			Category:    "Magical Aid",
			Subcategory: "Focus",
			Era:         "Medieval",
			Cost:        4000,
			Rarity:      4,
			Size:        4,
			Weight:      4.0,
			Type:        "Focus",
			Special:     "Sets spell optimal range to Medium",
			Description: "A powerful magical focus that extends spell range to medium distance.",
		},
		{
			ID:          uuid.New(),
			Name:        "Reagents (Single Use)",
			Category:    "Magical Aid",
			Subcategory: "Consumable",
			Era:         "Medieval",
			Cost:        200,
			Rarity:      1,
			Size:        0,
			Weight:      0.1,
			Type:        "Consumable",
			Special:     "Lowers spell backlash damage by 1 (minimum 1)",
			Description: "Magical components that reduce spell backlash damage.",
		},
		{
			ID:          uuid.New(),
			Name:        "Magical Bag",
			Category:    "Carry",
			Subcategory: "Storage",
			Era:         "Medieval",
			Cost:        10000,
			Rarity:      8,
			Size:        1,
			Weight:      1.0,
			Type:        "Storage",
			Special:     "Allows character to carry (Rating) without encumbrance",
			Rating:      1,
			Description: "A magical bag that can carry items without weight.",
		},
		{
			ID:          uuid.New(),
			Name:        "Orichalcum Dust (Single Use)",
			Category:    "Tools",
			Subcategory: "Detection",
			Era:         "Medieval",
			Cost:        100,
			Rarity:      3,
			Size:        0,
			Weight:      0.1,
			Type:        "Detection",
			Special:     "Reveals magical energies in area: Close",
			Description: "Magical dust that reveals hidden magical energies.",
		},
		{
			ID:          uuid.New(),
			Name:        "Orichalcum Orb",
			Category:    "Magical Aid",
			Subcategory: "Focus",
			Era:         "Medieval",
			Cost:        1000,
			Rarity:      4,
			Size:        1,
			Weight:      1.0,
			Type:        "Focus",
			Special:     "2 less penalty for area spells",
			Description: "A magical orb that reduces penalties for area effect spells.",
		},
	}
}
