package seeds

import (
	"github.com/mremperor-atwork/rpg1/api1/internal/models"
)

// GetSpecies returns the species definitions
func GetSpecies() []models.Species {
	return []models.Species{
		{
			Name:         "Human",
			Size:         5,
			Special:      "Adaptable: Humans can spend 1 experience point to gain a skill specialty in any skill they have at least 1 rank in.",
			BrawnStart:   2,
			BrawnMax:     4,
			AgilityStart: 2,
			AgilityMax:   4,
			LogicStart:   2,
			LogicMax:     4,
			WitsStart:    2,
			PowerStart:   2,
			PowerMax:     4,
			CoolStart:    2,
			CoolMax:      4,
		},
		{
			Name:         "Elf",
			Size:         4,
			Special:      "Long-lived: Elves gain +1 to Logic and Wits, but -1 to Brawn. They also gain the 'Elven Grace' quality for free.",
			BrawnStart:   1,
			BrawnMax:     3,
			AgilityStart: 3,
			AgilityMax:   5,
			LogicStart:   3,
			LogicMax:     5,
			WitsStart:    3,
			PowerStart:   2,
			PowerMax:     4,
			CoolStart:    2,
			CoolMax:      4,
		},
		{
			Name:         "Dwarf",
			Size:         3,
			Special:      "Stout: Dwarves gain +2 to Brawn, but -1 to Agility. They also gain the 'Dwarven Toughness' quality for free.",
			BrawnStart:   4,
			BrawnMax:     6,
			AgilityStart: 1,
			AgilityMax:   3,
			LogicStart:   2,
			LogicMax:     4,
			WitsStart:    2,
			PowerStart:   2,
			PowerMax:     4,
			CoolStart:    2,
			CoolMax:      4,
		},
		{
			Name:         "Halfling",
			Size:         2,
			Special:      "Lucky: Halflings gain +1 to Cool and can reroll one failed roll per session.",
			BrawnStart:   1,
			BrawnMax:     3,
			AgilityStart: 3,
			AgilityMax:   5,
			LogicStart:   2,
			LogicMax:     4,
			WitsStart:    2,
			PowerStart:   2,
			PowerMax:     4,
			CoolStart:    3,
			CoolMax:      5,
		},
		{
			Name:         "Orc",
			Size:         6,
			Special:      "Brutal: Orcs gain +2 to Brawn and Power, but -1 to Logic and Cool. They also gain the 'Orcish Rage' quality for free.",
			BrawnStart:   4,
			BrawnMax:     6,
			AgilityStart: 2,
			AgilityMax:   4,
			LogicStart:   1,
			LogicMax:     3,
			WitsStart:    2,
			PowerStart:   4,
			PowerMax:     6,
			CoolStart:    1,
			CoolMax:      3,
		},
	}
}
