package seeds

import (
	"github.com/mremperor-atwork/rpg1/api1/internal/features/srd"
)

// GetSpells returns comprehensive spells from the RPG documentation
func GetSpells() []srd.Spell {
	return []srd.Spell{
		// Air Magic Spells
		{
			Name:              "Air Detection",
			School:            "Air",
			Level:             1,
			Type:              "Detection",
			Description:       "Feel targets in the air around you. Detect wind patterns, electrical currents, and air movement.",
			BacklashThreshold: 1,
			Area:              "Engaged",
			Duration:          "Instant",
			Components:        "None",
		},
		{
			Name:              "Air Knowledge",
			School:            "Air",
			Level:             2,
			Type:              "Knowing",
			Description:       "Learn information about air-related targets. Understand wind patterns, electrical systems, and air quality.",
			BacklashThreshold: 1,
			Area:              "Engaged",
			Duration:          "Instant",
			Components:        "None",
		},
		{
			Name:              "Minor Air Alteration",
			School:            "Air",
			Level:             3,
			Type:              "Minor Alteration",
			Description:       "Make small changes to air currents, electrical charges, or wind patterns.",
			BacklashThreshold: 2,
			Area:              "Engaged",
			Duration:          "Temporary",
			Components:        "Focus",
		},
		{
			Name:              "Minor Air Manipulation",
			School:            "Air",
			Level:             4,
			Type:              "Minor Manipulation",
			Description:       "Control small amounts of air, electricity, or wind for simple effects.",
			BacklashThreshold: 2,
			Area:              "Near",
			Duration:          "Sustained",
			Components:        "Focus",
		},
		{
			Name:              "Air Shielding",
			School:            "Air",
			Level:             5,
			Type:              "Shielding",
			Description:       "Create protective barriers of air or electrical fields.",
			BacklashThreshold: 3,
			Area:              "Near",
			Duration:          "Sustained",
			Components:        "Focus",
		},
		{
			Name:              "Air Alteration",
			School:            "Air",
			Level:             6,
			Type:              "Alteration",
			Description:       "Significantly change air properties, electrical systems, or wind patterns.",
			BacklashThreshold: 3,
			Area:              "Far",
			Duration:          "Extended",
			Components:        "Focus, Reagents",
		},
		{
			Name:              "Air Manipulation",
			School:            "Air",
			Level:             7,
			Type:              "Manipulation",
			Description:       "Control large amounts of air, electricity, or wind for complex effects.",
			BacklashThreshold: 4,
			Area:              "Far",
			Duration:          "Sustained",
			Components:        "Focus, Reagents",
		},
		{
			Name:              "Air Transformation",
			School:            "Air",
			Level:             8,
			Type:              "Transformation",
			Description:       "Transform air into other forms or create permanent air-based effects.",
			BacklashThreshold: 4,
			Area:              "Far",
			Duration:          "Permanent",
			Components:        "Focus, Reagents, Ritual",
		},
		{
			Name:              "Major Air Alteration",
			School:            "Air",
			Level:             9,
			Type:              "Major Alteration",
			Description:       "Dramatically alter air properties on a large scale.",
			BacklashThreshold: 5,
			Area:              "Very Far",
			Duration:          "Extended",
			Components:        "Focus, Reagents, Ritual",
		},
		{
			Name:              "Major Air Manipulation",
			School:            "Air",
			Level:             10,
			Type:              "Major Manipulation",
			Description:       "Control massive amounts of air, electricity, or wind for epic effects.",
			BacklashThreshold: 5,
			Area:              "Very Far",
			Duration:          "Sustained",
			Components:        "Focus, Reagents, Ritual",
		},

		// Dark Magic Spells
		{
			Name:              "Dark Detection",
			School:            "Dark",
			Level:             1,
			Type:              "Detection",
			Description:       "Feel darkness, cold, and negative emotions in the area.",
			BacklashThreshold: 1,
			Area:              "Engaged",
			Duration:          "Instant",
			Components:        "None",
		},
		{
			Name:              "Dark Knowledge",
			School:            "Dark",
			Level:             2,
			Type:              "Knowing",
			Description:       "Learn information about dark forces, curses, and negative emotions.",
			BacklashThreshold: 1,
			Area:              "Engaged",
			Duration:          "Instant",
			Components:        "None",
		},
		{
			Name:              "Minor Dark Alteration",
			School:            "Dark",
			Level:             3,
			Type:              "Minor Alteration",
			Description:       "Create small areas of darkness, cold, or negative emotions.",
			BacklashThreshold: 2,
			Area:              "Engaged",
			Duration:          "Temporary",
			Components:        "Focus",
		},
		{
			Name:              "Minor Dark Manipulation",
			School:            "Dark",
			Level:             4,
			Type:              "Minor Manipulation",
			Description:       "Control shadows, cold, and negative emotions for simple effects.",
			BacklashThreshold: 2,
			Area:              "Near",
			Duration:          "Sustained",
			Components:        "Focus",
		},
		{
			Name:              "Dark Shielding",
			School:            "Dark",
			Level:             5,
			Type:              "Shielding",
			Description:       "Create protective barriers of darkness or cold.",
			BacklashThreshold: 3,
			Area:              "Near",
			Duration:          "Sustained",
			Components:        "Focus",
		},
		{
			Name:              "Dark Alteration",
			School:            "Dark",
			Level:             6,
			Type:              "Alteration",
			Description:       "Significantly change areas with darkness, cold, or negative emotions.",
			BacklashThreshold: 3,
			Area:              "Far",
			Duration:          "Extended",
			Components:        "Focus, Reagents",
		},
		{
			Name:              "Dark Manipulation",
			School:            "Dark",
			Level:             7,
			Type:              "Manipulation",
			Description:       "Control large amounts of darkness, cold, or negative emotions.",
			BacklashThreshold: 4,
			Area:              "Far",
			Duration:          "Sustained",
			Components:        "Focus, Reagents",
		},
		{
			Name:              "Dark Transformation",
			School:            "Dark",
			Level:             8,
			Type:              "Transformation",
			Description:       "Transform areas into permanent darkness or create lasting dark effects.",
			BacklashThreshold: 4,
			Area:              "Far",
			Duration:          "Permanent",
			Components:        "Focus, Reagents, Ritual",
		},
		{
			Name:              "Major Dark Alteration",
			School:            "Dark",
			Level:             9,
			Type:              "Major Alteration",
			Description:       "Dramatically alter large areas with darkness and cold.",
			BacklashThreshold: 5,
			Area:              "Very Far",
			Duration:          "Extended",
			Components:        "Focus, Reagents, Ritual",
		},
		{
			Name:              "Major Dark Manipulation",
			School:            "Dark",
			Level:             10,
			Type:              "Major Manipulation",
			Description:       "Control massive amounts of darkness, cold, and negative emotions.",
			BacklashThreshold: 5,
			Area:              "Very Far",
			Duration:          "Sustained",
			Components:        "Focus, Reagents, Ritual",
		},

		// Earth Magic Spells
		{
			Name:              "Earth Detection",
			School:            "Earth",
			Level:             1,
			Type:              "Detection",
			Description:       "Feel earth, stone, and metal in the area.",
			BacklashThreshold: 1,
			Area:              "Engaged",
			Duration:          "Instant",
			Components:        "None",
		},
		{
			Name:              "Earth Knowledge",
			School:            "Earth",
			Level:             2,
			Type:              "Knowing",
			Description:       "Learn information about earth, stone, metal, and geological features.",
			BacklashThreshold: 1,
			Area:              "Engaged",
			Duration:          "Instant",
			Components:        "None",
		},
		{
			Name:              "Minor Earth Alteration",
			School:            "Earth",
			Level:             3,
			Type:              "Minor Alteration",
			Description:       "Make small changes to earth, stone, or metal.",
			BacklashThreshold: 2,
			Area:              "Engaged",
			Duration:          "Temporary",
			Components:        "Focus",
		},
		{
			Name:              "Minor Earth Manipulation",
			School:            "Earth",
			Level:             4,
			Type:              "Minor Manipulation",
			Description:       "Control small amounts of earth, stone, or metal for simple effects.",
			BacklashThreshold: 2,
			Area:              "Near",
			Duration:          "Sustained",
			Components:        "Focus",
		},
		{
			Name:              "Earth Shielding",
			School:            "Earth",
			Level:             5,
			Type:              "Shielding",
			Description:       "Create protective barriers of earth, stone, or metal.",
			BacklashThreshold: 3,
			Area:              "Near",
			Duration:          "Sustained",
			Components:        "Focus",
		},
		{
			Name:              "Earth Alteration",
			School:            "Earth",
			Level:             6,
			Type:              "Alteration",
			Description:       "Significantly change earth, stone, or metal properties.",
			BacklashThreshold: 3,
			Area:              "Far",
			Duration:          "Extended",
			Components:        "Focus, Reagents",
		},
		{
			Name:              "Earth Manipulation",
			School:            "Earth",
			Level:             7,
			Type:              "Manipulation",
			Description:       "Control large amounts of earth, stone, or metal.",
			BacklashThreshold: 4,
			Area:              "Far",
			Duration:          "Sustained",
			Components:        "Focus, Reagents",
		},
		{
			Name:              "Earth Transformation",
			School:            "Earth",
			Level:             8,
			Type:              "Transformation",
			Description:       "Transform earth, stone, or metal into other forms.",
			BacklashThreshold: 4,
			Area:              "Far",
			Duration:          "Permanent",
			Components:        "Focus, Reagents, Ritual",
		},
		{
			Name:              "Major Earth Alteration",
			School:            "Earth",
			Level:             9,
			Type:              "Major Alteration",
			Description:       "Dramatically alter large areas of earth, stone, or metal.",
			BacklashThreshold: 5,
			Area:              "Very Far",
			Duration:          "Extended",
			Components:        "Focus, Reagents, Ritual",
		},
		{
			Name:              "Major Earth Manipulation",
			School:            "Earth",
			Level:             10,
			Type:              "Major Manipulation",
			Description:       "Control massive amounts of earth, stone, or metal.",
			BacklashThreshold: 5,
			Area:              "Very Far",
			Duration:          "Sustained",
			Components:        "Focus, Reagents, Ritual",
		},

		// Illusion Magic Spells
		{
			Name:              "Illusion Detection",
			School:            "Illusion",
			Level:             1,
			Type:              "Detection",
			Description:       "Detect illusions, charms, and mental influences in the area.",
			BacklashThreshold: 1,
			Area:              "Engaged",
			Duration:          "Instant",
			Components:        "None",
		},
		{
			Name:              "Illusion Knowledge",
			School:            "Illusion",
			Level:             2,
			Type:              "Knowing",
			Description:       "Learn information about illusions, mental states, and hidden truths.",
			BacklashThreshold: 1,
			Area:              "Engaged",
			Duration:          "Instant",
			Components:        "None",
		},
		{
			Name:              "Minor Illusion Alteration",
			School:            "Illusion",
			Level:             3,
			Type:              "Minor Alteration",
			Description:       "Create small illusions or minor mental effects.",
			BacklashThreshold: 2,
			Area:              "Engaged",
			Duration:          "Temporary",
			Components:        "Focus",
		},
		{
			Name:              "Minor Illusion Manipulation",
			School:            "Illusion",
			Level:             4,
			Type:              "Minor Manipulation",
			Description:       "Control simple illusions and mental effects.",
			BacklashThreshold: 2,
			Area:              "Near",
			Duration:          "Sustained",
			Components:        "Focus",
		},
		{
			Name:              "Illusion Shielding",
			School:            "Illusion",
			Level:             5,
			Type:              "Shielding",
			Description:       "Create protective illusions and mental barriers.",
			BacklashThreshold: 3,
			Area:              "Near",
			Duration:          "Sustained",
			Components:        "Focus",
		},
		{
			Name:              "Illusion Alteration",
			School:            "Illusion",
			Level:             6,
			Type:              "Alteration",
			Description:       "Significantly change perceptions and create complex illusions.",
			BacklashThreshold: 3,
			Area:              "Far",
			Duration:          "Extended",
			Components:        "Focus, Reagents",
		},
		{
			Name:              "Illusion Manipulation",
			School:            "Illusion",
			Level:             7,
			Type:              "Manipulation",
			Description:       "Control complex illusions and mental effects.",
			BacklashThreshold: 4,
			Area:              "Far",
			Duration:          "Sustained",
			Components:        "Focus, Reagents",
		},
		{
			Name:              "Illusion Transformation",
			School:            "Illusion",
			Level:             8,
			Type:              "Transformation",
			Description:       "Transform reality perception and create permanent illusions.",
			BacklashThreshold: 4,
			Area:              "Far",
			Duration:          "Permanent",
			Components:        "Focus, Reagents, Ritual",
		},
		{
			Name:              "Major Illusion Alteration",
			School:            "Illusion",
			Level:             9,
			Type:              "Major Alteration",
			Description:       "Dramatically alter perceptions on a large scale.",
			BacklashThreshold: 5,
			Area:              "Very Far",
			Duration:          "Extended",
			Components:        "Focus, Reagents, Ritual",
		},
		{
			Name:              "Major Illusion Manipulation",
			School:            "Illusion",
			Level:             10,
			Type:              "Major Manipulation",
			Description:       "Control massive illusions and reality-warping effects.",
			BacklashThreshold: 5,
			Area:              "Very Far",
			Duration:          "Sustained",
			Components:        "Focus, Reagents, Ritual",
		},

		// Light Magic Spells
		{
			Name:              "Light Detection",
			School:            "Light",
			Level:             1,
			Type:              "Detection",
			Description:       "Feel light, fire, and positive emotions in the area.",
			BacklashThreshold: 1,
			Area:              "Engaged",
			Duration:          "Instant",
			Components:        "None",
		},
		{
			Name:              "Light Knowledge",
			School:            "Light",
			Level:             2,
			Type:              "Knowing",
			Description:       "Learn information about light, fire, healing, and positive forces.",
			BacklashThreshold: 1,
			Area:              "Engaged",
			Duration:          "Instant",
			Components:        "None",
		},
		{
			Name:              "Minor Light Alteration",
			School:            "Light",
			Level:             3,
			Type:              "Minor Alteration",
			Description:       "Create small amounts of light, fire, or healing effects.",
			BacklashThreshold: 2,
			Area:              "Engaged",
			Duration:          "Temporary",
			Components:        "Focus",
		},
		{
			Name:              "Minor Light Manipulation",
			School:            "Light",
			Level:             4,
			Type:              "Minor Manipulation",
			Description:       "Control small amounts of light, fire, or healing energy.",
			BacklashThreshold: 2,
			Area:              "Near",
			Duration:          "Sustained",
			Components:        "Focus",
		},
		{
			Name:              "Light Shielding",
			School:            "Light",
			Level:             5,
			Type:              "Shielding",
			Description:       "Create protective barriers of light or fire.",
			BacklashThreshold: 3,
			Area:              "Near",
			Duration:          "Sustained",
			Components:        "Focus",
		},
		{
			Name:              "Light Alteration",
			School:            "Light",
			Level:             6,
			Type:              "Alteration",
			Description:       "Significantly change light, fire, or healing properties.",
			BacklashThreshold: 3,
			Area:              "Far",
			Duration:          "Extended",
			Components:        "Focus, Reagents",
		},
		{
			Name:              "Light Manipulation",
			School:            "Light",
			Level:             7,
			Type:              "Manipulation",
			Description:       "Control large amounts of light, fire, or healing energy.",
			BacklashThreshold: 4,
			Area:              "Far",
			Duration:          "Sustained",
			Components:        "Focus, Reagents",
		},
		{
			Name:              "Light Transformation",
			School:            "Light",
			Level:             8,
			Type:              "Transformation",
			Description:       "Transform areas with permanent light or healing effects.",
			BacklashThreshold: 4,
			Area:              "Far",
			Duration:          "Permanent",
			Components:        "Focus, Reagents, Ritual",
		},
		{
			Name:              "Major Light Alteration",
			School:            "Light",
			Level:             9,
			Type:              "Major Alteration",
			Description:       "Dramatically alter large areas with light and fire.",
			BacklashThreshold: 5,
			Area:              "Very Far",
			Duration:          "Extended",
			Components:        "Focus, Reagents, Ritual",
		},
		{
			Name:              "Major Light Manipulation",
			School:            "Light",
			Level:             10,
			Type:              "Major Manipulation",
			Description:       "Control massive amounts of light, fire, and healing energy.",
			BacklashThreshold: 5,
			Area:              "Very Far",
			Duration:          "Sustained",
			Components:        "Focus, Reagents, Ritual",
		},

		// Nature Magic Spells
		{
			Name:              "Nature Detection",
			School:            "Nature",
			Level:             1,
			Type:              "Detection",
			Description:       "Feel plants, animals, and natural forces in the area.",
			BacklashThreshold: 1,
			Area:              "Engaged",
			Duration:          "Instant",
			Components:        "None",
		},
		{
			Name:              "Nature Knowledge",
			School:            "Nature",
			Level:             2,
			Type:              "Knowing",
			Description:       "Learn information about plants, animals, and natural phenomena.",
			BacklashThreshold: 1,
			Area:              "Engaged",
			Duration:          "Instant",
			Components:        "None",
		},
		{
			Name:              "Minor Nature Alteration",
			School:            "Nature",
			Level:             3,
			Type:              "Minor Alteration",
			Description:       "Make small changes to plants, animals, or natural forces.",
			BacklashThreshold: 2,
			Area:              "Engaged",
			Duration:          "Temporary",
			Components:        "Focus",
		},
		{
			Name:              "Minor Nature Manipulation",
			School:            "Nature",
			Level:             4,
			Type:              "Minor Manipulation",
			Description:       "Control small amounts of plants, animals, or natural forces.",
			BacklashThreshold: 2,
			Area:              "Near",
			Duration:          "Sustained",
			Components:        "Focus",
		},
		{
			Name:              "Nature Shielding",
			School:            "Nature",
			Level:             5,
			Type:              "Shielding",
			Description:       "Create protective barriers using natural forces.",
			BacklashThreshold: 3,
			Area:              "Near",
			Duration:          "Sustained",
			Components:        "Focus",
		},
		{
			Name:              "Nature Alteration",
			School:            "Nature",
			Level:             6,
			Type:              "Alteration",
			Description:       "Significantly change plants, animals, or natural forces.",
			BacklashThreshold: 3,
			Area:              "Far",
			Duration:          "Extended",
			Components:        "Focus, Reagents",
		},
		{
			Name:              "Nature Manipulation",
			School:            "Nature",
			Level:             7,
			Type:              "Manipulation",
			Description:       "Control large amounts of plants, animals, or natural forces.",
			BacklashThreshold: 4,
			Area:              "Far",
			Duration:          "Sustained",
			Components:        "Focus, Reagents",
		},
		{
			Name:              "Nature Transformation",
			School:            "Nature",
			Level:             8,
			Type:              "Transformation",
			Description:       "Transform into animals or create permanent natural effects.",
			BacklashThreshold: 4,
			Area:              "Far",
			Duration:          "Permanent",
			Components:        "Focus, Reagents, Ritual",
		},
		{
			Name:              "Major Nature Alteration",
			School:            "Nature",
			Level:             9,
			Type:              "Major Alteration",
			Description:       "Dramatically alter large areas with natural forces.",
			BacklashThreshold: 5,
			Area:              "Very Far",
			Duration:          "Extended",
			Components:        "Focus, Reagents, Ritual",
		},
		{
			Name:              "Major Nature Manipulation",
			School:            "Nature",
			Level:             10,
			Type:              "Major Manipulation",
			Description:       "Control massive amounts of plants, animals, and natural forces.",
			BacklashThreshold: 5,
			Area:              "Very Far",
			Duration:          "Sustained",
			Components:        "Focus, Reagents, Ritual",
		},

		// Summoning Magic Spells
		{
			Name:              "Summoning Detection",
			School:            "Summoning",
			Level:             1,
			Type:              "Detection",
			Description:       "Feel spirits, astral entities, and magical forces in the area.",
			BacklashThreshold: 1,
			Area:              "Engaged",
			Duration:          "Instant",
			Components:        "None",
		},
		{
			Name:              "Summoning Knowledge",
			School:            "Summoning",
			Level:             2,
			Type:              "Knowing",
			Description:       "Learn information about spirits, astral entities, and magical forces.",
			BacklashThreshold: 1,
			Area:              "Engaged",
			Duration:          "Instant",
			Components:        "None",
		},
		{
			Name:              "Minor Summoning Alteration",
			School:            "Summoning",
			Level:             3,
			Type:              "Minor Alteration",
			Description:       "Make small changes to spiritual or astral forces.",
			BacklashThreshold: 2,
			Area:              "Engaged",
			Duration:          "Temporary",
			Components:        "Focus",
		},
		{
			Name:              "Minor Summoning Manipulation",
			School:            "Summoning",
			Level:             4,
			Type:              "Minor Manipulation",
			Description:       "Control small amounts of spiritual or astral forces.",
			BacklashThreshold: 2,
			Area:              "Near",
			Duration:          "Sustained",
			Components:        "Focus",
		},
		{
			Name:              "Summoning Shielding",
			School:            "Summoning",
			Level:             5,
			Type:              "Shielding",
			Description:       "Create protective barriers using spiritual or astral forces.",
			BacklashThreshold: 3,
			Area:              "Near",
			Duration:          "Sustained",
			Components:        "Focus",
		},
		{
			Name:              "Summoning Alteration",
			School:            "Summoning",
			Level:             6,
			Type:              "Alteration",
			Description:       "Significantly change spiritual or astral forces.",
			BacklashThreshold: 3,
			Area:              "Far",
			Duration:          "Extended",
			Components:        "Focus, Reagents",
		},
		{
			Name:              "Summoning Manipulation",
			School:            "Summoning",
			Level:             7,
			Type:              "Manipulation",
			Description:       "Control large amounts of spiritual or astral forces.",
			BacklashThreshold: 4,
			Area:              "Far",
			Duration:          "Sustained",
			Components:        "Focus, Reagents",
		},
		{
			Name:              "Summoning Transformation",
			School:            "Summoning",
			Level:             8,
			Type:              "Transformation",
			Description:       "Transform spiritual or astral forces into other forms.",
			BacklashThreshold: 4,
			Area:              "Far",
			Duration:          "Permanent",
			Components:        "Focus, Reagents, Ritual",
		},
		{
			Name:              "Major Summoning Alteration",
			School:            "Summoning",
			Level:             9,
			Type:              "Major Alteration",
			Description:       "Dramatically alter large areas with spiritual or astral forces.",
			BacklashThreshold: 5,
			Area:              "Very Far",
			Duration:          "Extended",
			Components:        "Focus, Reagents, Ritual",
		},
		{
			Name:              "Major Summoning Manipulation",
			School:            "Summoning",
			Level:             10,
			Type:              "Major Manipulation",
			Description:       "Control massive amounts of spiritual or astral forces.",
			BacklashThreshold: 5,
			Area:              "Very Far",
			Duration:          "Sustained",
			Components:        "Focus, Reagents, Ritual",
		},
	}
}
