package seeds

import (
	"github.com/google/uuid"
	"github.com/mremperor-atwork/rpg1/api1/internal/features/srd"
)

func GetSRDEntries() []srd.SRDEntry {
	return []srd.SRDEntry{
		{
			ID:       uuid.New(),
			Title:    "Design Philosophy",
			Category: "Core Rules",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "How to Play - Basic Rules",
			Category: "Core Rules",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Character Creation Overview",
			Category: "Character Creation",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Attributes - General Rules",
			Category: "Attributes",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Derived Stats",
			Category: "Attributes",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Skills - General Rules",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Skill Specialties",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Extended Rolls",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Qualities - General Rules",
			Category: "Qualities",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Experience and Advancement",
			Category: "Character Advancement",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Magic - General Rules",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Magic Schools",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Combat - Basic Rules",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Equipment - General Rules",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Species Overview",
			Category: "Species",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Tolerance System",
			Category: "Core Rules",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Modifiers",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Conditions and Status Effects",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Physical Skills - Athletics",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Physical Skills - Melee",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Physical Skills - Pilot",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Physical Skills - Ranged",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Physical Skills - Stealth",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Physical Skills - Thievery",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Physical Skills - Unarmed",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Mental Skills - Academics",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Mental Skills - Crafts",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Mental Skills - Investigation",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Mental Skills - Medicine",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Mental Skills - Nature Lore",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Mental Skills - Occult",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Mental Skills - Science",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Skills - Empathy",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Skills - Performance",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Skills - Intimidation",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Skills - Persuasion",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Skills - Streetwise",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Skills - Style",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Skills - Subterfuge",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Divine Doctrines",
			Category: "Qualities",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dwarves",
			Category: "Species",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Elves",
			Category: "Species",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Halflings",
			Category: "Species",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Humans",
			Category: "Species",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Orcs",
			Category: "Species",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Trolls",
			Category: "Species",
			Version:  1,
		},
		// Magic System Entries
		{
			ID:       uuid.New(),
			Title:    "What is Magic?",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "The Gift and Astral Realms",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Limits of Magic",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Godspeech and Gestures",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Spellcasting Rules",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Spell Levels and Backlash",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Spell Terms and Attributes",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Targeting and Range",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Ritual Spellcasting",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Anchored Magic",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Conjunctive Magic",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Reagents and Foci",
			Category: "Magic",
			Version:  1,
		},
		// Individual Spell Entries - Air Magic
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Spy the Unseen (Level 1)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Sense Electricity (Level 1)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Understand Physics (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Cut through hardship (Level 3)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Air is no resistance (Level 3)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Mage hand (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Shift Current (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Kinetic Shield (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Wind Wall (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Slow Fall (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Alter Speed (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Light Body (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Alter Current (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Telekinetic Push (Level 7)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Lightning (Level 7)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Flash Forward (Level 8)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Wind Walking (Level 8)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Telekinetic Strength (Level 9)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Wind Blades (Level 9)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Telekinetic Grasp (Level 10)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Fly (Level 10)",
			Category: "Magic",
			Version:  1,
		},
		// Individual Spell Entries - Dark Magic
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Detect Undead (Level 1)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Sense Hatred (Level 1)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Know Undead (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Sense Weakness (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Speak with Dead (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Darken Shadows (Level 3)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Pierce Darkness (Level 3)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Direct Ire (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Command Undead (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Emotional Shield (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Shield of Darkness (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Curse (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Deteriorate (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Necrotic Energy (Level 7)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Raise Undead (Level 7)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Transform into Greater Undead (Level 8)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Raise Shade (Level 9)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Corruption (Level 9)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Implant Emotion (Level 10)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Cold Snap (Level 10)",
			Category: "Magic",
			Version:  1,
		},
		// Individual Spell Entries - Earth Magic
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Sense object (Level 1)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Radar (Level 1)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Understand mechanism (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Know Strength/Weakness (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Minor Matter Alteration (Level 3)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Move Earth (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Magnetism (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Earth Wall (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Earth Cocoon (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Enhance/De-Enhance Object (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Rust (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Unshakable (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Shape Item (Level 7)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Earth Shape (Level 7)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Lead into Gold (Level 8)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Quicksand (Level 9)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Rock Solid (Level 9)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Earth Spike (Level 10)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Golem (Level 10)",
			Category: "Magic",
			Version:  1,
		},
		// Individual Spell Entries - Illusion Magic
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - See through Illusions (Level 1)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Sense Minds (Level 1)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Read Surface Thoughts (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Know Falsehood (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Emperor's new clothes (Level 3)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Soothe emotions (Level 3)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Illusory Sound (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Entertainment (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Mirror Image (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Concealing Fog (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Charm (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Invisibility (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Illusory Image (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Mind Trick (Level 7)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Telepathy (Level 7)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - False Impression (Level 8)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Undetectable (Level 8)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Major Image (Level 9)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Glamour (Level 9)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Imaginary wounds (Level 10)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Rewrite Reality (Level 10)",
			Category: "Magic",
			Version:  1,
		},
		// Individual Spell Entries - Light Magic
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Sense Heat (Level 1)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Sense Health (Level 1)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Diagnose (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Arsonology (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Minor Fire Alteration (Level 3)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Joy (Level 3)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Firebolt (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Stop Bleeding (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Move Light (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Shield of Fire (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - False Health (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Alter Flame (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Heal (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Searing light (Level 7)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Pleasure (Level 7)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Flaming Weapon (Level 8)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Body of flame (Level 8)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Sweltering Heat (Level 9)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Restore (Level 9)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Suns Wrath (Level 10)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Absolute Peace (Level 10)",
			Category: "Magic",
			Version:  1,
		},
		// Individual Spell Entries - Nature Magic
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Sense life (Level 1)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Sense corruption (Level 1)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Speak With animal (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Know beast/plant (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Know instinct (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Cat eyes (Level 3)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Natures ally (Level 3)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Animal Friendship (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Natures enemy (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Enhance Immune system (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Barkskin (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Partial Beast Shape (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Animal instincts (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Control animal (Level 7)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Entangle (Level 7)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Beast Shape (Level 8)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Regeneration (Level 8)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Greater beast (Level 9)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Plague (Level 9)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Swarm (Level 10)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Fight or Flight (Level 10)",
			Category: "Magic",
			Version:  1,
		},
		// Individual Spell Entries - Summoning Magic
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Sense Bindings (Level 1)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Sense Magic (Level 1)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Summon Sage (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Know Summon (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Alter Resonance (Level 3)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Free Summon (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Make Pact (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Summon Object (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Spell Defense (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Defensive Summon (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Possession (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Spirit Barrier (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Suppress Magic (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Summon Being (Level 7)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Banish (Level 7)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Prepare Vessel (Level 8)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Inhabitation (Level 8)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Extradimensional Space (Level 9)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Bind (Level 9)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Open Gate (Level 10)",
			Category: "Magic",
			Version:  1,
		},
		// Additional Game Systems
		{
			ID:       uuid.New(),
			Title:    "Hacking and Matrix",
			Category: "Technology",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Combat - Advanced Rules",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Chases and Movement",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Environmental Hazards",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Weapons and Armor",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Cyberware and Augmentations",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Vehicles and Transportation",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Chemicals and Drugs",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Creatures and Summons",
			Category: "Game World",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Training and Tutors",
			Category: "Character Advancement",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Lifestyle and Social Status",
			Category: "Game World",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Cheat Sheet",
			Category: "Reference",
			Version:  1,
		},
		// Combat Rules
		{
			ID:       uuid.New(),
			Title:    "Combat Overview",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Combat Actions",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Complex Actions",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Simple Actions",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Swift Actions",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Free Actions",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Attack and Defense",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Critical Successes in Combat",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Combat Complications",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Grappling",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Area Attacks",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Charge",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Full Defense",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Ready Action",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Close Combat Attack",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Ranged Combat",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Aiming",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Withdraw and Close In",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Called Shots",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Initiative",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Range Bands",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Combat Modifiers",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Size Chart",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Barriers and Cover",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Vehicle Combat",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Environmental Hazards in Combat",
			Category: "Combat",
			Version:  1,
		},
		// Equipment Rules
		{
			ID:       uuid.New(),
			Title:    "Equipment Overview",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Weapon Rules",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Armor Rules",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Equipment Quality and Rarity",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Weapon Modifications",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Armor Modifications",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Obtaining and Selling Equipment",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Encumbrance and Carrying Capacity",
			Category: "Equipment",
			Version:  1,
		},
	}
}
