package seeds

// GetSRDContentEN returns the English content for the first 10 SRD entries
func GetSRDContentEN() []struct {
	Title   string
	Content string
} {
	return []struct {
		Title   string
		Content string
	}{
		{
			Title:   "Design Philosophy",
			Content: "The basic idea is to have few attributes with equal numbers in each category Physical, Mental and Social. Following the fact that there are few attributes they should all be useful for a character. They don't have to be equally useful but there should be no 'dump stat' that won't come back to haunt a player ever so often. No Attribute should feel useless and every attribute should contribute to something that benefits a character.\n\nSkills: It is hard to balance skills. There should be neither too few or too many. Every skill should have a role to play and yet I wish to have the same number of skills in each category.\n\nMagic: I wish to give rise to many sorts of spellcasters, magic is the realm of clerics, druids, scholarly wizards and demon-summoning warlocks. And they are not as locked in as a class-system like DnD. You want a druid who becomes a bear and spits lightning? That should be doable. but not without downsides.\n\nTolerance: I wish to have a system that keeps PCs from being so full of cyberware that they are effectively a robot or being a walking spell repository and to keep mages from simply augmenting themselves to godhood.\n\nCombat: This is very difficult. As all developers know you cannot have it all. I want combat that flows faster than shadowrun, rarely messes with action economy, and can feel both epic and deadly.",
		},
		{
			Title:   "How to Play - Basic Rules",
			Content: "Rolls: For any situation, other than structured time such as combat, rolls should be one and done. Drawn out rolls rarely add anything to a game. As much as possible should be resolved by one roll per participating party.\n\nBase thresholds:\n1: Routine, don't bother rolling unless character is heavily penalized. Example: academics or science, basic addition.\n2: Easy, most people will rarely fail. Example: craft, whittle a sharpened stake.\n3: Average, a professional will rarely fail. Example: athletics, throwing a grenade to land inside a 1m by 1m area.\n4: Tricky, a professional will fail ever so often. Example: Survival: hunting deer.\n5-6. Difficult, a professional will fail often. Example: Performance, perform an unpracticed monologue from a play.\n7-8. Very difficult, a professional will fail more than succeed. Example: ranged weapons, split an arrow with yours.\n9-10. Insane, a professional will maybe manage this once or a few times in their career but few would risk it. Example: Pilot: Landing an aircraft on another aircraft in flight.",
		},
		{
			Title:   "Character Creation Overview",
			Content: "Character creation follows these steps:\n1. Character concept\n2. Virtue and Vice\n3. Species\n4. Attributes\n5. Skills\n6. Skill Specialties\n7. Positive Qualities\n8. Negative Qualities\n9. Spend Experience\n10. Starting Equipment\n11. Derived Stats\n12. Character Name\n\nCharacter creation options:\n- Underdog: Your character is in the early stages of their career. Attribute limit Species starting value +2 (one at +3), Skill limit: 4 (one at 5). 155 experience points.\n- Nothing special: Your character knows what they are doing. Attribute limit: Species starting value +3 (One at +4), Skill limit: 5 (one at 6). 234 experience points.\n- Something special: Your character is a capable professional or natural talent. Attribute limit: Species starting value +4, choose 1 attribute with no limit, Skill limit: 6 (two at 7). 349 experience points.\n- Heroic: Your character is exceptional, a true hero. Attribute limit: Species starting value +5, choose 2 attributes with no limit, Skill limit: 7 (three at 8). 464 experience points.",
		},
		{
			Title:   "Attributes - General Rules",
			Content: "Attributes are the basic building blocks of your character. They represent your character's natural abilities and potential.\n\nAttribute ratings:\n0: Crippled, the character is severely impaired in this area.\n1: Poor, the character struggles with tasks involving this attribute.\n2: Average, the character is typical for their species.\n3: Good, the character is above average in this area.\n4: Exceptional, the character is notably gifted.\n5: Superhuman, the character is beyond normal limits.\n6+: Legendary, the character is truly extraordinary.\n\nPhysical Attributes:\n- Brawn: Physical strength, toughness, and endurance\n- Agility: Speed, coordination, and reflexes\n\nMental Attributes:\n- Logic: Intelligence, reasoning, and problem-solving\n- Wits: Awareness, perception, and quick thinking\n\nSocial Attributes:\n- Power: Charisma, leadership, and force of personality\n- Cool: Composure, self-control, and emotional stability",
		},
		{
			Title:   "Derived Stats",
			Content: "Carrying capacity: Brawn x 2 in kilograms. Characters can carry up to their carrying capacity without penalty.\n\nWillpower: Cool + Logic. Represents mental fortitude and can be spent to add dice to rolls.\n\nInitiative: Wits + Agility. Determines action order in combat.\n\nPerception: Wits + Logic. Used for noticing things and awareness checks.\n\nHearing Threshold: 10 - Wits. The difficulty to hear quiet sounds.\n\nPhysical resistance: Brawn + Cool. Used to resist physical effects and damage.\n\nMental resistance: Logic + Cool. Used to resist mental effects and manipulation.\n\nTolerance: A measure of how much magical or technological enhancement a character can handle. Tolerance 0: Frenzy risk. Negative Tolerance: Risk permanent Frenzy.",
		},
		{
			Title:   "Skills - General Rules",
			Content: "Skills measure your character's training in various areas. Such as professional training, exercise or experience in a field.\n\nAt character creation your skills start at 0. You can then spend Skill points from your starting points.\n\nSkill ratings:\n0: Untrained, the character has never learned even the most basic uses of this skill.\n1: Dabbler, The character has tried to use the skills once or twice.\n2-3: Hobbyist, The character uses this skill now and then but never has to depend on it.\n4: Near professional, A character who uses the skill often but lacks support or motivation.\n5-6: Professional, A character who uses the skill daily and likely makes their living from it.\n7: Expert, a character who follows all new developments, often has a specialty.\n8: Local authority, A character who is respected/watched/consulted for their ability.\n9: Master, A character who is indisputably a master of the craft, likely best in the region.\n10: Paragon, a character who has reached the limits of skill alone.\n\nIn order to put points in magical skills you will need to purchase 'The Gift' or 'Incomplete Gift' Quality.",
		},
		{
			Title:   "Skill Specialties",
			Content: "Skill specialties represent a narrow field of study for your character. Each specialty is tied to a particular skill. There are two kinds of specialties:\n\nA typical Specialty grants the character +2 when using a skill in the specified way.\n\nAn Exotic Specialty grants the character the ability to use their Skill rating for a field the skill does not otherwise allow, such as Computer Hacking with the Science skill.\n\nAt character creation you get a number of specialties tied to starting points.\n\nA skill can have an unlimited number of specialties but you cannot benefit from more than one at a time.\n\nSpecialties in magic skills do not give the ability to cast higher level spells. Only the skills base rating can do that.",
		},
		{
			Title:   "Extended Rolls",
			Content: "Many skill rolls can be improved by taking it slowly. When it is reasonable, a character can take a +1 for every additional instance of time spent on a roll, to a maximum of their Cool/2.\n\nCrafting a weapon may take 1 day, the crafter can get a +1 for 2 days, +2 for 3 days etc.\n\nWillpower on Extended rolls: If a character spends Willpower on an extended roll, they cannot regain Willpower until the roll's duration is over.",
		},
		{
			Title:   "Qualities - General Rules",
			Content: "Qualities represent something more unique to your character than Attributes, Skills and Specialties. They can represent things your character was born with, picked up through life or something they have accomplished.\n\nQualities all have a numerical value. This represents the number of Quality Points it costs to acquire the particular Positive Quality. Some Qualities have a range of numbers, this means that you can acquire multiple ratings of the Quality for different bonuses. Such as fighting styles that range from 1-5. To purchase rating 2, you first have to purchase rating 1. But each rating still only costs 1 point.\n\nBe well aware of the 'Wealthy' quality as it increases the amount of money you can start with at character creation. Furthermore, note that to get a magical skill you need to purchase 'The Gift' or 'Incomplete Gift' qualities.\n\nUnless the quality specifies otherwise you cannot pick the same quality multiple times.",
		},
		{
			Title:   "Experience and Advancement",
			Content: "Experience costs:\n- Attribute point: 10 XP\n- Skill point: 4 XP\n- Specialty: 3 XP\n- Quality Point: 2 XP\n\nEarning experience:\n- Automatic: 1 XP per session\n- Progression: 0-2 XP based on character development\n- Role Playing: 0-2 XP based on good roleplaying\n- Average per session should be 1-3 XP\n\nTraining time: Characters can train to improve skills and attributes, but this requires time and often a teacher or training materials.",
		},
		{
			Title:   "Magic - General Rules",
			Content: "When increasing your skill rating in a magical skill you automatically gain the ability to cast any spell listed under that level of skill (or a spell of that level that you create yourself). A specialization does not give you access to additional spells but simply increases the corresponding dice pool.\n\nSpell levels:\nLevel 1: Detection (Backlash Threshold: 1)\n- Feel targets in spell area.\n- Targets must be tied to Magic School.\n- Start at area: 'engaged' without penalties.\n- Net Successes typically determine how many details they know about the targets.\n\nLevel 2: Knowing (Backlash Threshold: 1)\n- Learn information.\n- Knowledge must be about a target related to a Magic School.\n- Net Successes typically determine how many pieces of information the caster learns.\n\nLevel 3: Minor Alteration (Backlash Threshold: 2)\n- Make small changes to targets.\n- Changes are temporary and limited in scope.\n- Net Successes determine the effectiveness of the alteration.",
		},
		{
			Title:   "Magic Schools",
			Content: "Air: Agility, Lightning, Speed, Telekinesis, Sound manipulation and Wind. Practitioners known as 'Adepts' or 'Wind Walkers'.\n\nDark: Cold, Curses, Frailty, Logic, Negative Emotions, Shadows, Undead. Practitioners known as 'Dark magicians' or 'Necromancers'.\n\nEarth: Brawn, Enhance object, Ruin objects, Make Equipment, Shape Earth, Stoicism. Practitioners known as 'Shapers'.\n\nIllusion: Charm, Cool, Illusions, Invisibility, Telepathy. Practitioners known as 'Enchanters' or 'Illusionists'.\n\nLight: Fire, Warm/hot feelings (Good feelings and anger), Healing, Light, Power, Purity, Revelation. Practitioners known as 'Healers' or 'Pyromancers'.\n\nNature: Animals, Disease, Instincts, Plants, Poison, Shapechange, Wits. Practitioners known as 'Druids' or 'Shifters'.\n\nSummoning: Affecting Magic, Astral, Banish, Bind, Exorcise, Possession, Summoning. Practitioners known as 'Shamans', 'Summoners' or 'Warlocks'.",
		},
		{
			Title:   "Combat - Basic Rules",
			Content: "Combat is structured time where actions are resolved in initiative order.\n\nInitiative: Wits + Agility determines action order. Higher initiative acts first.\n\nActions:\n- Simple Action: Basic actions like moving, drawing weapons, or simple skill checks\n- Complex Action: More involved actions like attacking, casting spells, or complex skill checks\n- Free Action: Minor actions that don't require significant time or effort\n\nAttack rolls: Skill + Attribute vs. Defense\n- Successes determine damage or effectiveness\n- Critical successes (rolling 10s) provide additional benefits\n- Dramatic failures (rolling 1s) can have serious consequences\n\nDefense: Agility + Athletics (dodge) or appropriate defensive skill\n\nDamage: Weapons and spells have damage ratings. Damage is reduced by armor.\n\nHealth: Characters have health equal to Brawn + Cool. When health reaches 0, characters are incapacitated.",
		},
		{
			Title:   "Equipment - General Rules",
			Content: "Equipment includes weapons, armor, tools, and other items that characters can use.\n\nWeapons:\n- Melee weapons: Swords, axes, maces, etc.\n- Ranged weapons: Bows, crossbows, firearms, etc.\n- Thrown weapons: Daggers, spears, grenades, etc.\n\nArmor:\n- Provides protection against damage\n- Can have penalties to physical actions\n- Different armor types for different body locations\n\nEncumbrance:\n- Medium: Up to 1.5x carrying capacity\n- Heavy: Up to 2x carrying capacity\n- Characters can carry beyond this but suffer penalties\n\nWeapon modifications:\n- Can enhance weapon capabilities\n- May require exotic specialties to use\n- Can affect weapon damage, accuracy, or special properties\n\nArmor modifications:\n- Can enhance protection\n- May provide additional benefits\n- Can affect mobility and other factors",
		},
		{
			Title:   "Species Overview",
			Content: "Dwarves: Stout and hardy, dwarves gain +2 to Brawn, but -1 to Agility. They also gain the 'Dwarven Toughness' quality for free. Dwarves have earth/stone colored skin and are known for their craftsmanship and resilience.\n\nElves: Long-lived and graceful, elves gain +1 to Logic and Wits, but -1 to Brawn. They also gain the 'Elven Grace' quality for free. Elves are known for their wisdom and connection to nature.\n\nHalflings: Small and lucky, halflings gain +1 to Cool and can reroll one failed roll per session. They are known for their good fortune and adaptability.\n\nHumans: Adaptable and versatile, humans can spend 1 experience point to gain a skill specialty in any skill they have at least 1 rank in. Humans are known for their flexibility and determination.\n\nOrcs: Strong and fierce, orcs gain +2 to Brawn, but -1 to Cool. They are known for their physical prowess and tribal culture.\n\nTrolls: Massive and powerful, trolls gain +3 to Brawn, but -2 to Agility and -1 to Cool. They are known for their incredible strength and durability.",
		},
		{
			Title:   "Tolerance System",
			Content: "Tolerance represents how much magical or technological enhancement a character can handle before suffering negative effects.\n\nTolerance 0: Frenzy. You risk losing control entirely. Any time you take damage you must roll a Mental Resistance DT: 4 or lose control. You must eliminate anyone and anything that COULD be a threat. That includes Enemies, Friends, passers by and animals (even caged ones). The Frenzy ends when you no longer perceive any threats.\n\nTolerance Negative: Risk permanent Frenzy. When you enter a frenzy. Roll 1d6. Every negative Tolerance you have counts upwards of the die. If you roll equal to or below the negative then you will be stuck in a state of frenzy, even if your tolerance increases again.\n\nExample: Orcus has gone down to -3 Tolerance. And is hit by a carelessly thrown rock. He rolls to resist but only gets 3. Its frenzy time! As he enters a frenzy he rolls 1d6… 4! That is above his negative tolerance. He is safe a little while longer…",
		},
		{
			Title:   "Social Modifiers",
			Content: "Social interactions are affected by various modifiers based on the situation:\n\nImpression modifiers:\n-10: Outlandish request\n-6: Hostile, highly expensive/dangerous, pariah\n-4: Unfriendly, expensive/dangerous, untrustworthy, terrible\n-2: Annoyed, difficult, selfish, bad\n0: Neutral, minor, none, average\n+1: Friendly, overpaying/bribe slightly, helpful, good\n+3: Liked, overpaying/bribe greatly, trustworthy, great\n+5: Devoted, ridiculously generous, virtuous, incontrovertible evidence\n\nAdditional modifiers:\n- Prejudiced: additional -2\n- Reputation affects social interactions\n- Arguments and evidence can provide bonuses\n- Social context matters significantly",
		},
		{
			Title:   "Conditions and Status Effects",
			Content: "Characters can be affected by various conditions that modify their capabilities:\n\nPhysical Conditions:\n- Off-balance: -2 to physical actions\n- Immobilized: Cannot move\n- Confused: -2 to mental actions\n- Distracted: -2 to perception checks\n- Tired: -1 to all actions\n- Exhausted: -2 to all actions\n- Angry: +1 to physical actions, -1 to social actions\n- On Fire: Takes damage each round\n- Impaled: Takes ongoing damage\n- Blown tire: Vehicle handling penalties\n\nMental Conditions:\n- Panicked: Severe penalties to actions\n- Fearful: -2 to social actions\n- Addicted: Various penalties depending on severity\n\nConditions can be caused by spells, environmental hazards, or other effects. Most conditions can be removed through appropriate actions or the passage of time.",
		},
		{
			Title:   "Physical Skills - Athletics",
			Content: "Athletics is a physical skill that represents a character's overall ability to move, run, jump, and perform other feats of athleticism. It can be used in a wide array of situations, such as when trying to outrun an opponent, climb a wall, dodge attacks, or even perform a tricky acrobatic maneuver.\n\nExample uses:\n- Climbing (Athletics + Brawn) Vs. Threshold\n- Swimming (Athletics + Brawn) Vs. Threshold\n- Gymnastics (Athletics + Agility) Vs. Threshold\n- Throwing (Athletics + Agility) Vs. Defense\n- Dodge (Athletics + Wits) Vs. Attack\n- Lift heavy object (Athletics + Brawn) Vs. Threshold (object size-brawn)\n\nExample Penalties:\n- Slippery -2 to -6\n- Bad weather -2 to -8\n- Swimming: -1 for every 2 encumbrance\n\nExample Bonuses:\n- Climbing gear +2 to +4 (climbing)\n- Swimming fins +4 (Swimming)\n\nExotic Specialties: Weapons with 'Exotic' tag.",
		},
		{
			Title:   "Physical Skills - Melee",
			Content: "Melee skill is a combat skill that focuses on the use of weapons like swords, axes, and other close-combat weapons. With mastery of this skill, characters can efficiently attack foes, parry incoming attacks and use shields to deflect damage.\n\nExample uses:\n- Armed attack (Melee + Agility) Vs. Defense\n- Parry (Melee + Wits) Vs. Attack\n- Identify melee weapon (Melee + Logic) Vs. Threshold\n- Find (best) improvised weapon (Melee + Wits) Vs. Threshold\n- Dazzling display (Melee + Power) Vs. Mental Resistance\n\nExotic Specialties: Weapons with 'Exotic' tag.",
		},
		{
			Title:   "Physical Skills - Pilot",
			Content: "The Pilot skill is a technical skill that represents a character's ability to operate various vehicles such as Cars, Horses, airplanes, helicopters, boats, and even spacecraft. This skill encompasses everything from basic navigation and maneuvering to stunts or avoiding gunfire.\n\nExample uses:\n- Ride (Pilot + Agility) Vs. Opposed pilot (chase) /Creature Agility + Athletics (unwilling mount)\n- Drive carriage (Pilot + Power) Vs. Opposed pilot (chase)\n- Drive car/motorcycle (Pilot + Wits) Vs. Opposed pilot (chase)\n- Fly aircraft (Pilot + Logic) Vs. Opposed pilot (chase)\n- Remote control (Pilot + Agility/Logic) Vs. Opposed pilot (chase)\n- Drive watercraft (Pilot + Wits) Vs. Opposed pilot (chase)\n\nExample Penalties:\n- Slippery -2 to -6 (Ground vehicles)\n- Poor sight -2 to -6\n- Unsafe speed -2 to -8\n- Vehicle handling -2 to -6\n- No stirrups -4 (ride)\n- Horse(s) spooked -4 (Ride/drive carriage)\n\nExample Bonuses:\n- Control Rig: +2\n- HUD/AR with navigation software +2 (on rolls to reach a particular destination, not chases)\n- Vehicle handling +2 to +6\n- Impressive Saddle +1, Exceptional Saddle +2 (Ride)\n\nExotic Specialties: (Jet) (Rotorcraft) (Sailing). In cyber era only: (Ride)",
		},
		{
			Title:   "Physical Skills - Ranged",
			Content: "The Ranged skill is a physical skill that represents a character's ability to use projectile weapons such as bows, crossbows, muskets, and modern firearms. This skill includes proficiency in aiming, firing, and reloading weapons, as well as knowledge of ammunition and the mechanics of different types of ranged weapons.\n\nExample uses:\n- Shoot bow (Ranged weapons + Agility) Vs. Defense\n- Shoot crossbow (Ranged weapons + Agility) Vs. Defense\n- Shoot firearm (Ranged weapons + Agility) Vs. Defense\n- Identify ranged weapon (Ranged weapons + Logic) Vs. Threshold\n\nExample Penalties:\n- Weather -2 to -8\n- Poor sight -2 to -6\n- Range -2 to -6\n- Cover -2 to -6\n\nExample Bonuses:\n- Smart Gun system: +2\n- Aim +1 to + 5\n\nExotic Specialties: Weapons with 'Exotic' tag.",
		},
		{
			Title:   "Physical Skills - Stealth",
			Content: "The Stealth skill is a physical skill that represents a character's ability to move silently and avoid detection. Characters with a high level of Stealth skill are able to blend in with their surroundings, use natural cover to stay hidden, and move quietly to avoid alerting enemies or other potential threats.\n\nExample uses:\n- Hide/Move silently (Stealth + Agility) Vs. Opposed Perception\n- Stalk/observe secretly (Stealth + Wits) Vs. Opposed Perception\n- Blend in (Stealth + Power) Vs. Opposed Perception\n\nExample Penalties:\n- Little cover -2 to -8\n- Bright or obvious clothing (-2 to -4)\n\nExample Bonuses:\n- Crowded +4 (stalk/blend in)\n- Appropriate clothing +2\n- High vantage (+4) (Stalk)",
		},
		{
			Title:   "Physical Skills - Thievery",
			Content: "The Thievery skill is a technical skill that represents a character's ability to perform illicit activities such as picking locks, picking pockets, disabling alarms, and hot-wiring vehicles. Characters with a high level of Thievery skill are able to masterfully manipulate locks and security systems.\n\nExample uses:\n- Pickpocket (Thievery + Agility) Vs. Threshold (item size) and Opposed Perception\n- Pick lock (Thievery + Agility) Vs. Threshold\n- Disable alarm (Thievery + Logic) Vs. Threshold\n- Hotwire car (Thievery + Logic) Vs. Threshold\n- Conceal item (Thievery + Wits) Vs. Opposed Perception\n\nExample Penalties:\n- Advanced security -2 to -8\n- Open area -2 (Pickpocket)\n- Object size -1 to -5 (Conceal item)\n\nExample Bonuses:\n- Crowded +2 (Pickpocket)\n- Tools +2 to +6\n- Large clothing +2 (Conceal item)",
		},
		{
			Title:   "Physical Skills - Unarmed",
			Content: "The Unarmed skill is a physical skill that represents a character's ability to engage in combat without weapons or other equipment. This skill is particularly useful in situations where carrying weapons is not feasible or where one's weapons have been taken away.\n\nExample uses:\n- Unarmed attack (Unarmed + Agility) Vs. Threshold\n- Grapple check (Unarmed + Brawn) Vs. Opposed grapple/escape check\n- Kick down door (Unarmed + Brawn) Vs. Threshold\n\nExotic Specialties: Weapons with 'Exotic' tag.",
		},
		{
			Title:   "Mental Skills - Academics",
			Content: "Academics skill is a mental skill that focuses on the study of history, politics, research, and law. It encompasses knowledge of past events, governmental structures, legal systems, and the ability to conduct research and analyze data.\n\nSample Specialties: Literature, History, Law, Linguistics, Research, Bureaucracy, Local Politics, National Politics, Scandals, noble houses\n\nExample uses:\n- Academic knowledge (Academics + Logic) Vs. Threshold\n- Academic Research (Academics + Cool) Vs. Threshold\n- Legal loopholes/draft contract (Academics + Logic) Vs. Threshold\n- Translation (Academics + Logic)\n- Political knowledge (Academics + Logic) Vs. Threshold\n- Cut red tape (Academics + Power) Vs. Threshold\n- Political motives (Academics + Logic OR Wits) Vs. Subterfuge + Logic/Power",
		},
		{
			Title:   "Mental Skills - Crafts",
			Content: "Crafts is a practical skill that focuses on creating and repairing physical objects. It encompasses a variety of disciplines such as Smithing, Sculpting, Inventing, and Repair. With mastery of this skill, characters can create complex objects, repair items, and invent new devices.\n\nSample Specialties: Automotive, Carpentry, Jury Rigging, Sculpting, Welding, smithing, fletching\n\nExample uses:\n- Repair machine/weapon (Crafts + Logic) Vs. Threshold\n  1 damage repaired per success. Base time: hours = size\n- Repair building (Crafts + Brawn) Vs. Threshold\n  1 damage repaired per success. Base time: days = size\n- Smithing (Crafts + Brawn) Vs. Threshold\n  Smithing threshold: 2 + weapon damage/armor rating. Base time: days = size\n- Jury rig (Crafts + Wits) Vs. Threshold\n  Threshold: half structure. Base time: 10 minutes per size, Object not repaired but functions as damaged\n- Sculpting (Crafts + Power) Vs. Threshold\n- Find flaw (Crafts + Wits) Vs. Threshold\n- Invent (Crafts + Logic) Vs. Threshold",
		},
		{
			Title:   "Mental Skills - Investigation",
			Content: "Investigation skill is a mental skill that focuses on the art of detection and gathering information. It encompasses a variety of disciplines such as investigating crime scenes, cryptography, finding hidden objects, and analysis.\n\nSample Specialties: Crime Scenes, Cryptography, Dreams, Forensic Accounting, Riddles\n\nExample uses:\n- Search (Investigation + Wits) Vs. Threshold/Opposed Stealth + Wits\n- Reconstruct crime scene (Investigation + Wits) Vs. Threshold\n- Analyze patterns (Investigation + Logic) Vs. Threshold",
		},
		{
			Title:   "Mental Skills - Medicine",
			Content: "Medicine skill is a practical skill that focuses on the knowledge and expertise of medicine and healing. It encompasses knowledge of anatomy, physiology, diagnosis, treatment, and nursing care.\n\nSample Specialties: Cardiology, First Aid, Pathology, Pharmacology\n\nExample uses:\n- First aid (Medicine + Agility) Vs. Threshold\n- Surgery (Medicine + Agility) Vs. Threshold\n- Long term care (Medicine + Logic) Vs. Threshold\n- Treat disease (Medicine + Logic) Vs. Threshold\n- Diagnose (Medicine + Wits) Vs. Threshold\n\nExotic Specialty: Surgery",
		},
		{
			Title:   "Mental Skills - Nature Lore",
			Content: "Nature Lore skill is a knowledge-based skill that focuses on understanding and interacting with the natural world. It encompasses knowledge of flora and fauna, tracking, survival in the wild, and environmental conditions.\n\nSample Specialties: Dogs, Exotic Pets, Horses, Training, Wild Animals, tracking, hunting\n\nExample uses:\n- Calm animal (Animal ken + Power OR Cool) Vs. Threshold\n- Animal Knowledge (Animal ken + Logic) Vs. Threshold\n- Recognize habitat (Animal ken + Logic) Vs. Threshold\n- Train animal (Animal ken + Cool) Vs. Threshold\n- Hunt for food (Nature Lore + Agility) Vs. Threshold\n- Follow tracks (Nature Lore + Wits) Vs. Threshold\n- Shelter (Nature Lore + Cool) Vs. Threshold\n- Navigate (Nature Lore + Logic) Vs. Threshold\n- Gather firewood (Nature Lore + Brawn) Vs. Threshold\n- Gather ingredients/edible plants (Nature Lore + Logic) Vs. Threshold\n\nExample Penalties:\n- Unfamiliar environment\n- Weather/darkness -2 to -8\n- Barren landscape -6\n- Hours passed -1 per/dry hour up to -8, -2 per raining hour (tracking) up to impossible\n- Poor/lacking tools -2 to -4 (gather firewood, shelter)\n\nExample Bonuses:\n- Familiar grounds +2\n- Near dawn or twilight +2 (hunting)\n- High vantage (+4) (hunting)",
		},
		{
			Title:   "Mental Skills - Occult",
			Content: "Occult skill represents knowledge of supernatural forces, magical theory, and spiritual matters. It encompasses understanding of rituals, spirits, magical creatures, and the hidden forces that shape the world.\n\nSample Specialties: Ritual magic, Spirit (type), offerings, Magical theory, ghosts, magical creatures, curses, religion, myth\n\nExample uses:\n- Strike infernal bargain (Occult + Power) Vs. Entity (Force + Power)\n- Know spirit/magical creature (Occult + Logic) Vs. Threshold\n- Recognize symbolism (Occult + Logic) Vs. Threshold\n- Prepare ritual area (Occult + Logic) Vs. Threshold\n- Occult knowledge (Occult + Logic) Vs. Threshold",
		},
		{
			Title:   "Mental Skills - Science",
			Content: "The Science skill is a knowledge-based skill that represents a character's understanding of scientific concepts, theories, and methods. It encompasses knowledge of physics, chemistry, biology, and other natural sciences.\n\nSample Specialties: Biology, Chemistry, Genetics, Optics, Particle Physics, Data Retrieval, Digital Security, Programming, User Interface Design\n\nExample uses:\n- Scientific knowledge (Science + Logic) Vs. Threshold\n- Scientific research (Science + Cool) Vs. Threshold\n- Chemistry (Science + Logic) Vs. Threshold\n- Disarm bomb (Science + Cool) Vs. Threshold\n- Perform experiment (Science + Logic) Vs. Threshold\n- Internet search (Computer + Logic) Vs. Threshold\n- Hacking (Computer + Logic) Vs. Threshold (or opposed Computer + Logic)\n- Programming (Computer + Logic) Vs. Threshold\n\nExotic Specialties: (Hacking), (Bioware)",
		},
		{
			Title:   "Social Skills - Empathy",
			Content: "Empathy skill represents the ability to understand and connect with others on an emotional level. It allows characters to read emotions, detect deception, and provide emotional support.\n\nSample Specialties: Buried Feelings, Calming, Emotions, Lies, Motives\n\nExample uses:\n- Determine emotions (Empathy + Wits) Vs. Subterfuge + Cool\n- Sense subterfuge (Empathy + Wits) Vs. Subterfuge + Power\n- Comprehend motives (Empathy + Logic) Vs. Subterfuge + Power\n- Soothe/Therapize (Empathy + Power) Vs. Threshold\n\nGear Bonuses:\n- Polygraph (Sense Subterfuge): +4\n- Psycological Evaluation (Comprehend motives, Determine emotions): +2\n- Microexpression reader (Sense Subterfuge, Determine emotions): +2\n- Blanket/toy (Soothe/Therapize): +1\n\nGear Penalties:\n- Panicked (Soothe/Therapize): -4\n- Fearful (Soothe/Therapize): -2\n- Voice Changer (Sense Subterfuge, Determine emotions): -2\n- Masked/voice only (Sense Subterfuge, Determine emotions): -2",
		},
		{
			Title:   "Social Skills - Performance",
			Content: "Performance skill represents the ability to entertain and captivate audiences through various artistic mediums. It encompasses music, dance, acting, and other forms of artistic expression.\n\nSample Specialties: Dance, Journalism, Music Composition, Painting, Speeches\n\nExample uses:\n- Dance (Performance + Agility) Vs. Threshold\n- Compose music (Performance + Logic) Vs. Threshold\n- Speech/evangelize (Performance + Power) Vs. Audience Mental resistance\n- Play instrument (Performance + Agility) Vs. Threshold\n- Sing (Performance + Power) Vs. Threshold\n\nExotic Specialties: (Instrument, (String, Key, Blow, other))\n\nGear Bonuses:\n- Drunk: +2\n- Impressive instruments: +2\n- Exceptional instruments: +4\n- Likes performance type: +2\n- Special effects/magic: +2\n- Proper Stage: +2\n\nGear Penalties:\n- Lack of instruments: -4\n- Dead drunk: -2\n- Low quality instruments: -2\n- Dislikes performance type: -2",
		},
		{
			Title:   "Social Skills - Intimidation",
			Content: "Intimidation skill represents the ability to inspire fear and compliance through threats, displays of force, or psychological pressure. It allows characters to control situations through fear rather than persuasion.\n\nSample Specialties: Direct Threats, Interrogation, Murderous Stare, Torture, Veiled Threats\n\nExample uses:\n- Show of force (Intimidation + Brawn) Vs. Mental Resistance\n- Threaten (Intimidation + Power) Vs. Mental Resistance\n- Torture (Intimidation + Cool) Vs. Physical Resistance\n\nIntimidator Bonuses:\n- Outnumbering: +2 (+4: Outnumbering greatly)\n- Armed: +2 (+4: Superior arms)\n- Intimidating Size: +2 (+4: Massive Size)\n- Advantageous position: +1 (Superior position +2)\n- Target helpless: +6\n\nIntimidator Penalties:\n- Outnumbering: -2 (-4: Outnumbering greatly)\n- Armed: -2 (-4: Superior arms)\n- Intimidating Size: -2 (-4: Massive Size)\n- Advantageous position: -1 (Superior position -2, Safe position -4)\n- Intimidator helpless: -8",
		},
		{
			Title:   "Social Skills - Persuasion",
			Content: "Persuasion skill represents the ability to influence others through argument, charm, and negotiation. It allows characters to convince others to take actions or change their opinions.\n\nSample Specialties: Fast Talking, Inspiring, Sales Pitches, Seduction, Sermons\n\nExample uses:\n- Fast talk (Persuasion + Wits) Vs. Mental Resistance\n- Negotiation (Persuasion + Power) Vs. Persuasion + Power\n- Seduction (Persuasion + Power) Vs Mental Resistance",
		},
		{
			Title:   "Social Skills - Streetwise",
			Content: "Streetwise skill represents knowledge of urban environments, criminal networks, and the underground economy. It allows characters to navigate dangerous neighborhoods and find illicit goods and services.\n\nSample Specialties: Black market, Gangs, Navigation, Rumors, Undercover work\n\nExample uses:\n- Underworld knowledge (Streetwise + Logic) Vs. Threshold\n- Find shortcut (Streetwise + Wits) Vs. Threshold\n- Get illegal goods/services (Streetwise + Power) Vs. Threshold\n- Learn local rumors (Streetwise + Wits) Vs. Threshold",
		},
		{
			Title:   "Social Skills - Style",
			Content: "Style skill represents the ability to present oneself effectively in social situations, manage appearances, and navigate social hierarchies. It encompasses fashion, etiquette, and social manipulation.\n\nSample Specialties: Clothing, high society, street, stylish recovery, making an entrance, gossip\n\nExample uses:\n- Fitting in (Style + Power) Vs. Threshold\n- Learning gossip (Style + Wits) Vs. Threshold\n- Spreading rumors (Style + Power) Vs. Threshold\n- Stylish recovery 'I meant to do that' (Style + Agility) Vs. Perception\n- Dressing right (Style + Logic) Vs. Threshold",
		},
		{
			Title:   "Social Skills - Subterfuge",
			Content: "Subterfuge skill represents the ability to deceive, mislead, and manipulate others through lies, disguises, and misdirection. It allows characters to hide their true intentions and create false impressions.\n\nSample Specialties: Detecting lies, Hidden meanings, Hiding emotions, Long cons, Misdirection\n\nExample uses:\n- Spotting lies (Subterfuge + Wits) Vs. Subterfuge + Power\n- Bluff (Subterfuge + Power) Vs. Subterfuge + Wits\n- Hide emotion (Subterfuge + Cool) Vs. Empathy + Wits\n- Disguise (Subterfuge + Power OR Wits) Vs. Perception\n- Play tough (Subterfuge + Brawn) Vs. Empathy + Wits\n- Forgery (Subterfuge + Logic) Vs. Perception or Applicable Skill + Wits",
		},
		{
			Title:   "Divine Doctrines",
			Content: "Divine Doctrine represents a character's commitment to divine ideals that affect their abilities and actions. These doctrines provide bonuses for actions that align with the deity's values and penalties for actions that oppose them.\n\nDolus: God of Illusion, Trickery, Thievery and Charm.\nEncouraged: Lies or trickery +1, Sleight of Hand +1, Slimy charm +1\nDiscouraged: Calling out a liar or exposing a trick -1, Violence before conversation -1, Being a sourpuss -1\n\nGaia: Goddess of Earth, Crafting, Stoicism and materials.\nEncouraged: Crafting something +1, Making plans methodically +1, Spending extra time on tasks +1\nDiscouraged: Destroying someone's hard work -1, Improvising despite plans -1, Convincing others to destroy things -1\n\nSolara: Goddess of Light, Healing, Fire and passion.\nEncouraged: Healing or aiding others +1, Acting thoughtlessly due to emotion +1, Fighting supernatural evil +1\nDiscouraged: Assisting 'evil' -1, Acting with logic instead of passion when people are at risk -1, Acting demure or pessimistic -1\n\nSylvanus: God of Nature, Plants, Animals and the circle of life.\nEncouraged: Caring for animals +1, Tracking and hunting +1, Protecting nature +1\nDiscouraged: Killing without good cause -1, Saving the weak -1, Using technology -1\n\nTempesta: Goddess of Air, Speed, Lightning and Storms.\nEncouraged: Acting in anger +1, Taking surprising actions +1, Teamworking +1\nDiscouraged: Diplomacy -1, Spending extra time on tasks -1, Trying to keep cool -1\n\nJanus: God of the Astral, Summoning, Gateways and Banishment.\nEncouraged: Acting in defense of others +1, Restraining or trapping +1, Bargaining +1\nDiscouraged: Acting against your word -1, Being uninvited in protected areas -1, Defending the guilty -1\n\nUmbra: Goddess of Darkness, Secrets, Cold, and Entropy.\nEncouraged: Acting pragmatically against custom +1, Hiding or concealing +1, Digging for hidden information +1",
		},
		{
			Title:   "Dwarves",
			Content: "Dwarves are stout and hardy folk known for their craftsmanship and resilience. They have earth and stone colored skin, and are typically shorter and more muscular than humans.\n\nAttribute Modifiers:\n- +2 to Brawn\n- -1 to Agility\n\nSpecial Qualities:\n- Dwarven Toughness: Dwarves gain the 'Dwarven Toughness' quality for free at character creation. This quality provides additional resistance to physical damage and environmental hazards.\n\nCultural Traits:\n- Master craftsmen and artisans\n- Strong connection to earth and stone\n- Traditional and conservative values\n- Excellent miners and engineers\n- Known for their resilience and determination\n\nStarting Languages:\n- Common\n- Dwarvish\n\nDwarves excel in physical labor, crafting, and combat situations where their natural toughness and strength provide advantages. Their reduced agility is offset by their superior durability and craftsmanship skills.",
		},
		{
			Title:   "Elves",
			Content: "Elves are long-lived and graceful beings known for their wisdom and connection to nature. They are typically taller and more slender than humans, with pointed ears and an ethereal beauty.\n\nAttribute Modifiers:\n- +1 to Logic\n- +1 to Wits\n- -1 to Brawn\n\nSpecial Qualities:\n- Elven Grace: Elves gain the 'Elven Grace' quality for free at character creation. This quality provides bonuses to agility-based actions and aesthetic pursuits.\n\nCultural Traits:\n- Deep connection to nature and magic\n- Long-lived with extended perspective on time\n- Artistic and philosophical inclinations\n- Masters of archery and magic\n- Known for their wisdom and patience\n\nStarting Languages:\n- Common\n- Elvish\n\nElves excel in mental pursuits, magic, archery, and social situations where their grace and wisdom provide advantages. Their reduced physical strength is compensated by their superior mental attributes and magical abilities.",
		},
		{
			Title:   "Halflings",
			Content: "Halflings are small and lucky folk known for their good fortune and adaptability. They are typically about half the size of humans, with curly hair and cheerful dispositions.\n\nAttribute Modifiers:\n- +1 to Cool\n\nSpecial Qualities:\n- Lucky: Halflings can reroll one failed roll per session. This represents their natural good fortune and ability to find success even in difficult circumstances.\n\nCultural Traits:\n- Naturally optimistic and cheerful\n- Excellent cooks and hosts\n- Skilled at avoiding notice\n- Strong community bonds\n- Known for their adaptability and resourcefulness\n\nStarting Languages:\n- Common\n- Halfling\n\nHalflings excel in social situations, stealth, and any activity where their natural luck and adaptability can provide advantages. Their small size can be a disadvantage in physical confrontations, but their luck and agility often help them avoid such situations.",
		},
		{
			Title:   "Humans",
			Content: "Humans are adaptable and versatile beings known for their flexibility and determination. They are the most common species and can be found in almost every environment and culture.\n\nAttribute Modifiers:\n- No attribute modifiers\n\nSpecial Qualities:\n- Adaptable: Humans can spend 1 experience point to gain a skill specialty in any skill they have at least 1 rank in. This represents their natural ability to adapt and learn quickly.\n\nCultural Traits:\n- Highly adaptable to different environments\n- Diverse cultures and societies\n- Ambitious and driven\n- Quick learners and innovators\n- Known for their determination and resilience\n\nStarting Languages:\n- Common\n- One additional language of choice\n\nHumans excel in versatility and adaptability. They may not have the natural advantages of other species, but their flexibility allows them to excel in almost any field through hard work and determination.",
		},
		{
			Title:   "Orcs",
			Content: "Orcs are strong and fierce warriors known for their physical prowess and tribal culture. They are typically larger and more muscular than humans, with prominent tusks and greenish skin.\n\nAttribute Modifiers:\n- +2 to Brawn\n- -1 to Cool\n\nSpecial Qualities:\n- Fierce: Orcs gain bonuses in combat situations and when facing physical challenges. Their natural aggression and strength make them formidable opponents.\n\nCultural Traits:\n- Strong tribal and clan bonds\n- Warrior culture and traditions\n- Respect for strength and honor\n- Skilled hunters and trackers\n- Known for their loyalty and courage\n\nStarting Languages:\n- Common\n- Orcish\n\nOrcs excel in physical combat, hunting, and any activity where their strength and ferocity provide advantages. Their reduced composure can make them more prone to emotional outbursts, but also makes them more passionate and driven.",
		},
		{
			Title:   "Trolls",
			Content: "Trolls are massive and powerful beings known for their incredible strength and durability. They are the largest of the common species, with thick skin and regenerative abilities.\n\nAttribute Modifiers:\n- +3 to Brawn\n- -2 to Agility\n- -1 to Cool\n\nSpecial Qualities:\n- Regeneration: Trolls have natural regenerative abilities that allow them to recover from injuries more quickly than other species.\n- Thick Skin: Trolls have natural armor due to their thick, tough skin.\n\nCultural Traits:\n- Solitary or small family groups\n- Territorial and protective\n- Strong connection to their environment\n- Skilled at survival and endurance\n- Known for their patience and persistence\n\nStarting Languages:\n- Common\n- Trollish\n\nTrolls excel in physical combat, endurance activities, and any situation where their incredible strength and durability provide advantages. Their reduced agility and composure are significant drawbacks, but their raw power often compensates for these limitations.",
		},
	}
}
