package seeds

// GetSRDContentEN returns the English content for the first 10 SRD entries
func GetSRDContentEN() []struct {
	Title   string
	Content string
} {
	return []struct {
		Title   string
		Content string
	}{
		{
			Title:   "Design Philosophy",
			Content: "The basic idea is to have few attributes with equal numbers in each category Physical, Mental and Social. Following the fact that there are few attributes they should all be useful for a character. They don't have to be equally useful but there should be no 'dump stat' that won't come back to haunt a player ever so often. No Attribute should feel useless and every attribute should contribute to something that benefits a character.\n\nSkills: It is hard to balance skills. There should be neither too few or too many. Every skill should have a role to play and yet I wish to have the same number of skills in each category.\n\nMagic: I wish to give rise to many sorts of spellcasters, magic is the realm of clerics, druids, scholarly wizards and demon-summoning warlocks. And they are not as locked in as a class-system like DnD. You want a druid who becomes a bear and spits lightning? That should be doable. but not without downsides.\n\nTolerance: I wish to have a system that keeps PCs from being so full of cyberware that they are effectively a robot or being a walking spell repository and to keep mages from simply augmenting themselves to godhood.\n\nCombat: This is very difficult. As all developers know you cannot have it all. I want combat that flows faster than shadowrun, rarely messes with action economy, and can feel both epic and deadly.",
		},
		{
			Title:   "How to Play - Basic Rules",
			Content: "Rolls: For any situation, other than structured time such as combat, rolls should be one and done. Drawn out rolls rarely add anything to a game. As much as possible should be resolved by one roll per participating party.\n\nBase thresholds:\n1: Routine, don't bother rolling unless character is heavily penalized. Example: academics or science, basic addition.\n2: Easy, most people will rarely fail. Example: craft, whittle a sharpened stake.\n3: Average, a professional will rarely fail. Example: athletics, throwing a grenade to land inside a 1m by 1m area.\n4: Tricky, a professional will fail ever so often. Example: Survival: hunting deer.\n5-6. Difficult, a professional will fail often. Example: Performance, perform an unpracticed monologue from a play.\n7-8. Very difficult, a professional will fail more than succeed. Example: ranged weapons, split an arrow with yours.\n9-10. Insane, a professional will maybe manage this once or a few times in their career but few would risk it. Example: Pilot: Landing an aircraft on another aircraft in flight.",
		},
		{
			Title:   "Character Creation Overview",
			Content: "Character creation follows these steps:\n1. Character concept\n2. Virtue and Vice\n3. Species\n4. Attributes\n5. Skills\n6. Skill Specialties\n7. Positive Qualities\n8. Negative Qualities\n9. Spend Experience\n10. Starting Equipment\n11. Derived Stats\n12. Character Name\n\nCharacter creation options:\n- Underdog: Your character is in the early stages of their career. Attribute limit Species starting value +2 (one at +3), Skill limit: 4 (one at 5). 155 experience points.\n- Nothing special: Your character knows what they are doing. Attribute limit: Species starting value +3 (One at +4), Skill limit: 5 (one at 6). 234 experience points.\n- Something special: Your character is a capable professional or natural talent. Attribute limit: Species starting value +4, choose 1 attribute with no limit, Skill limit: 6 (two at 7). 349 experience points.\n- Heroic: Your character is exceptional, a true hero. Attribute limit: Species starting value +5, choose 2 attributes with no limit, Skill limit: 7 (three at 8). 464 experience points.",
		},
		{
			Title:   "Attributes - General Rules",
			Content: "Attributes are the basic building blocks of your character. They represent your character's natural abilities and potential.\n\nAttribute ratings:\n0: Crippled, the character is severely impaired in this area.\n1: Poor, the character struggles with tasks involving this attribute.\n2: Average, the character is typical for their species.\n3: Good, the character is above average in this area.\n4: Exceptional, the character is notably gifted.\n5: Superhuman, the character is beyond normal limits.\n6+: Legendary, the character is truly extraordinary.\n\nPhysical Attributes:\n- Brawn: Physical strength, toughness, and endurance\n- Agility: Speed, coordination, and reflexes\n\nMental Attributes:\n- Logic: Intelligence, reasoning, and problem-solving\n- Wits: Awareness, perception, and quick thinking\n\nSocial Attributes:\n- Power: Charisma, leadership, and force of personality\n- Cool: Composure, self-control, and emotional stability",
		},
		{
			Title:   "Derived Stats",
			Content: "Carrying capacity: Brawn x 2 in kilograms. Characters can carry up to their carrying capacity without penalty.\n\nWillpower: Cool + Logic. Represents mental fortitude and can be spent to add dice to rolls.\n\nInitiative: Wits + Agility. Determines action order in combat.\n\nPerception: Wits + Logic. Used for noticing things and awareness checks.\n\nHearing Threshold: 10 - Wits. The difficulty to hear quiet sounds.\n\nPhysical resistance: Brawn + Cool. Used to resist physical effects and damage.\n\nMental resistance: Logic + Cool. Used to resist mental effects and manipulation.\n\nTolerance: A measure of how much magical or technological enhancement a character can handle. Tolerance 0: Frenzy risk. Negative Tolerance: Risk permanent Frenzy.",
		},
		{
			Title:   "Skills - General Rules",
			Content: "Skills measure your character's training in various areas. Such as professional training, exercise or experience in a field.\n\nAt character creation your skills start at 0. You can then spend Skill points from your starting points.\n\nSkill ratings:\n0: Untrained, the character has never learned even the most basic uses of this skill.\n1: Dabbler, The character has tried to use the skills once or twice.\n2-3: Hobbyist, The character uses this skill now and then but never has to depend on it.\n4: Near professional, A character who uses the skill often but lacks support or motivation.\n5-6: Professional, A character who uses the skill daily and likely makes their living from it.\n7: Expert, a character who follows all new developments, often has a specialty.\n8: Local authority, A character who is respected/watched/consulted for their ability.\n9: Master, A character who is indisputably a master of the craft, likely best in the region.\n10: Paragon, a character who has reached the limits of skill alone.\n\nIn order to put points in magical skills you will need to purchase 'The Gift' or 'Incomplete Gift' Quality.",
		},
		{
			Title:   "Skill Specialties",
			Content: "Skill specialties represent a narrow field of study for your character. Each specialty is tied to a particular skill. There are two kinds of specialties:\n\nA typical Specialty grants the character +2 when using a skill in the specified way.\n\nAn Exotic Specialty grants the character the ability to use their Skill rating for a field the skill does not otherwise allow, such as Computer Hacking with the Science skill.\n\nAt character creation you get a number of specialties tied to starting points.\n\nA skill can have an unlimited number of specialties but you cannot benefit from more than one at a time.\n\nSpecialties in magic skills do not give the ability to cast higher level spells. Only the skills base rating can do that.",
		},
		{
			Title:   "Extended Rolls",
			Content: "Many skill rolls can be improved by taking it slowly. When it is reasonable, a character can take a +1 for every additional instance of time spent on a roll, to a maximum of their Cool/2.\n\nCrafting a weapon may take 1 day, the crafter can get a +1 for 2 days, +2 for 3 days etc.\n\nWillpower on Extended rolls: If a character spends Willpower on an extended roll, they cannot regain Willpower until the roll's duration is over.",
		},
		{
			Title:   "Qualities - General Rules",
			Content: "Qualities represent something more unique to your character than Attributes, Skills and Specialties. They can represent things your character was born with, picked up through life or something they have accomplished.\n\nQualities all have a numerical value. This represents the number of Quality Points it costs to acquire the particular Positive Quality. Some Qualities have a range of numbers, this means that you can acquire multiple ratings of the Quality for different bonuses. Such as fighting styles that range from 1-5. To purchase rating 2, you first have to purchase rating 1. But each rating still only costs 1 point.\n\nBe well aware of the 'Wealthy' quality as it increases the amount of money you can start with at character creation. Furthermore, note that to get a magical skill you need to purchase 'The Gift' or 'Incomplete Gift' qualities.\n\nUnless the quality specifies otherwise you cannot pick the same quality multiple times.",
		},
		{
			Title:   "Experience and Advancement",
			Content: "Experience costs:\n- Attribute point: 10 XP\n- Skill point: 4 XP\n- Specialty: 3 XP\n- Quality Point: 2 XP\n\nEarning experience:\n- Automatic: 1 XP per session\n- Progression: 0-2 XP based on character development\n- Role Playing: 0-2 XP based on good roleplaying\n- Average per session should be 1-3 XP\n\nTraining time: Characters can train to improve skills and attributes, but this requires time and often a teacher or training materials.",
		},
		{
			Title:   "Magic - General Rules",
			Content: "When increasing your skill rating in a magical skill you automatically gain the ability to cast any spell listed under that level of skill (or a spell of that level that you create yourself). A specialization does not give you access to additional spells but simply increases the corresponding dice pool.\n\nSpell levels:\nLevel 1: Detection (Backlash Threshold: 1)\n- Feel targets in spell area.\n- Targets must be tied to Magic School.\n- Start at area: 'engaged' without penalties.\n- Net Successes typically determine how many details they know about the targets.\n\nLevel 2: Knowing (Backlash Threshold: 1)\n- Learn information.\n- Knowledge must be about a target related to a Magic School.\n- Net Successes typically determine how many pieces of information the caster learns.\n\nLevel 3: Minor Alteration (Backlash Threshold: 2)\n- Make small changes to targets.\n- Changes are temporary and limited in scope.\n- Net Successes determine the effectiveness of the alteration.",
		},
		{
			Title:   "Magic Schools",
			Content: "Air: Agility, Lightning, Speed, Telekinesis, Sound manipulation and Wind. Practitioners known as 'Adepts' or 'Wind Walkers'.\n\nDark: Cold, Curses, Frailty, Logic, Negative Emotions, Shadows, Undead. Practitioners known as 'Dark magicians' or 'Necromancers'.\n\nEarth: Brawn, Enhance object, Ruin objects, Make Equipment, Shape Earth, Stoicism. Practitioners known as 'Shapers'.\n\nIllusion: Charm, Cool, Illusions, Invisibility, Telepathy. Practitioners known as 'Enchanters' or 'Illusionists'.\n\nLight: Fire, Warm/hot feelings (Good feelings and anger), Healing, Light, Power, Purity, Revelation. Practitioners known as 'Healers' or 'Pyromancers'.\n\nNature: Animals, Disease, Instincts, Plants, Poison, Shapechange, Wits. Practitioners known as 'Druids' or 'Shifters'.\n\nSummoning: Affecting Magic, Astral, Banish, Bind, Exorcise, Possession, Summoning. Practitioners known as 'Shamans', 'Summoners' or 'Warlocks'.",
		},
		{
			Title:   "Combat - Basic Rules",
			Content: "Combat is structured time where actions are resolved in initiative order.\n\nInitiative: Wits + Agility determines action order. Higher initiative acts first.\n\nActions:\n- Simple Action: Basic actions like moving, drawing weapons, or simple skill checks\n- Complex Action: More involved actions like attacking, casting spells, or complex skill checks\n- Free Action: Minor actions that don't require significant time or effort\n\nAttack rolls: Skill + Attribute vs. Defense\n- Successes determine damage or effectiveness\n- Critical successes (rolling 10s) provide additional benefits\n- Dramatic failures (rolling 1s) can have serious consequences\n\nDefense: Agility + Athletics (dodge) or appropriate defensive skill\n\nDamage: Weapons and spells have damage ratings. Damage is reduced by armor.\n\nHealth: Characters have health equal to Brawn + Cool. When health reaches 0, characters are incapacitated.",
		},
		{
			Title:   "Equipment - General Rules",
			Content: "Equipment includes weapons, armor, tools, and other items that characters can use.\n\nWeapons:\n- Melee weapons: Swords, axes, maces, etc.\n- Ranged weapons: Bows, crossbows, firearms, etc.\n- Thrown weapons: Daggers, spears, grenades, etc.\n\nArmor:\n- Provides protection against damage\n- Can have penalties to physical actions\n- Different armor types for different body locations\n\nEncumbrance:\n- Medium: Up to 1.5x carrying capacity\n- Heavy: Up to 2x carrying capacity\n- Characters can carry beyond this but suffer penalties\n\nWeapon modifications:\n- Can enhance weapon capabilities\n- May require exotic specialties to use\n- Can affect weapon damage, accuracy, or special properties\n\nArmor modifications:\n- Can enhance protection\n- May provide additional benefits\n- Can affect mobility and other factors",
		},
		{
			Title:   "Species Overview",
			Content: "Dwarves: Stout and hardy, dwarves gain +2 to Brawn, but -1 to Agility. They also gain the 'Dwarven Toughness' quality for free. Dwarves have earth/stone colored skin and are known for their craftsmanship and resilience.\n\nElves: Long-lived and graceful, elves gain +1 to Logic and Wits, but -1 to Brawn. They also gain the 'Elven Grace' quality for free. Elves are known for their wisdom and connection to nature.\n\nHalflings: Small and lucky, halflings gain +1 to Cool and can reroll one failed roll per session. They are known for their good fortune and adaptability.\n\nHumans: Adaptable and versatile, humans can spend 1 experience point to gain a skill specialty in any skill they have at least 1 rank in. Humans are known for their flexibility and determination.\n\nOrcs: Strong and fierce, orcs gain +2 to Brawn, but -1 to Cool. They are known for their physical prowess and tribal culture.\n\nTrolls: Massive and powerful, trolls gain +3 to Brawn, but -2 to Agility and -1 to Cool. They are known for their incredible strength and durability.",
		},
		{
			Title:   "Tolerance System",
			Content: "Tolerance represents how much magical or technological enhancement a character can handle before suffering negative effects.\n\nTolerance 0: Frenzy. You risk losing control entirely. Any time you take damage you must roll a Mental Resistance DT: 4 or lose control. You must eliminate anyone and anything that COULD be a threat. That includes Enemies, Friends, passers by and animals (even caged ones). The Frenzy ends when you no longer perceive any threats.\n\nTolerance Negative: Risk permanent Frenzy. When you enter a frenzy. Roll 1d6. Every negative Tolerance you have counts upwards of the die. If you roll equal to or below the negative then you will be stuck in a state of frenzy, even if your tolerance increases again.\n\nExample: Orcus has gone down to -3 Tolerance. And is hit by a carelessly thrown rock. He rolls to resist but only gets 3. Its frenzy time! As he enters a frenzy he rolls 1d6… 4! That is above his negative tolerance. He is safe a little while longer…",
		},
		{
			Title:   "Social Modifiers",
			Content: "Social interactions are affected by various modifiers based on the situation:\n\nImpression modifiers:\n-10: Outlandish request\n-6: Hostile, highly expensive/dangerous, pariah\n-4: Unfriendly, expensive/dangerous, untrustworthy, terrible\n-2: Annoyed, difficult, selfish, bad\n0: Neutral, minor, none, average\n+1: Friendly, overpaying/bribe slightly, helpful, good\n+3: Liked, overpaying/bribe greatly, trustworthy, great\n+5: Devoted, ridiculously generous, virtuous, incontrovertible evidence\n\nAdditional modifiers:\n- Prejudiced: additional -2\n- Reputation affects social interactions\n- Arguments and evidence can provide bonuses\n- Social context matters significantly",
		},
		{
			Title:   "Conditions and Status Effects",
			Content: "Characters can be affected by various conditions that modify their capabilities:\n\nPhysical Conditions:\n- Off-balance: -2 to physical actions\n- Immobilized: Cannot move\n- Confused: -2 to mental actions\n- Distracted: -2 to perception checks\n- Tired: -1 to all actions\n- Exhausted: -2 to all actions\n- Angry: +1 to physical actions, -1 to social actions\n- On Fire: Takes damage each round\n- Impaled: Takes ongoing damage\n- Blown tire: Vehicle handling penalties\n\nMental Conditions:\n- Panicked: Severe penalties to actions\n- Fearful: -2 to social actions\n- Addicted: Various penalties depending on severity\n\nConditions can be caused by spells, environmental hazards, or other effects. Most conditions can be removed through appropriate actions or the passage of time.",
		},
		{
			Title:   "Physical Skills - Athletics",
			Content: "Athletics is a physical skill that represents a character's overall ability to move, run, jump, and perform other feats of athleticism. It can be used in a wide array of situations, such as when trying to outrun an opponent, climb a wall, dodge attacks, or even perform a tricky acrobatic maneuver.\n\nExample uses:\n- Climbing (Athletics + Brawn) Vs. Threshold\n- Swimming (Athletics + Brawn) Vs. Threshold\n- Gymnastics (Athletics + Agility) Vs. Threshold\n- Throwing (Athletics + Agility) Vs. Defense\n- Dodge (Athletics + Wits) Vs. Attack\n- Lift heavy object (Athletics + Brawn) Vs. Threshold (object size-brawn)\n\nExample Penalties:\n- Slippery -2 to -6\n- Bad weather -2 to -8\n- Swimming: -1 for every 2 encumbrance\n\nExample Bonuses:\n- Climbing gear +2 to +4 (climbing)\n- Swimming fins +4 (Swimming)\n\nExotic Specialties: Weapons with 'Exotic' tag.",
		},
		{
			Title:   "Physical Skills - Melee",
			Content: "Melee skill is a combat skill that focuses on the use of weapons like swords, axes, and other close-combat weapons. With mastery of this skill, characters can efficiently attack foes, parry incoming attacks and use shields to deflect damage.\n\nExample uses:\n- Armed attack (Melee + Agility) Vs. Defense\n- Parry (Melee + Wits) Vs. Attack\n- Identify melee weapon (Melee + Logic) Vs. Threshold\n- Find (best) improvised weapon (Melee + Wits) Vs. Threshold\n- Dazzling display (Melee + Power) Vs. Mental Resistance\n\nExotic Specialties: Weapons with 'Exotic' tag.",
		},
		{
			Title:   "Physical Skills - Pilot",
			Content: "The Pilot skill is a technical skill that represents a character's ability to operate various vehicles such as Cars, Horses, airplanes, helicopters, boats, and even spacecraft. This skill encompasses everything from basic navigation and maneuvering to stunts or avoiding gunfire.\n\nExample uses:\n- Ride (Pilot + Agility) Vs. Opposed pilot (chase) /Creature Agility + Athletics (unwilling mount)\n- Drive carriage (Pilot + Power) Vs. Opposed pilot (chase)\n- Drive car/motorcycle (Pilot + Wits) Vs. Opposed pilot (chase)\n- Fly aircraft (Pilot + Logic) Vs. Opposed pilot (chase)\n- Remote control (Pilot + Agility/Logic) Vs. Opposed pilot (chase)\n- Drive watercraft (Pilot + Wits) Vs. Opposed pilot (chase)\n\nExample Penalties:\n- Slippery -2 to -6 (Ground vehicles)\n- Poor sight -2 to -6\n- Unsafe speed -2 to -8\n- Vehicle handling -2 to -6\n- No stirrups -4 (ride)\n- Horse(s) spooked -4 (Ride/drive carriage)\n\nExample Bonuses:\n- Control Rig: +2\n- HUD/AR with navigation software +2 (on rolls to reach a particular destination, not chases)\n- Vehicle handling +2 to +6\n- Impressive Saddle +1, Exceptional Saddle +2 (Ride)\n\nExotic Specialties: (Jet) (Rotorcraft) (Sailing). In cyber era only: (Ride)",
		},
		{
			Title:   "Physical Skills - Ranged",
			Content: "The Ranged skill is a physical skill that represents a character's ability to use projectile weapons such as bows, crossbows, muskets, and modern firearms. This skill includes proficiency in aiming, firing, and reloading weapons, as well as knowledge of ammunition and the mechanics of different types of ranged weapons.\n\nExample uses:\n- Shoot bow (Ranged weapons + Agility) Vs. Defense\n- Shoot crossbow (Ranged weapons + Agility) Vs. Defense\n- Shoot firearm (Ranged weapons + Agility) Vs. Defense\n- Identify ranged weapon (Ranged weapons + Logic) Vs. Threshold\n\nExample Penalties:\n- Weather -2 to -8\n- Poor sight -2 to -6\n- Range -2 to -6\n- Cover -2 to -6\n\nExample Bonuses:\n- Smart Gun system: +2\n- Aim +1 to + 5\n\nExotic Specialties: Weapons with 'Exotic' tag.",
		},
		{
			Title:   "Physical Skills - Stealth",
			Content: "The Stealth skill is a physical skill that represents a character's ability to move silently and avoid detection. Characters with a high level of Stealth skill are able to blend in with their surroundings, use natural cover to stay hidden, and move quietly to avoid alerting enemies or other potential threats.\n\nExample uses:\n- Hide/Move silently (Stealth + Agility) Vs. Opposed Perception\n- Stalk/observe secretly (Stealth + Wits) Vs. Opposed Perception\n- Blend in (Stealth + Power) Vs. Opposed Perception\n\nExample Penalties:\n- Little cover -2 to -8\n- Bright or obvious clothing (-2 to -4)\n\nExample Bonuses:\n- Crowded +4 (stalk/blend in)\n- Appropriate clothing +2\n- High vantage (+4) (Stalk)",
		},
		{
			Title:   "Physical Skills - Thievery",
			Content: "The Thievery skill is a technical skill that represents a character's ability to perform illicit activities such as picking locks, picking pockets, disabling alarms, and hot-wiring vehicles. Characters with a high level of Thievery skill are able to masterfully manipulate locks and security systems.\n\nExample uses:\n- Pickpocket (Thievery + Agility) Vs. Threshold (item size) and Opposed Perception\n- Pick lock (Thievery + Agility) Vs. Threshold\n- Disable alarm (Thievery + Logic) Vs. Threshold\n- Hotwire car (Thievery + Logic) Vs. Threshold\n- Conceal item (Thievery + Wits) Vs. Opposed Perception\n\nExample Penalties:\n- Advanced security -2 to -8\n- Open area -2 (Pickpocket)\n- Object size -1 to -5 (Conceal item)\n\nExample Bonuses:\n- Crowded +2 (Pickpocket)\n- Tools +2 to +6\n- Large clothing +2 (Conceal item)",
		},
		{
			Title:   "Physical Skills - Unarmed",
			Content: "The Unarmed skill is a physical skill that represents a character's ability to engage in combat without weapons or other equipment. This skill is particularly useful in situations where carrying weapons is not feasible or where one's weapons have been taken away.\n\nExample uses:\n- Unarmed attack (Unarmed + Agility) Vs. Threshold\n- Grapple check (Unarmed + Brawn) Vs. Opposed grapple/escape check\n- Kick down door (Unarmed + Brawn) Vs. Threshold\n\nExotic Specialties: Weapons with 'Exotic' tag.",
		},
		{
			Title:   "Mental Skills - Academics",
			Content: "Academics skill is a mental skill that focuses on the study of history, politics, research, and law. It encompasses knowledge of past events, governmental structures, legal systems, and the ability to conduct research and analyze data.\n\nSample Specialties: Literature, History, Law, Linguistics, Research, Bureaucracy, Local Politics, National Politics, Scandals, noble houses\n\nExample uses:\n- Academic knowledge (Academics + Logic) Vs. Threshold\n- Academic Research (Academics + Cool) Vs. Threshold\n- Legal loopholes/draft contract (Academics + Logic) Vs. Threshold\n- Translation (Academics + Logic)\n- Political knowledge (Academics + Logic) Vs. Threshold\n- Cut red tape (Academics + Power) Vs. Threshold\n- Political motives (Academics + Logic OR Wits) Vs. Subterfuge + Logic/Power",
		},
		{
			Title:   "Mental Skills - Crafts",
			Content: "Crafts is a practical skill that focuses on creating and repairing physical objects. It encompasses a variety of disciplines such as Smithing, Sculpting, Inventing, and Repair. With mastery of this skill, characters can create complex objects, repair items, and invent new devices.\n\nSample Specialties: Automotive, Carpentry, Jury Rigging, Sculpting, Welding, smithing, fletching\n\nExample uses:\n- Repair machine/weapon (Crafts + Logic) Vs. Threshold\n  1 damage repaired per success. Base time: hours = size\n- Repair building (Crafts + Brawn) Vs. Threshold\n  1 damage repaired per success. Base time: days = size\n- Smithing (Crafts + Brawn) Vs. Threshold\n  Smithing threshold: 2 + weapon damage/armor rating. Base time: days = size\n- Jury rig (Crafts + Wits) Vs. Threshold\n  Threshold: half structure. Base time: 10 minutes per size, Object not repaired but functions as damaged\n- Sculpting (Crafts + Power) Vs. Threshold\n- Find flaw (Crafts + Wits) Vs. Threshold\n- Invent (Crafts + Logic) Vs. Threshold",
		},
		{
			Title:   "Mental Skills - Investigation",
			Content: "Investigation skill is a mental skill that focuses on the art of detection and gathering information. It encompasses a variety of disciplines such as investigating crime scenes, cryptography, finding hidden objects, and analysis.\n\nSample Specialties: Crime Scenes, Cryptography, Dreams, Forensic Accounting, Riddles\n\nExample uses:\n- Search (Investigation + Wits) Vs. Threshold/Opposed Stealth + Wits\n- Reconstruct crime scene (Investigation + Wits) Vs. Threshold\n- Analyze patterns (Investigation + Logic) Vs. Threshold",
		},
		{
			Title:   "Mental Skills - Medicine",
			Content: "Medicine skill is a practical skill that focuses on the knowledge and expertise of medicine and healing. It encompasses knowledge of anatomy, physiology, diagnosis, treatment, and nursing care.\n\nSample Specialties: Cardiology, First Aid, Pathology, Pharmacology\n\nExample uses:\n- First aid (Medicine + Agility) Vs. Threshold\n- Surgery (Medicine + Agility) Vs. Threshold\n- Long term care (Medicine + Logic) Vs. Threshold\n- Treat disease (Medicine + Logic) Vs. Threshold\n- Diagnose (Medicine + Wits) Vs. Threshold\n\nExotic Specialty: Surgery",
		},
		{
			Title:   "Mental Skills - Nature Lore",
			Content: "Nature Lore skill is a knowledge-based skill that focuses on understanding and interacting with the natural world. It encompasses knowledge of flora and fauna, tracking, survival in the wild, and environmental conditions.\n\nSample Specialties: Dogs, Exotic Pets, Horses, Training, Wild Animals, tracking, hunting\n\nExample uses:\n- Calm animal (Animal ken + Power OR Cool) Vs. Threshold\n- Animal Knowledge (Animal ken + Logic) Vs. Threshold\n- Recognize habitat (Animal ken + Logic) Vs. Threshold\n- Train animal (Animal ken + Cool) Vs. Threshold\n- Hunt for food (Nature Lore + Agility) Vs. Threshold\n- Follow tracks (Nature Lore + Wits) Vs. Threshold\n- Shelter (Nature Lore + Cool) Vs. Threshold\n- Navigate (Nature Lore + Logic) Vs. Threshold\n- Gather firewood (Nature Lore + Brawn) Vs. Threshold\n- Gather ingredients/edible plants (Nature Lore + Logic) Vs. Threshold\n\nExample Penalties:\n- Unfamiliar environment\n- Weather/darkness -2 to -8\n- Barren landscape -6\n- Hours passed -1 per/dry hour up to -8, -2 per raining hour (tracking) up to impossible\n- Poor/lacking tools -2 to -4 (gather firewood, shelter)\n\nExample Bonuses:\n- Familiar grounds +2\n- Near dawn or twilight +2 (hunting)\n- High vantage (+4) (hunting)",
		},
		{
			Title:   "Mental Skills - Occult",
			Content: "Occult skill represents knowledge of supernatural forces, magical theory, and spiritual matters. It encompasses understanding of rituals, spirits, magical creatures, and the hidden forces that shape the world.\n\nSample Specialties: Ritual magic, Spirit (type), offerings, Magical theory, ghosts, magical creatures, curses, religion, myth\n\nExample uses:\n- Strike infernal bargain (Occult + Power) Vs. Entity (Force + Power)\n- Know spirit/magical creature (Occult + Logic) Vs. Threshold\n- Recognize symbolism (Occult + Logic) Vs. Threshold\n- Prepare ritual area (Occult + Logic) Vs. Threshold\n- Occult knowledge (Occult + Logic) Vs. Threshold",
		},
		{
			Title:   "Mental Skills - Science",
			Content: "The Science skill is a knowledge-based skill that represents a character's understanding of scientific concepts, theories, and methods. It encompasses knowledge of physics, chemistry, biology, and other natural sciences.\n\nSample Specialties: Biology, Chemistry, Genetics, Optics, Particle Physics, Data Retrieval, Digital Security, Programming, User Interface Design\n\nExample uses:\n- Scientific knowledge (Science + Logic) Vs. Threshold\n- Scientific research (Science + Cool) Vs. Threshold\n- Chemistry (Science + Logic) Vs. Threshold\n- Disarm bomb (Science + Cool) Vs. Threshold\n- Perform experiment (Science + Logic) Vs. Threshold\n- Internet search (Computer + Logic) Vs. Threshold\n- Hacking (Computer + Logic) Vs. Threshold (or opposed Computer + Logic)\n- Programming (Computer + Logic) Vs. Threshold\n\nExotic Specialties: (Hacking), (Bioware)",
		},
		{
			Title:   "Social Skills - Empathy",
			Content: "Empathy skill represents the ability to understand and connect with others on an emotional level. It allows characters to read emotions, detect deception, and provide emotional support.\n\nSample Specialties: Buried Feelings, Calming, Emotions, Lies, Motives\n\nExample uses:\n- Determine emotions (Empathy + Wits) Vs. Subterfuge + Cool\n- Sense subterfuge (Empathy + Wits) Vs. Subterfuge + Power\n- Comprehend motives (Empathy + Logic) Vs. Subterfuge + Power\n- Soothe/Therapize (Empathy + Power) Vs. Threshold\n\nGear Bonuses:\n- Polygraph (Sense Subterfuge): +4\n- Psycological Evaluation (Comprehend motives, Determine emotions): +2\n- Microexpression reader (Sense Subterfuge, Determine emotions): +2\n- Blanket/toy (Soothe/Therapize): +1\n\nGear Penalties:\n- Panicked (Soothe/Therapize): -4\n- Fearful (Soothe/Therapize): -2\n- Voice Changer (Sense Subterfuge, Determine emotions): -2\n- Masked/voice only (Sense Subterfuge, Determine emotions): -2",
		},
		{
			Title:   "Social Skills - Performance",
			Content: "Performance skill represents the ability to entertain and captivate audiences through various artistic mediums. It encompasses music, dance, acting, and other forms of artistic expression.\n\nSample Specialties: Dance, Journalism, Music Composition, Painting, Speeches\n\nExample uses:\n- Dance (Performance + Agility) Vs. Threshold\n- Compose music (Performance + Logic) Vs. Threshold\n- Speech/evangelize (Performance + Power) Vs. Audience Mental resistance\n- Play instrument (Performance + Agility) Vs. Threshold\n- Sing (Performance + Power) Vs. Threshold\n\nExotic Specialties: (Instrument, (String, Key, Blow, other))\n\nGear Bonuses:\n- Drunk: +2\n- Impressive instruments: +2\n- Exceptional instruments: +4\n- Likes performance type: +2\n- Special effects/magic: +2\n- Proper Stage: +2\n\nGear Penalties:\n- Lack of instruments: -4\n- Dead drunk: -2\n- Low quality instruments: -2\n- Dislikes performance type: -2",
		},
		{
			Title:   "Social Skills - Intimidation",
			Content: "Intimidation skill represents the ability to inspire fear and compliance through threats, displays of force, or psychological pressure. It allows characters to control situations through fear rather than persuasion.\n\nSample Specialties: Direct Threats, Interrogation, Murderous Stare, Torture, Veiled Threats\n\nExample uses:\n- Show of force (Intimidation + Brawn) Vs. Mental Resistance\n- Threaten (Intimidation + Power) Vs. Mental Resistance\n- Torture (Intimidation + Cool) Vs. Physical Resistance\n\nIntimidator Bonuses:\n- Outnumbering: +2 (+4: Outnumbering greatly)\n- Armed: +2 (+4: Superior arms)\n- Intimidating Size: +2 (+4: Massive Size)\n- Advantageous position: +1 (Superior position +2)\n- Target helpless: +6\n\nIntimidator Penalties:\n- Outnumbering: -2 (-4: Outnumbering greatly)\n- Armed: -2 (-4: Superior arms)\n- Intimidating Size: -2 (-4: Massive Size)\n- Advantageous position: -1 (Superior position -2, Safe position -4)\n- Intimidator helpless: -8",
		},
		{
			Title:   "Social Skills - Persuasion",
			Content: "Persuasion skill represents the ability to influence others through argument, charm, and negotiation. It allows characters to convince others to take actions or change their opinions.\n\nSample Specialties: Fast Talking, Inspiring, Sales Pitches, Seduction, Sermons\n\nExample uses:\n- Fast talk (Persuasion + Wits) Vs. Mental Resistance\n- Negotiation (Persuasion + Power) Vs. Persuasion + Power\n- Seduction (Persuasion + Power) Vs Mental Resistance",
		},
		{
			Title:   "Social Skills - Streetwise",
			Content: "Streetwise skill represents knowledge of urban environments, criminal networks, and the underground economy. It allows characters to navigate dangerous neighborhoods and find illicit goods and services.\n\nSample Specialties: Black market, Gangs, Navigation, Rumors, Undercover work\n\nExample uses:\n- Underworld knowledge (Streetwise + Logic) Vs. Threshold\n- Find shortcut (Streetwise + Wits) Vs. Threshold\n- Get illegal goods/services (Streetwise + Power) Vs. Threshold\n- Learn local rumors (Streetwise + Wits) Vs. Threshold",
		},
		{
			Title:   "Social Skills - Style",
			Content: "Style skill represents the ability to present oneself effectively in social situations, manage appearances, and navigate social hierarchies. It encompasses fashion, etiquette, and social manipulation.\n\nSample Specialties: Clothing, high society, street, stylish recovery, making an entrance, gossip\n\nExample uses:\n- Fitting in (Style + Power) Vs. Threshold\n- Learning gossip (Style + Wits) Vs. Threshold\n- Spreading rumors (Style + Power) Vs. Threshold\n- Stylish recovery 'I meant to do that' (Style + Agility) Vs. Perception\n- Dressing right (Style + Logic) Vs. Threshold",
		},
		{
			Title:   "Social Skills - Subterfuge",
			Content: "Subterfuge skill represents the ability to deceive, mislead, and manipulate others through lies, disguises, and misdirection. It allows characters to hide their true intentions and create false impressions.\n\nSample Specialties: Detecting lies, Hidden meanings, Hiding emotions, Long cons, Misdirection\n\nExample uses:\n- Spotting lies (Subterfuge + Wits) Vs. Subterfuge + Power\n- Bluff (Subterfuge + Power) Vs. Subterfuge + Wits\n- Hide emotion (Subterfuge + Cool) Vs. Empathy + Wits\n- Disguise (Subterfuge + Power OR Wits) Vs. Perception\n- Play tough (Subterfuge + Brawn) Vs. Empathy + Wits\n- Forgery (Subterfuge + Logic) Vs. Perception or Applicable Skill + Wits",
		},
		{
			Title:   "Divine Doctrines",
			Content: "Divine Doctrine represents a character's commitment to divine ideals that affect their abilities and actions. These doctrines provide bonuses for actions that align with the deity's values and penalties for actions that oppose them.\n\nDolus: God of Illusion, Trickery, Thievery and Charm.\nEncouraged: Lies or trickery +1, Sleight of Hand +1, Slimy charm +1\nDiscouraged: Calling out a liar or exposing a trick -1, Violence before conversation -1, Being a sourpuss -1\n\nGaia: Goddess of Earth, Crafting, Stoicism and materials.\nEncouraged: Crafting something +1, Making plans methodically +1, Spending extra time on tasks +1\nDiscouraged: Destroying someone's hard work -1, Improvising despite plans -1, Convincing others to destroy things -1\n\nSolara: Goddess of Light, Healing, Fire and passion.\nEncouraged: Healing or aiding others +1, Acting thoughtlessly due to emotion +1, Fighting supernatural evil +1\nDiscouraged: Assisting 'evil' -1, Acting with logic instead of passion when people are at risk -1, Acting demure or pessimistic -1\n\nSylvanus: God of Nature, Plants, Animals and the circle of life.\nEncouraged: Caring for animals +1, Tracking and hunting +1, Protecting nature +1\nDiscouraged: Killing without good cause -1, Saving the weak -1, Using technology -1\n\nTempesta: Goddess of Air, Speed, Lightning and Storms.\nEncouraged: Acting in anger +1, Taking surprising actions +1, Teamworking +1\nDiscouraged: Diplomacy -1, Spending extra time on tasks -1, Trying to keep cool -1\n\nJanus: God of the Astral, Summoning, Gateways and Banishment.\nEncouraged: Acting in defense of others +1, Restraining or trapping +1, Bargaining +1\nDiscouraged: Acting against your word -1, Being uninvited in protected areas -1, Defending the guilty -1\n\nUmbra: Goddess of Darkness, Secrets, Cold, and Entropy.\nEncouraged: Acting pragmatically against custom +1, Hiding or concealing +1, Digging for hidden information +1",
		},
		// Combat Rules
		{
			Title:   "Combat Overview",
			Content: "Combat takes place in \"Structured Time\" meaning that characters each have a limited time to act. Combat is divided into \"Rounds\" each participant gets to act during each round. They act on their \"turn\" determined by their \"initiative order\".\n\nRounds are not meant to have an exact time constraint in order to make the action more cinematic. If a time is specified then the argument will always be made that someone could do more or less than their character or that a round has passed because someone spoke for more than a few seconds. That said a round is meant to be roughly 6 seconds.\n\nCombat is meant to be risky and potentially deadly for most characters. Inspired by the sort of ruthless danger seen in the likes of \"The Witcher\", \"The Last of Us\", and other action dramas.",
		},
		{
			Title:   "Combat Actions",
			Content: "Actions: every character has a few actions available to them during a round of combat. 1 complex action OR 2 simple actions, 1 swift action and as many free actions as the gm wishes to allow (minimum 1) any action may be replaced by a lower action, i.e. you may trade a simple action for another swift.\n\nAfter you have moved you cannot take another action and then keep moving. You may not split movement around actions.\n\nYou may not take any action twice in a turn even if you have the actions remaining.\n* Aiming is explicitly exempt from this rule.\n\nYou may not perform more than one attack action per turn even if one is physical and the other magic.",
		},
		{
			Title:   "Complex Actions",
			Content: "Complex actions:\n• Draw large/concealed weapon\n• Fully automatic fire\n• Suppressive fire\n• Spellcasting\n• Grapple\n• Area attack (close combat)\n• Charge (cannot be used with move, swift action)\n• Use skill\n• Full defense\n• Ready Action\n• Safe disengage",
		},
		{
			Title:   "Simple Actions",
			Content: "Simple actions:\n• Close combat Attack action\n• Single or burst fire\n• Reckless casting\n• Give command (to subservient npcs, drones, summons etc)\n• Escape grapple\n• Withdraw from engagement \n• Run\n• Aim\n• Draw weapon\n• Reload\n• Stand up\n• Observe in detail (perception check)\n• Pick up Object\n• Open door",
		},
		{
			Title:   "Swift Actions",
			Content: "Swift actions:\n• Move\n• Take cover (nearby)\n• Go prone \n• Declare Spell defense\n• Shielding magic\n• Quickdraw\n• Called shot",
		},
		{
			Title:   "Free Actions",
			Content: "Free actions:\n• Drop held object\n• Stop sustaining spell\n• Speak (short statements, no social skill use)",
		},
		{
			Title:   "Attack and Defense",
			Content: "Attack and defense actions:\nAttacker declares attack\nDefender declares:\n• Athletics + wits to dodge\n• Or Melee + wits to parry\n\nWhen a parry is initiated the one with smaller weapon size is penalized the size difference.\n\nRanged attacks cannot be blocked unless defender has a shield.\nRanged attackers have to take a penalty based on optimal range. Every rangeband away from optimal gives -2.\nDefender may add shield size to defense when blocking.\nA defender with an equipped projectile ranged weapon may use it to parry a close combat attack but the weapon only counts as half the size (rounded up).\n\nIf the attacker wins, their base damage (brawn + weapon damage) or (ranged weapon damage) is compared to defenders Lethal Threshold (armor x2 - armor piercing). If damage is higher it is lethal, if lower it is stun.\n\nThen add net successes to damage and remove modified soak. The final number is damage inflicted on the defender.",
		},
		{
			Title:   "Critical Successes in Combat",
			Content: "Critical successes and glitches in combat:\n\nImpressive success: \nAttacker: If the attacker achieves an impressive success by beating the defenders roll by half again as many successes. \nThey may choose one of the following options or one agreed by player and GM: \n1. make the attack do lethal damage even if the Lethal Threshold is too high.\n2. Inflict a minor negative condition on the target.\n\nDefender: If the defender achieves an impressive success by beating the attackers roll by half again as many successes. \nThey may choose one of the following options or one agreed by player and GM: \n1. Take a minor beneficial condition\n2. Inflict a minor negative condition on the attacker.\n\nExceptional success: \nAttacker: If the attacker achieves an exceptional success (critical hit) by beating the defenders roll by twice as many successes. \nThey may choose one of the following options or one agreed by player and GM: \n1. Ignore all targets armor rating (but not soak granted by brawn) \n2. Inflict a major negative condition on the defender.\n\nDefender: If the defender achieves an exceptional success by beating the attackers roll by twice as many successes. \nThey may choose one of the following options or one agreed by player and GM: \n1. Take a major beneficial condition\n2. Do damage to the attacker equal to net successes.",
		},
		{
			Title:   "Combat Complications",
			Content: "Complications in combat:\n\nMinor complication: \nAttacker: Suffer \"Off Balance\" Condition or Suffer \"Distracted\" Condition\n\nMajor Complication: \nAttacker: Drop weapon/ Weapon Jams/ Bowstring breaks/ 1 stun damage to unarmed attacker\n\nDramatic Failure: Weapon becomes damaged/ Unarmed attacker takes 1 Lethal damage, Attacker Falls prone\n\nDefender Minor Complication: Suffer \"Off Balance\" Condition or Suffer \"Distracted\" Condition\n\nDefender Major Complication: Drops Weapon (Parry) or Falls Prone (Dodge)\n\nDefender Dramatic Failure: Suffer 2 additional Damage, Damage upgrades (Lethal to aggravated etc), Suffer a Major Condition",
		},
		{
			Title:   "Grappling",
			Content: "Grapple:\nA grapple is initiated with an Unarmed + Agility test vs. Defense. If the attacker wins the test both participants suffer the grappled condition. After the grapple has been established both parties roll a \"grapple check\" brawn + unarmed. Or if a party only cares to escape the grapple they may utilize agility + athletics instead.\n\nThe opposed grapple check is then repeated each following round on the highest initiative of any grapple participant.\n\nWhen a party wins they may take one of several options:\n• Pin: the pinned character cannot take any non-free action except trying to escape the pin, or spellcasting without movement. A pinning participant can keep making other grapple maneuvers on subsequent rounds but leaving the grapple also means ending the pin.\n• Takedown: the one who performed this maneuver can either knock the opponent prone and remain standing; ending the grapple. Or follow along making them both count as prone to those outside the grapple but between them only the bottom one will suffer penalties of the prone condition.\n• Injure: the winner does damage as a successful attack. Either unarmed or with a held weapon of size 2 or smaller.\n• Forced move: the winner can raise the grapple up from prone, if they are already standing they can instead move the grapple as far as one move allows.\n• Draw weapon: maximum size 2.\n• Disarm, successful disarm means the winner now controls the weapon.\n• Apply restraints: as long as the grappler has rope, manacles or other restraints drawn they may use a maneuver to apply them, however, to apply the restraint they must succeed on this action once for every limb they wish to restrain.\n• Escape grapple.\n\nMultiple grapplers: if an ally wishes to take part in a grapple then they can do brawn + unarmed as a teamwork test. However they become a valid target for grapple actions.\n\nSpellcasting in grapple: A character who wishes to cast a spell in a grapple must either: Establish a pin, in which case they can cast with -3. Or Forego their grapple check and be unable to use gestures in casting.",
		},
		{
			Title:   "Area Attacks",
			Content: "Area attack (close combat):\nBy using a complex action a combatant may sweep their weapon or limb in a wide arch hitting multiple opponents. As long as all targets are within engaged distance to one another the attacker can affect a number of targets equal to half weapon size + 1 additional target for attackers size above 5. So a troll (size 6) with a two-handed sword (size 4) could affect 3 targets. However it is not possible to pick and choose what targets to affect in the area.\n\nPerforming an area attack is done with a -4 penalty and if any blocker gets a Critical success they can use it to halt your swing before affecting others.\n\nAdditionally area attack can be done instead of the normal attack penalties if the target is invisible.",
		},
		{
			Title:   "Charge",
			Content: "Charge (cannot be used with the move swift action):\nCharge allows a character to move from short range and into engaged and make a close combat attack. A charge has to be in a straight line, and cannot be done over difficult terrain. A charging character gets +2 on their close combat check but suffers -2 to defense until their next turn.",
		},
		{
			Title:   "Full Defense",
			Content: "Full defense:\nA character may choose to hunker down and focus on defense instead of attacking. A character taking full defense receives a bonus to all defensive actions equal to their Cool stat.\n\nA character who has not yet acted, and is not surprised may declare that they are taking a full defense action before it is their turn to act.\n\nTaking full defense can be a great way to improve your chances later in combat since you are much more likely to get a Critical success on your defense rolls, allowing you to inflict conditions.",
		},
		{
			Title:   "Ready Action",
			Content: "Ready Action:\nA character may choose to prepare an action instead of acting immediately. You can choose any one action up to a complex action to be performed when certain conditions are met as a reaction. You must set simple and observable conditions such as \"as soon as someone enters the room\" and an action you can perform such as \"I will shoot the person who enters\".\n\nThis action remains in place until you take a different action or lose the ability to perform it. The GM may permit you to take certain fitting actions such as aim actions if you plan to shoot a particular place or an intimidation. But they have to occur on subsequent turns as normal.",
		},
		{
			Title:   "Close Combat Attack",
			Content: "Close combat attack action:\nAttacking is at the core of combat. It requires the attacker to be in engaged range with the defender. One attack isn't necessarily one hack, slash, stab or punch but rather a quick back and forth between the combatants.\n\nA close combat attack consists of Agility + Melee or Unarmed.",
		},
		{
			Title:   "Ranged Combat",
			Content: "Single or burst fire:\nAttacking with a ranged weapon. Most older range weapons can only fire a single shot per attack. Some modern weapons are capable of burst fire, or fully automatic, both of which can fire a 3 round burst as a single round.\n\nA ranged attack action consists of Agility + Ranged weapons for projectile weapons and Agility + Athletics for throwing.\nBurst applies -2 to the target's defense roll.",
		},
		{
			Title:   "Aiming",
			Content: "Aim:\nYou can \"aim\" using any weapon, this can be described as looking through a scope and holding your breath or sizing up your opponents defense or making light probing attacks that will never really hit to see the openings.\n\nRegardless of how it is described, aim gives the user +1 to their next attack roll against the intended target (or target in the same position), this can be done for a number of simple actions up to the aimer's Cool/2.\n\nAim is excepted from the rule to not perform the same action twice in a turn.\n\nIn close combat, if the target of the aim action stops being engaged with the aimer for any reason, the aim bonus is lost.\nIn ranged combat, if the target of the aim action disappears out of sight the aim bonus is lost.\nSimilarly if the aimer takes any active action other than aiming or attacking their aimed target they lose the aim bonus.",
		},
		{
			Title:   "Withdraw and Close In",
			Content: "Withdraw/Close in:\nWithdraw: Maybe a close combat engagement is not for you. However, turning and running is a good way to be stabbed to death. So you need to try to extricate yourself from combat. \nThis can be done with an Agility + Athletics roll. It is opposed by the other combatant(s) close combat rolls (reach is not a concern in these rolls). \nIf you get any net successes you can withdraw into close range, if they score a grazing hit you are stuck in the engagement but take no damage, if they score net hits then you stay in combat and take damage as if they had done a successful attack.\n\nClose in: similarly, if you find yourself outclassed by your opponents reach you can close in. That means stepping inside their guard. It is a very risky move but can be vital if the enemy has a spear and you a dagger. You can only be \"closed in\" with one combatant at the time. You can leave closed in with a successful withdraw check or it can end if one combatant is moved forcefully or grappled.\nMake an Agility + athletics roll (- opponents full reach). It is opposed by the other combatant's close combat/unarmed rolls. If you get any net successes you can close in and neither combatant can use or benefit any weapon over size 2, if they score a grazing hit you are stuck in the engagement but take no damage, if they score net hits then you stay in combat and take damage as if they had done a successful attack.",
		},
		{
			Title:   "Called Shots",
			Content: "Called shot:\nIf you wish to target a specific body part (or piece of equipment) in close or ranged combat you must spend a swift action to declare that you are doing a called shot.\n\nIn melee you suffer a -2 per size difference of the used weapon and the target. The smaller the weapon the easier it is to hit a specific point.\n\nIn ranged combat the size of your weapons have no bearing on accuracy so instead a called shot in ranged combat suffers -2 per size below 5 it targets.\n\n• Trip: -4, -8 if the target has 4+ legs.\n• Disarm: -4, -8 if the target is holding the weapon/item in 2 hands.\n• Target Vitals: -4, 2 more damage. A simple aim for a more painful spot.\n• Damage equipment: (see barriers.)\n\nBody parts for Size 5:\n• 4: Torso -2\n• 3: Leg -4, (Leg wrack, Disabled Leg)\n• 2: Arm/Head -6, (Arm wrack, Disabled Arm / Stunned)\n• 1: -8 Hand/Face/Heart/Throat\n• Vital spot: (Heart or Throat: Stun damage does Lethal, Lethal ignores half soak from Brawn)\n• 0: -10 Eye/mouth, (Lethal to eye ignores half soak from Brawn)\n\nArea Attacks do not count as called shot even though they may theoretically cover specific body parts that are vital or unarmored.",
		},
		{
			Title:   "Initiative",
			Content: "Initiative order:\nInitiative: at the beginning of each round every participant rolls 2d6 and add rating of wits+agility-(size of weapon, item or magical foci the character plans to use). Other things may also affect Initiative, such as armor, and any wound penalties.\n\nThis is just to get a number, not successes. Characters act in order of decreasing initiative.\n\nTwo weapons or weapon and shield: When planning to use two items for defense or attack during a round the initiative penalty is equal to the greatest penalty item and half (rounded up) of the lower penalty item.\n\nTies technically means that two characters act at the same time, however resolve it as follows: PAWR\nPC goes first, if both are PCs: Character with higher Agility, if same then character with higher Wits then Roll 2d6 each until one gets a higher number.\n\nSurprise: If one party catches the other unaware they are allowed one action up to a complex before combat starts and initiative is rolled.\nIf part of a party fails to surprise, only the successful ones are permitted the extra action.\nA character may not apply their defense against a character of which they are unaware.",
		},
		{
			Title:   "Range Bands",
			Content: "Range Bands:\n\nEngaged: Right next to you, 1-2 meters\n• Movement: Engaged to close: withdraw action\n• Optimal range: Melee, unarmed\n• Maximum range for: Melee, unarmed\n\nClose: In the same room, 3-10 meters\n• Movement: Close to engaged, requires 1 move\n• Optimal range: Pistols, throwing knives, grenades, machine pistols, flame throwers\n\nShort: Next room over, 10-20 meters, across a large room like a theater\n• Movement: Short to engaged requires 2 moves/run\n• Optimal range: Charge, submachine guns, javelin, shortbow/light crossbow, musket\n• Maximum range for: Charge\n\nMedium: across a square, high window to below, 20-50 meters\n• Movement: Medium to short: 2 moves, medium to engaged: 4 moves\n• Optimal range: Assault rifle, rifle, Heavy crossbow, longbow, light machine gun\n• Maximum range for: Pistols, throwing knives, grenades, machine pistols, flame throwers\n\nLong: Across a football field, snipers nest down, 50-200 meters\n• Movement: Long to medium, 4 moves, Long to engaged: 8 moves\n• Optimal range: Sniper rifle, mortar, field cannon, tank turret, ballista, heavy machine gun\n• Maximum range for: submachine guns, javelin, shortbow/light crossbow, musket\n\nExtreme: Across a battlefield, over a city center, 200-2000 meters\n• Movement: Extreme to long: 8 moves, Extreme to engaged, 16 moves \n• Optimal range: Trebuchet, siege cannons, long range artillery\n• Maximum range for: Everything else",
		},
		{
			Title:   "Combat Modifiers",
			Content: "Combat modifiers:\n\nGeneral Modifiers:\n• Defender Surprised: defender loses defense against 1st attack.\n• Aim: +1 per aim action taken (max = Cool/2). Aim is lost when engagement breaks or other active action taken.\n• Poor Visibility: -1 to -6 (-1 light fog/dim light, -6 complete darkness/smoke grenade)\n• Defender has shield: Permits defenders to parry fired missiles. Defender gets a shield bonus to parry.\n• Defending against consecutive attacks in the same round: -1 Defense per attack after the first.\n\nClose combat:\n• Attacker has greater reach: -1 per reach difference to defenders parry roll. (Does not apply to Dodge)\n• Parrying Defender has greater reach: -1 per reach difference to attackers attack roll. (Does not apply against Dodge)\n• Called shot: -2 to hit per size difference of weapon and target\n• Charge: +2 Attack, -2 defense until next turn. Applies to parry or dodge\n• Defender has shield: Defender gets a shield bonus to parry.\n• Friends in melee: +1 for each allied fighter in the same engagement. In excess to the enemy\n\nRanged Combat:\n• Attacker at range: -2 per range band outside optimal. (Penalties to shorter ranges do not apply against stationary/unaware targets)\n• Attacker Engaged: -1 per weapon size (stacks with range penalty). Applies to shooting engaged enemies or shooting other targets while engaged.\n• Wind: -1 to -6 (-1 light breeze, -6 storm)\n• Small defender: -2 to attack per target size smaller than 5\n• Large defender: +2 to attack per target size larger than 5\n• Called shot: -2 to attack per target size smaller than 5\n• Burst fire: Defender suffers -2, Attackers brawn requirement increases by 2\n• Fully automatic fire: Makes it an Area: engaged attack: Defender suffers -3, Attackers brawn requirement doubled\n• Shooting into engagement: -2 distracted penalty to defender. If major complication: hit ally instead.\n• Defender in cover: +2, +4 or +6 to the defender depending on how much cover.\n• Area: Engaged: -4 to defender\n• Area: close: -8 to defender\n• Defender is running: -2 to attacker\n• Attacker is running: -4 to attacker",
		},
		{
			Title:   "Size Chart",
			Content: "Size Chart:\n12. Helicopter, semi truck, large bus, house/large apartment, private jet\n11. Small aircraft, bus, apartment/small house, trailer\n10. Mammoth, large car, truck coupe, bedroom\n9. Elephant, sedan car, carriage, tool shed\n8. small carriage, compact car, rhino\n7. Giant, tuk-tuk, field cannon, horse, bear\n6. Troll, heavy machine gun, motorcycle \n5. normal human/orc/elf, longbow, sniper rifle, bicycle, moped. Light machine gun. Chainsaw\n4. Halfling/gnome, dwarf, human torso, heavy crossbow, assault rifle, two handed sword, human child, tower shield\n3. Human leg, arming sword, shortbow, submachine gun, light crossbow, shield\n2. human arm, heavy/machine pistol, baby, short sword, buckler, rapier\n1. hand, dagger, pouch, face, light pistol\n0. eye, coin. Holdout pistol",
		},
		{
			Title:   "Barriers and Cover",
			Content: "Barriers and Cover:\n\nStructure: an object's \"health\", known as its \"structure rating\" is equal to its size + armor rating. A wall is typically size 8-12 depending on how big. In addition when trying to get through a wall. Each layer of the typical thickness adds half again as much size and armor to the structure rating.\n\nSoak: when damaging an object directly rather than trying to pierce it (such as with armor) it has a soak value of armor x2.\n\nArmor: This is the value added to any target behind cover when trying to shoot through the material.\n\nDamaging objects: In order to damage an object a weapon's damage must have a base damage value (or brawn + damage) greater than the object's soak - Armor piercing.\nObjects with armor value >0 can only be damaged with weapons that do Lethal damage.\n\nAttacking through objects: To pierce a barrier the weapon used has to be able to damage it. If it can then the attack proceeds as normal with the target adding the barriers armor (not doubled) to their soak. A pierced object suffers 1 structure damage.\n\nCover Types:\n• Light: +2 to defense covered characters with ranged weapons. Character covers roughly 50% of their body\n• Medium: +4 to defense covered characters with ranged weapons. Character covers roughly 75% of their body\n• Heavy: +6 to defense covered characters with ranged weapons. Character covers roughly 90% of their body\n• Full: must shoot through cover to hit covered character. Characters cover 100% of their body",
		},
		{
			Title:   "Vehicle Combat",
			Content: "Vehicle/Drone Combat:\nVehicle combat follows the same basic rules as regular combat but with some modifications for the scale and complexity of vehicle engagements.\n\nVehicles have their own initiative based on the pilot's skills and the vehicle's handling characteristics. Vehicle weapons follow the same rules as regular weapons but may have different range bands and damage values appropriate to their scale.\n\nDrone combat can be controlled remotely or autonomously, with different rules for each mode of operation.",
		},
		{
			Title:   "Environmental Hazards in Combat",
			Content: "Environmental Hazards in Combat:\nVarious environmental factors can affect combat effectiveness and safety:\n\n• Poor visibility (fog, smoke, darkness) applies penalties to attack rolls\n• Difficult terrain can affect movement and provide cover\n• Extreme temperatures can cause fatigue and other conditions\n• Hazardous environments (toxic gas, radiation) may cause ongoing damage\n• Weather conditions (rain, wind, snow) can affect ranged attacks and movement\n\nThese hazards are typically represented as penalties to relevant rolls or as conditions that affect characters over time.",
		},
		// Equipment Rules
		{
			Title:   "Equipment Overview",
			Content: "Equipment encompasses all items that characters can carry, wear, or use. This includes weapons, armor, tools, vehicles, and personal gear.\n\nEquipment is categorized by:\n• Type: Weapons, Armor, Tools, Personal Gear, Vehicles\n• Era: Medieval, Industrial, Cyber\n• Rarity: Civilian (0), Restricted (1-3), Military (4-5)\n• Quality: Standard, Exceptional, Masterwork\n\nCharacters start with 6000c worth of equipment. Each starting point has maximum rarity limits for equipment. Equipment can be obtained through purchase, crafting, or acquisition, and can be modified to enhance capabilities.",
		},
		{
			Title:   "Weapon Rules",
			Content: "Weapons are categorized by type, damage, size, and special properties.\n\nDamage: Weapons have a base damage rating that is added to Brawn for melee weapons or used directly for ranged weapons. Bows may add Brawn/2 instead.\n\nSize: Determines encumbrance, initiative penalties, and reach. Larger weapons require higher Wits to quickdraw (2x weapon size).\n\nType: Blade, Club, Axe, Polearm, Throwing, Exotic, etc. Determines which skills can be used.\n\nSpecial Properties:\n• Armor Piercing: Reduces target's armor rating\n• Parrying: Bonus to parry defense\n• Quick: Can be drawn as a free action\n• Throwing: Can be thrown effectively\n• Concealed: Easier to hide\n• Brawling: Can be used in unarmed combat\n• Restraining: Can grapple or bind targets\n• Tripping: Can knock targets prone\n• Disarming: Can disarm opponents\n• Gaping Wounds: Causes bleeding\n• Risky: Can harm the wielder on complications\n• Fragile: Easily damaged\n• Inaccurate: Penalty to attack rolls\n• Loud: Makes noise when used\n• Flaming: Sets targets on fire\n• Shocking: Stuns targets\n• Gruesome: Causes fear or horror",
		},
		{
			Title:   "Armor Rules",
			Content: "Armor provides protection by adding to Soak value and Lethal Threshold.\n\nArmor Rating: Adds to character's Soak value and Lethal Threshold. Incoming damage is decreased by Brawn/2 + Effective Armor Rating.\n\nLethal Threshold: If a Lethal Weapon's Base Damage + Armor Piercing Value is higher than Armor Rating x2, damage is Lethal; otherwise it becomes Stun Damage.\n\nSize: Determines coverage area. Size 5: Full body except head. Size 4: Torso and Arms. Size 3: Torso only.\n\nType: Soft (leather, cloth) or Hard (metal, ceramic). Affects layering rules.\n\nArmor Layers: Up to 2 layers can be combined if at least one is Soft. Character gets full bonus of best layer + half bonus of second layer. Additional penalty of -1 to all physical actions, Initiative, and Defense per extra layer.\n\nBallistic Rating: Used only against firearms (weapons with 'ballistic' tag). Medieval armor has low ballistic ratings.\n\nLocation Specific: Helmets and location armor only protect against called shots to that location. Only highest penalty from armor type applies.",
		},
		{
			Title:   "Equipment Quality and Rarity",
			Content: "Equipment has both quality and rarity ratings that affect availability and effectiveness.\n\nQuality:\n• Standard: Normal equipment with no bonuses\n• Exceptional: +1 to relevant rolls or +1 armor/damage\n• Masterwork: +2 to relevant rolls or +2 armor/damage\n\nRarity:\n• 0 (Civilian): Readily available, no restrictions\n• 1-2 (Restricted): Requires permits or special access\n• 3-4 (Military): Limited to military or law enforcement\n• 5 (Illegal): Banned or highly controlled\n\nObtaining Equipment: Characters must make Streetwise + Power rolls to find restricted equipment. Successes determine availability and price.\n\nSelling Equipment: Characters receive 50% + (5% x rarity) of market value as base, modified by Streetwise + Power successes.",
		},
		{
			Title:   "Weapon Modifications",
			Content: "Weapons can be modified to enhance their capabilities or add new functions.\n\nModification Slots: Each weapon has a limited number of modification slots based on size and type.\n\nStandard Mods: Come with the weapon and can sometimes be removed. Still take modification slots.\n\nCommon Modifications:\n• Scopes: Improve accuracy at range\n• Suppressors: Reduce noise\n• Extended Magazines: Increase ammunition capacity\n• Bayonets: Add melee capability\n• Mono-edging: Increase armor piercing\n• Smart Systems: Improve accuracy\n• Concealment: Make weapons easier to hide\n• Custom Grips: Improve handling\n• Reinforced Construction: Increase durability\n• Special Ammunition: Various effects\n\nCompatibility: Some modifications are incompatible with others. GM determines compatibility.",
		},
		{
			Title:   "Armor Modifications",
			Content: "Armor can be modified to enhance protection or add functionality.\n\nModification Capacity: Based on armor size and type. Larger armor has more modification slots.\n\nCommon Modifications:\n• Reinforced Plating: Increase armor rating\n• Concealment: Make armor less visible\n• Climate Control: Maintain comfortable temperature\n• Medical Systems: Monitor health and provide treatment\n• Communication Systems: Built-in radios or commlinks\n• Power Systems: Provide energy for other modifications\n• Camouflage: Blend with environment\n• Storage: Hidden compartments\n• Mobility Enhancements: Reduce movement penalties\n• Sensor Systems: Improve awareness\n\nLayering: Modified armor follows normal layering rules. Modifications don't affect layer limits.",
		},
		{
			Title:   "Obtaining and Selling Equipment",
			Content: "Equipment can be obtained through various means and sold for profit.\n\nObtaining Equipment:\n• Purchase: Standard civilian equipment available in shops\n• Restricted Equipment: Requires Streetwise + Power roll\n  - Base difficulty: Rarity rating\n  - Allies can reduce difficulty\n  - Paying 50% extra reduces difficulty by 1\n  - Successes determine availability and price\n\nSelling Equipment:\n• Base return: 50% + (5% x rarity) of market value\n• Streetwise + Power roll adds 5% per success\n• Maximum return: 100% of market value\n• Damaged equipment sells for less\n• Rare equipment may attract unwanted attention\n\nBlack Market: Illegal equipment requires special contacts and higher risks. Law enforcement may investigate large transactions.",
		},
		{
			Title:   "Encumbrance and Carrying Capacity",
			Content: "Characters have limits on how much they can carry and how it affects their abilities.\n\nCarrying Capacity: Brawn x 2 in kilograms. Characters can carry up to this amount without penalty.\n\nEncumbrance Levels:\n• Light: Up to carrying capacity\n• Medium: Up to 1.5x carrying capacity (-1 to physical actions)\n• Heavy: Up to 2x carrying capacity (-2 to physical actions)\n• Overloaded: Beyond 2x capacity (-4 to physical actions)\n\nItem Size: Most items have a size rating equal to their encumbrance in kilograms. Some items are lighter (Light tag) or heavier than their size suggests.\n\nStorage Solutions:\n• Backpacks: Increase effective carrying capacity\n• Belt pouches: Hold small items\n• Weapon sheaths: Secure weapons for quick access\n• Armor storage: Specialized containers for armor\n\nMovement: Heavy encumbrance affects movement speed and initiative. Characters may need to drop items to move effectively.",
		},
		{
			Title:   "Dwarves",
			Content: "Dwarves are stout and hardy folk known for their craftsmanship and resilience. They have earth and stone colored skin, and are typically shorter and more muscular than humans.\n\nAttribute Modifiers:\n- +2 to Brawn\n- -1 to Agility\n\nSpecial Qualities:\n- Dwarven Toughness: Dwarves gain the 'Dwarven Toughness' quality for free at character creation. This quality provides additional resistance to physical damage and environmental hazards.\n\nCultural Traits:\n- Master craftsmen and artisans\n- Strong connection to earth and stone\n- Traditional and conservative values\n- Excellent miners and engineers\n- Known for their resilience and determination\n\nStarting Languages:\n- Common\n- Dwarvish\n\nDwarves excel in physical labor, crafting, and combat situations where their natural toughness and strength provide advantages. Their reduced agility is offset by their superior durability and craftsmanship skills.",
		},
		{
			Title:   "Elves",
			Content: "Elves are long-lived and graceful beings known for their wisdom and connection to nature. They are typically taller and more slender than humans, with pointed ears and an ethereal beauty.\n\nAttribute Modifiers:\n- +1 to Logic\n- +1 to Wits\n- -1 to Brawn\n\nSpecial Qualities:\n- Elven Grace: Elves gain the 'Elven Grace' quality for free at character creation. This quality provides bonuses to agility-based actions and aesthetic pursuits.\n\nCultural Traits:\n- Deep connection to nature and magic\n- Long-lived with extended perspective on time\n- Artistic and philosophical inclinations\n- Masters of archery and magic\n- Known for their wisdom and patience\n\nStarting Languages:\n- Common\n- Elvish\n\nElves excel in mental pursuits, magic, archery, and social situations where their grace and wisdom provide advantages. Their reduced physical strength is compensated by their superior mental attributes and magical abilities.",
		},
		{
			Title:   "Halflings",
			Content: "Halflings are small and lucky folk known for their good fortune and adaptability. They are typically about half the size of humans, with curly hair and cheerful dispositions.\n\nAttribute Modifiers:\n- +1 to Cool\n\nSpecial Qualities:\n- Lucky: Halflings can reroll one failed roll per session. This represents their natural good fortune and ability to find success even in difficult circumstances.\n\nCultural Traits:\n- Naturally optimistic and cheerful\n- Excellent cooks and hosts\n- Skilled at avoiding notice\n- Strong community bonds\n- Known for their adaptability and resourcefulness\n\nStarting Languages:\n- Common\n- Halfling\n\nHalflings excel in social situations, stealth, and any activity where their natural luck and adaptability can provide advantages. Their small size can be a disadvantage in physical confrontations, but their luck and agility often help them avoid such situations.",
		},
		{
			Title:   "Humans",
			Content: "Humans are adaptable and versatile beings known for their flexibility and determination. They are the most common species and can be found in almost every environment and culture.\n\nAttribute Modifiers:\n- No attribute modifiers\n\nSpecial Qualities:\n- Adaptable: Humans can spend 1 experience point to gain a skill specialty in any skill they have at least 1 rank in. This represents their natural ability to adapt and learn quickly.\n\nCultural Traits:\n- Highly adaptable to different environments\n- Diverse cultures and societies\n- Ambitious and driven\n- Quick learners and innovators\n- Known for their determination and resilience\n\nStarting Languages:\n- Common\n- One additional language of choice\n\nHumans excel in versatility and adaptability. They may not have the natural advantages of other species, but their flexibility allows them to excel in almost any field through hard work and determination.",
		},
		{
			Title:   "Orcs",
			Content: "Orcs are strong and fierce warriors known for their physical prowess and tribal culture. They are typically larger and more muscular than humans, with prominent tusks and greenish skin.\n\nAttribute Modifiers:\n- +2 to Brawn\n- -1 to Cool\n\nSpecial Qualities:\n- Fierce: Orcs gain bonuses in combat situations and when facing physical challenges. Their natural aggression and strength make them formidable opponents.\n\nCultural Traits:\n- Strong tribal and clan bonds\n- Warrior culture and traditions\n- Respect for strength and honor\n- Skilled hunters and trackers\n- Known for their loyalty and courage\n\nStarting Languages:\n- Common\n- Orcish\n\nOrcs excel in physical combat, hunting, and any activity where their strength and ferocity provide advantages. Their reduced composure can make them more prone to emotional outbursts, but also makes them more passionate and driven.",
		},
		{
			Title:   "Trolls",
			Content: "Trolls are massive and powerful beings known for their incredible strength and durability. They are the largest of the common species, with thick skin and regenerative abilities.\n\nAttribute Modifiers:\n- +3 to Brawn\n- -2 to Agility\n- -1 to Cool\n\nSpecial Qualities:\n- Regeneration: Trolls have natural regenerative abilities that allow them to recover from injuries more quickly than other species.\n- Thick Skin: Trolls have natural armor due to their thick, tough skin.\n\nCultural Traits:\n- Solitary or small family groups\n- Territorial and protective\n- Strong connection to their environment\n- Skilled at survival and endurance\n- Known for their patience and persistence\n\nStarting Languages:\n- Common\n- Trollish\n\nTrolls excel in physical combat, endurance activities, and any situation where their incredible strength and durability provide advantages. Their reduced agility and composure are significant drawbacks, but their raw power often compensates for these limitations.",
		},
	}
}
