package seeds

import (
	"github.com/google/uuid"
	"github.com/mremperor-atwork/rpg1/api1/internal/features/srd"
)

func GetSRDEntries() []srd.SRDEntry {
	return []srd.SRDEntry{
		{
			ID:       uuid.New(),
			Title:    "Design Philosophy",
			Category: "Core Rules",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "How to Play - Basic Rules",
			Category: "Core Rules",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Character Creation Overview",
			Category: "Character Creation",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Attributes - General Rules",
			Category: "Attributes",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Derived Stats",
			Category: "Attributes",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Skills - General Rules",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Skill Specialties",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Extended Rolls",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Qualities - General Rules",
			Category: "Qualities",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Experience and Advancement",
			Category: "Character Advancement",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Magic - General Rules",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Magic Schools",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Combat - Basic Rules",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Equipment - General Rules",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Species Overview",
			Category: "Species",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Tolerance System",
			Category: "Core Rules",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Modifiers",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Conditions and Status Effects",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Physical Skills - Athletics",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Physical Skills - Melee",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Physical Skills - Pilot",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Physical Skills - Ranged",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Physical Skills - Stealth",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Physical Skills - Thievery",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Physical Skills - Unarmed",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Mental Skills - Academics",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Mental Skills - Crafts",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Mental Skills - Investigation",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Mental Skills - Medicine",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Mental Skills - Nature Lore",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Mental Skills - Occult",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Mental Skills - Science",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Skills - Empathy",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Skills - Performance",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Skills - Intimidation",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Skills - Persuasion",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Skills - Streetwise",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Skills - Style",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Skills - Subterfuge",
			Category: "Skills",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Divine Doctrines",
			Category: "Qualities",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Pantheon of the Gods",
			Category: "Religion",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "God-Spawn",
			Category: "Qualities",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Spiritual Guide",
			Category: "Qualities",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Explosives - Overview",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Explosives - Planting Rules",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Explosives - Medieval Era",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Explosives - Industrial Era",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Explosives - Cyber Era",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Detonators - Overview",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Detonators - Medieval Era",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Detonators - Industrial Era",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Detonators - Cyber Era",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Explosive Add-ons",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Vehicle Modifications - Overview",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Vehicle Armor",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Vehicle Weapon Mounts",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Vehicle Performance Upgrades",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Vehicle Electronics",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dwarves",
			Category: "Species",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Elves",
			Category: "Species",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Halflings",
			Category: "Species",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Humans",
			Category: "Species",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Orcs",
			Category: "Species",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Trolls",
			Category: "Species",
			Version:  1,
		},
		// Magic System Entries
		{
			ID:       uuid.New(),
			Title:    "What is Magic?",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "The Gift and Astral Realms",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Limits of Magic",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Godspeech and Gestures",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Spellcasting Rules",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Spell Levels and Backlash",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Spell Terms and Attributes",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Targeting and Range",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Ritual Spellcasting",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Anchored Magic",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Conjunctive Magic",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Reagents and Foci",
			Category: "Magic",
			Version:  1,
		},
		// Individual Spell Entries - Air Magic
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Spy the Unseen (Level 1)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Sense Electricity (Level 1)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Understand Physics (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Cut through hardship (Level 3)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Air is no resistance (Level 3)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Mage hand (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Shift Current (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Kinetic Shield (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Wind Wall (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Slow Fall (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Alter Speed (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Light Body (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Alter Current (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Telekinetic Push (Level 7)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Lightning (Level 7)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Flash Forward (Level 8)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Wind Walking (Level 8)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Telekinetic Strength (Level 9)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Wind Blades (Level 9)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Telekinetic Grasp (Level 10)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Air Magic - Fly (Level 10)",
			Category: "Magic",
			Version:  1,
		},
		// Individual Spell Entries - Dark Magic
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Detect Undead (Level 1)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Sense Hatred (Level 1)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Know Undead (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Sense Weakness (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Speak with Dead (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Darken Shadows (Level 3)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Pierce Darkness (Level 3)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Direct Ire (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Command Undead (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Emotional Shield (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Shield of Darkness (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Curse (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Deteriorate (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Necrotic Energy (Level 7)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Raise Undead (Level 7)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Transform into Greater Undead (Level 8)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Raise Shade (Level 9)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Corruption (Level 9)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Implant Emotion (Level 10)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Dark Magic - Cold Snap (Level 10)",
			Category: "Magic",
			Version:  1,
		},
		// Individual Spell Entries - Earth Magic
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Sense object (Level 1)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Radar (Level 1)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Understand mechanism (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Know Strength/Weakness (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Minor Matter Alteration (Level 3)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Move Earth (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Magnetism (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Earth Wall (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Earth Cocoon (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Enhance/De-Enhance Object (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Rust (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Unshakable (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Shape Item (Level 7)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Earth Shape (Level 7)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Lead into Gold (Level 8)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Quicksand (Level 9)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Rock Solid (Level 9)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Earth Spike (Level 10)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Earth Magic - Golem (Level 10)",
			Category: "Magic",
			Version:  1,
		},
		// Individual Spell Entries - Illusion Magic
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - See through Illusions (Level 1)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Sense Minds (Level 1)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Read Surface Thoughts (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Know Falsehood (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Emperor's new clothes (Level 3)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Soothe emotions (Level 3)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Illusory Sound (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Entertainment (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Mirror Image (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Concealing Fog (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Charm (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Invisibility (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Illusory Image (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Mind Trick (Level 7)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Telepathy (Level 7)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - False Impression (Level 8)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Undetectable (Level 8)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Major Image (Level 9)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Glamour (Level 9)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Imaginary wounds (Level 10)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Illusion Magic - Rewrite Reality (Level 10)",
			Category: "Magic",
			Version:  1,
		},
		// Individual Spell Entries - Light Magic
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Sense Heat (Level 1)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Sense Health (Level 1)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Diagnose (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Arsonology (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Minor Fire Alteration (Level 3)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Joy (Level 3)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Firebolt (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Stop Bleeding (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Move Light (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Shield of Fire (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - False Health (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Alter Flame (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Heal (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Searing light (Level 7)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Pleasure (Level 7)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Flaming Weapon (Level 8)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Body of flame (Level 8)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Sweltering Heat (Level 9)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Restore (Level 9)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Suns Wrath (Level 10)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Light Magic - Absolute Peace (Level 10)",
			Category: "Magic",
			Version:  1,
		},
		// Individual Spell Entries - Nature Magic
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Sense life (Level 1)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Sense corruption (Level 1)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Speak With animal (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Know beast/plant (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Know instinct (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Cat eyes (Level 3)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Natures ally (Level 3)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Animal Friendship (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Natures enemy (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Enhance Immune system (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Barkskin (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Partial Beast Shape (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Animal instincts (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Control animal (Level 7)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Entangle (Level 7)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Beast Shape (Level 8)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Regeneration (Level 8)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Greater beast (Level 9)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Plague (Level 9)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Swarm (Level 10)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Nature Magic - Fight or Flight (Level 10)",
			Category: "Magic",
			Version:  1,
		},
		// Individual Spell Entries - Summoning Magic
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Sense Bindings (Level 1)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Sense Magic (Level 1)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Summon Sage (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Know Summon (Level 2)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Alter Resonance (Level 3)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Free Summon (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Make Pact (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Summon Object (Level 4)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Spell Defense (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Defensive Summon (Level 5)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Possession (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Spirit Barrier (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Suppress Magic (Level 6)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Summon Being (Level 7)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Banish (Level 7)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Prepare Vessel (Level 8)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Inhabitation (Level 8)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Extradimensional Space (Level 9)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Bind (Level 9)",
			Category: "Magic",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Summoning Magic - Open Gate (Level 10)",
			Category: "Magic",
			Version:  1,
		},
		// Additional Game Systems
		{
			ID:       uuid.New(),
			Title:    "Hacking and Matrix",
			Category: "Technology",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Combat - Advanced Rules",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Chases and Movement",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Environmental Hazards",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Weapons and Armor",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Cyberware and Augmentations",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Vehicles and Transportation",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Chemicals and Drugs",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Creatures and Summons",
			Category: "Game World",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Training and Tutors",
			Category: "Character Advancement",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Lifestyle and Social Status",
			Category: "Game World",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Cheat Sheet",
			Category: "Reference",
			Version:  1,
		},
		// Combat Rules
		{
			ID:       uuid.New(),
			Title:    "Combat Overview",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Combat Actions",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Complex Actions",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Simple Actions",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Swift Actions",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Free Actions",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Attack and Defense",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Critical Successes in Combat",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Combat Complications",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Grappling",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Area Attacks",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Charge",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Full Defense",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Ready Action",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Close Combat Attack",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Ranged Combat",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Aiming",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Withdraw and Close In",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Called Shots",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Initiative",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Range Bands",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Combat Modifiers",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Size Chart",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Barriers and Cover",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Vehicle Combat",
			Category: "Combat",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Environmental Hazards in Combat",
			Category: "Combat",
			Version:  1,
		},
		// Equipment Rules
		{
			ID:       uuid.New(),
			Title:    "Equipment Overview",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Weapon Rules",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Armor Rules",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Equipment Quality and Rarity",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Weapon Modifications",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Armor Modifications",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Obtaining and Selling Equipment",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Encumbrance and Carrying Capacity",
			Category: "Equipment",
			Version:  1,
		},
		// Matrix and Hacking
		{
			ID:       uuid.New(),
			Title:    "The Matrix - Overview",
			Category: "Matrix",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Matrix Terminology",
			Category: "Matrix",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Legal Matrix Uses",
			Category: "Matrix",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Matrix Research",
			Category: "Matrix",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Virtual Reality",
			Category: "Matrix",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Hacking - Overview",
			Category: "Hacking",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Hacking Modifiers",
			Category: "Hacking",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Hacking Equipment",
			Category: "Hacking",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Programs - Legal",
			Category: "Hacking",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Programs - Illegal",
			Category: "Hacking",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Object Structure and Damage",
			Category: "Hacking",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Forked Quickhack",
			Category: "Hacking",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Sustained Quickhack",
			Category: "Hacking",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Quickhacking Actions - Overview",
			Category: "Hacking",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Scanning",
			Category: "Hacking",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Overload",
			Category: "Hacking",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Disrupt",
			Category: "Hacking",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Control",
			Category: "Hacking",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Virtual Reality Hacking - Overview",
			Category: "Hacking",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "VR Hacking Actions",
			Category: "Hacking",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "VR Hacking Penalties",
			Category: "Hacking",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Database Firewall Ratings",
			Category: "Hacking",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Failing VR Hacking Rolls",
			Category: "Hacking",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Search",
			Category: "Hacking",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Datasteal",
			Category: "Hacking",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Alter Data",
			Category: "Hacking",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Hacking Examples",
			Category: "Hacking",
			Version:  1,
		},
		// Health and Healing
		{
			ID:       uuid.New(),
			Title:    "Health - Overview",
			Category: "Health",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Health Calculation",
			Category: "Health",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Temporary Health",
			Category: "Health",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Wounds - Overview",
			Category: "Health",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Damage Types",
			Category: "Health",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Wound Penalties",
			Category: "Health",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Wound Recovery",
			Category: "Health",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Healing - Overview",
			Category: "Health",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Natural Healing",
			Category: "Health",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Medical Treatment",
			Category: "Health",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Magical Healing",
			Category: "Health",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Healing Complications",
			Category: "Health",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Death and Dying",
			Category: "Health",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Bleeding Out",
			Category: "Health",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Stabilization",
			Category: "Health",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Resurrection",
			Category: "Health",
			Version:  1,
		},
		// Environmental Hazards
		{
			ID:       uuid.New(),
			Title:    "Environmental Hazards - Overview",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Falling",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Falling from Vehicles",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Fire",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Acid",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Exhaustion",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Pollution",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Radioactivity",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Cold - Overview",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Cold - Mild",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Cold - Severe",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Cold - Deadly",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Heat - Overview",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Heat - Mild",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Heat - Severe",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Heat - Deadly",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Weather - Overview",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Weather Effects on Vehicles",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Terrain - Overview",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Difficult Terrain",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Vehicle Operation",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Unsafe Speeds",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Vehicle Combat",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Vehicle Crashes",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Chases - Overview",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Foot Chases",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Vehicle Chases",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Chase Speed and Location",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Survival - Overview",
			Category: "Environment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Environmental Adaptation",
			Category: "Environment",
			Version:  1,
		},
		// Advanced Systems
		{
			ID:       uuid.New(),
			Title:    "Social Mechanics - Overview",
			Category: "Advanced",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Modifiers",
			Category: "Advanced",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Reputation System",
			Category: "Advanced",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Lifestyle - Overview",
			Category: "Advanced",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Lifestyle - Destitute",
			Category: "Advanced",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Lifestyle - Poor",
			Category: "Advanced",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Lifestyle - Decent",
			Category: "Advanced",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Lifestyle - Well Off",
			Category: "Advanced",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Lifestyle - Rich",
			Category: "Advanced",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Lifestyle - Wealthy",
			Category: "Advanced",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Skills - Empathy",
			Category: "Advanced",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Skills - Performance",
			Category: "Advanced",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Skills - Intimidation",
			Category: "Advanced",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Skills - Persuasion",
			Category: "Advanced",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Skills - Streetwise",
			Category: "Advanced",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Skills - Style",
			Category: "Advanced",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Skills - Subterfuge",
			Category: "Advanced",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Contact Networks",
			Category: "Advanced",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Fame and Recognition",
			Category: "Advanced",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Influence and Status",
			Category: "Advanced",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Qualities - Positive",
			Category: "Advanced",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Qualities - Negative",
			Category: "Advanced",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Combat",
			Category: "Advanced",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Consequences",
			Category: "Advanced",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Gear and Equipment",
			Category: "Advanced",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Social Magic",
			Category: "Advanced",
			Version:  1,
		},
		// Vehicles & Chases
		{
			ID:       uuid.New(),
			Title:    "Vehicles - Overview",
			Category: "Vehicles",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Vehicle Penalties",
			Category: "Vehicles",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Vehicle Bonuses",
			Category: "Vehicles",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Unsafe Speeds",
			Category: "Vehicles",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Vehicle Combat",
			Category: "Vehicles",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Vehicle Movement",
			Category: "Vehicles",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Vehicle Crashes",
			Category: "Vehicles",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Chases - Overview",
			Category: "Vehicles",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Foot Chases",
			Category: "Vehicles",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Vehicle Chases",
			Category: "Vehicles",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Chase Speed",
			Category: "Vehicles",
			Version:  1,
		},
		// Augmentations
		{
			ID:       uuid.New(),
			Title:    "Augmentations - Overview",
			Category: "Augmentations",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Augmentation Quality",
			Category: "Augmentations",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Cyberware - Overview",
			Category: "Augmentations",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Cyberware - Basic Implants",
			Category: "Augmentations",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Cyberware - Limb Replacements",
			Category: "Augmentations",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Cyberware - Attribute Enhancements",
			Category: "Augmentations",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Cyberware - Sensory Implants",
			Category: "Augmentations",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Cyberware - Combat Implants",
			Category: "Augmentations",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Cyberware - Utility Implants",
			Category: "Augmentations",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Cyberware Modifications",
			Category: "Augmentations",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Bioware - Overview",
			Category: "Augmentations",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Bioware - Attribute Enhancements",
			Category: "Augmentations",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Bioware - Sensory Enhancements",
			Category: "Augmentations",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Bioware - Physical Enhancements",
			Category: "Augmentations",
			Version:  1,
		},
		// Gamemaster Section
		{
			ID:       uuid.New(),
			Title:    "Gamemaster - Overview",
			Category: "Gamemaster",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Running the Game",
			Category: "Gamemaster",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Adventure Design",
			Category: "Gamemaster",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "NPC Creation",
			Category: "Gamemaster",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Campaign Management",
			Category: "Gamemaster",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Storytelling Techniques",
			Category: "Gamemaster",
			Version:  1,
		},
		// Additional Missing Sections
		{
			ID:       uuid.New(),
			Title:    "Drugs and Substances",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Tools and Equipment",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Communication Equipment",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Surveillance Equipment",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Medical Equipment",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Security Equipment",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Entertainment Equipment",
			Category: "Equipment",
			Version:  1,
		},
		{
			ID:       uuid.New(),
			Title:    "Cheat Sheet",
			Category: "Reference",
			Version:  1,
		},
	}
}
